export const SEND_MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "date",
    headerName: "LBL_REQUESTED_DELIVERY_DATE",
    field: "DLVRY_DT",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_ORG_LGST_GRP_CD",
    field: "ORG_LGST_GRP_CD",
    align: "center",
    width: 130,
  },
  {
    type: "text",
    headerName: "LBL_TRANSFERED_LGST_GRP_CD",
    field: "LGST_GRP_CD",
    align: "center",
    width: 130,
  },
  {
    type: "text",
    headerName: "LBL_SHIPMENT_NUMBER",
    field: "SHPM_NO",
    align: "center",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_ORD_DO",
    field: "ORD_NO",
    align: "center",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_CODE",
    field: "FRM_LOC_CD",
    align: "center",
    width: 80,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_NAME",
    field: "FRM_LOC_NM",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_ADDRESS",
    field: "FRM_DTL_ADDR1",
    align: "left",
    width: 200,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_CD",
    field: "TO_LOC_CD",
    align: "center",
    width: 80,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_NM",
    field: "TO_LOC_NM",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_ADDRESS",
    field: "TO_DTL_ADDR1",
    align: "left",
    width: 200,
  },
  {
    type: "text",
    headerName: "LBL_SOLD_TO_CD",
    field: "SOLD_TO_CD",
    align: "left",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_SOLD_TO_NM",
    field: "SOLD_TO_NM",
    align: "left",
    width: 120,
  },
  {
    type: "combo",
    headerName: "LBL_ORDER_TYPE",
    field: "ORD_TP",
    codeKey: "ordTpList",
    align: "center",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_NET_VOL",
    field: "PLN_NET_VOL",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_VOL",
    field: "PLN_GRS_VOL",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_NET_WGT",
    field: "PLN_NET_WGT",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_WGT",
    field: "PLN_GRS_WGT",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PLT_QTY",
    field: "PLN_PLT_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_RTNR_QTY",
    field: "PLN_RTNR_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PBOX_QTY",
    field: "PLN_PBOX_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_BOX_QTY",
    field: "PLN_BOX_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY1",
    field: "PLN_FLEX_QTY1",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY2",
    field: "PLN_FLEX_QTY2",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY3",
    field: "PLN_FLEX_QTY3",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY4",
    field: "PLN_FLEX_QTY4",
    align: "right",
    width: 150,
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY5",
    field: "PLN_FLEX_QTY5",
    align: "right",
  },
  {
    type: "text",
    headerName: "LBL_PLAN_ID",
    field: "PLN_ID",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_PLAN_NAME",
    field: "PLN_NM",
    align: "left",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_TRANSFERED_USR_ID",
    field: "SHPM_TRNSFR_USR_ID",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_TRANSFERED_DTTM",
    field: "SHPM_TRNSFR_DTTM",
    align: "center",
    width: 180,
  },
];

export const RCV_MAIN_COLUMN_DEFS = SEND_MAIN_COLUMN_DEFS.filter(
  (col) => !("field" in col) || col.field !== "ORD_TP",
);

export const DETAIL_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_LINE_NO",
    field: "ORD_LINE_NO",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_CD",
    field: "CUST_ITEM_CD",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_NM",
    field: "CUST_ITEM_NM",
    align: "left",
    width: 120,
  },
  {
    type: "combo",
    headerName: "LBL_TEMP_TCD",
    field: "TEMP_TCD",
    codeKey: "vehTempTcd",
    align: "left",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_ORD_QTY",
    field: "PLN_ORD_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_PLN_ORD_QTY_UOM",
    field: "PLN_ORD_QTY_UOM",
    codeKey: "itmUomList",
    align: "left",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_INV_QTY",
    field: "PLN_INV_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_PLN_INV_QTY_UOM",
    field: "PLN_INV_QTY_UOM",
    codeKey: "itmUomList",
    align: "left",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_NET_VOL",
    field: "PLN_NET_VOL",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_VOL",
    field: "PLN_GRS_VOL",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_NET_WGT",
    field: "PLN_NET_WGT",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_WGT",
    field: "PLN_GRS_WGT",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PLT_QTY",
    field: "PLN_PLT_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_RTNR_QTY",
    field: "PLN_RTNR_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PBOX_QTY",
    field: "PLN_PBOX_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_BOX_QTY",
    field: "PLN_BOX_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY1",
    field: "PLN_FLEX_QTY1",
    align: "right",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY2",
    field: "PLN_FLEX_QTY2",
    align: "right",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY3",
    field: "PLN_FLEX_QTY3",
    align: "right",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY4",
    field: "PLN_FLEX_QTY4",
    align: "right",
    width: 150,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY5",
    field: "PLN_FLEX_QTY5",
    align: "right",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_RMRK",
    field: "SHPM_DTL_RSN_DESC",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_REFER_ORD",
    field: "REFER_ORD_NO",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_REFER_ORD_LINE_NO",
    field: "REFER_ORD_LINE_NO",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    align: "center",
    width: 150,
  },
];

export const POP_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_TRNF_HIST_CD",
    field: "TRNF_HIST_CD",
    align: "center",
    flex: 1,
  },
  {
    type: "text",
    headerName: "LBL_ORG_LGST_GRP_CD",
    field: "ORG_LGST_GRP_CD",
    align: "center",
    flex: 1,
  },
  {
    type: "text",
    headerName: "LBL_TRANSFERED_LGST_GRP_CD",
    field: "LGST_GRP_CD",
    align: "center",
    flex: 1,
  },
  {
    type: "text",
    headerName: "LBL_TRANSFERED_DTTM",
    field: "TRANSFERED_DTTM",
    align: "center",
    flex: 1,
  },
  {
    type: "text",
    headerName: "LBL_TRANSFERED_USR_ID",
    field: "TRANSFERED_USR_ID",
    align: "center",
    flex: 1,
  },
];
