export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "datetime",
    headerName: "LBL_RECEIVE_DATE",
    field: "CRE_DTTM",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    width: 100,
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_INTERFACE_TCD",
    field: "IF_TCD",
    codeKey: "interfaceType",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_USR_RE_PRCS_YN",
    field: "RE_PRCS_BY_USR_YN",
    width: 120,
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_PRCS_STS",
    field: "IF_PRCS_STS",
    codeKey: "interfaceStatus",
    width: 70,
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_PRCS_MSG",
    field: "IF_PRCS_MSG_CD",
    codeKey: "interfaceMessage",
    width: 200,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_PRCS_MSG_DESC",
    field: "IF_PRCS_MSG_DESC",
    width: 200,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_CD",
    field: "ITEM_CD",
    width: 80,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_NM",
    field: "ITEM_NM",
    width: 100,
    align: "left",
  },
  {
    type: "combo",
    headerName: "LBL_ITEM_TP",
    field: "ITEM_TP",
    codeKey: "itemType",
    width: 100,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_STRG_CODE",
    field: "ITEM_STRG_CD",
    width: 100,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GRP",
    field: "ITEM_GRP_CD",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_EXT_ITEM_GRP",
    field: "EXT_ITEM_GRP_CD",
    codeKey: "extItemGrp",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_ITEM_FCD",
    field: "ITEM_FCD",
    codeKey: "itemFcd",
    width: 90,
    align: "left",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_ITEM_CLASS",
    field: "ITEM_CCD",
    codeKey: "itemClass",
    width: 120,
    align: "left",
  },
  {
    type: "combo",
    headerName: "LBL_PLANT_ITEM_STS",
    field: "PLANT_ITEM_STS",
    codeKey: "plantItemSts",
    width: 120,
    align: "left",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_WGT",
    field: "GROSS_WEIGHT",
    width: 90,
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_NET_WGT",
    field: "NET_WEIGHT",
    width: 90,
    align: "right",
  },
  {
    type: "text",
    headerName: "LBL_WEIGHT_SCD",
    field: "WEIGHT_SCD",
    width: 100,
    align: "center",
  },
  {
    type: "numeric",
    headerName: "LBL_VOL",
    field: "VOL",
    width: 100,
    align: "right",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_VOL_UOM",
    field: "VOL_SCD",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_SIZE_DESCR",
    field: "SIZE_DESCR",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_PKG_GRP",
    field: "PKG_TP",
    codeKey: "pkgType",
    width: 100,
    align: "left",
  },
  {
    type: "combo",
    headerName: "LBL_TEMP_CAL_OPT",
    field: "TEMP_TCD",
    codeKey: "vehTempTcd",
    width: 100,
    align: "left",
  },
  {
    type: "combo",
    headerName: "LBL_DISTCHAIN_ITEM_STS",
    field: "DISTCHAIN_ITEM_STS",
    codeKey: "chaItemSts",
    width: 100,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_SPEC_DESCR",
    field: "SPEC_DESCR",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_PLT_SPEC_TP",
    field: "PLT_SPEC_TP",
    width: 100,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_BX_TP",
    field: "BOX_TP_DESCR",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_EXT_BOX_TP",
    field: "EXT_BOX_TP",
    codeKey: "extBoxType",
    width: 100,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_ORIGIN_NM",
    field: "ORIGIN_NM",
    width: 100,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_LB_MEAT_CUT_NM",
    field: "LB_MEAT_CUT_NM",
    width: 100,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_LB_ITEM_NM",
    field: "LB_ITEM_NM",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_LB_TEMP_TP",
    field: "LB_TEMP_TP",
    width: 100,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ALT_ITEM_NM",
    field: "ALT_ITEM_NM",
    width: 100,
    align: "left",
  },
  {
    type: "numeric",
    headerName: "LBL_VOL_PER_BOX",
    field: "VOL_PER_BOX",
    width: 100,
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_BOX_QTY_PER_PLT",
    field: "BOX_QTY_PER_PLT",
    width: 100,
    align: "right",
  },
  {
    type: "text",
    headerName: "LBL_SEND_TIME",
    field: "TRANS_DATE",
    width: 130,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_ISSU_BY",
    field: "SYSID",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CLIENT",
    field: "CLIENT_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 150,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 150,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 150,
    align: "center",
    editable: false,
  },
];

export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_INTERFACE_TCD",
    field: "IF_TCD",
    codeKey: "interfaceType",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CUST_CD_FOR_CENTER",
    field: "ITEM_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_PLANT",
    field: "PLANT_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_COMPANY_GROUP",
    field: "CUST_GRP_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 120,
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 120,
    editable: false,
  },
];

export const SUB02_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_INTERFACE_TCD",
    field: "IF_TCD",
    codeKey: "interfaceType",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_CD",
    field: "ITEM_CD",
    width: 80,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_COMPANY_CD",
    field: "CUST_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_COMPANY_GROUP",
    field: "CUST_GRP_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_SALES_ORG",
    field: "SALES_ORG_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DISTBUTE_CHANNEL",
    field: "DIST_CHANNEL",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_SALES_STRG_CODE",
    field: "SALES_UNIT_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DELI_PLANT_CD",
    field: "DELI_PLANT_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD1",
    field: "ITEM_GCD1",
    width: 90,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD1_NM",
    field: "ITEM_GCD1_NM",
    width: 130,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD2",
    field: "ITEM_GCD2",
    width: 90,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD2_NM",
    field: "ITEM_GCD2_NM",
    width: 130,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD3",
    field: "ITEM_GCD3",
    width: 90,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD3_NM",
    field: "ITEM_GCD3_NM",
    width: 130,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD4",
    field: "ITEM_GCD4",
    width: 90,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD4_NM",
    field: "ITEM_GCD4_NM",
    width: 130,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD5",
    field: "ITEM_GCD5",
    width: 90,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD5_NM",
    field: "ITEM_GCD5_NM",
    width: 130,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 120,
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 120,
    editable: false,
  },
];

export const SUB03_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_INTERFACE_TCD",
    field: "IF_TCD",
    codeKey: "interfaceType",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_CD",
    field: "ITEM_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_STRG_CODE",
    field: "ITEM_STRG_CD",
    width: 80,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_NUMERATOR",
    field: "NUMERATOR",
    width: 200,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DENOMINATOR",
    field: "DENOMINATOR",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 120,
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 120,
    editable: false,
  },
];
