const DSPCH_OP_STS_STYLE: Record<string, { backgroundColor: string; color?: string }> = {
  "2000": { backgroundColor: "#4D4D4D", color: "#fff" },
  "2010": { backgroundColor: "#ffffff" },
  "2020": { backgroundColor: "#edeff4", color: "#000" },
  "2030": { backgroundColor: "#dbdfe8", color: "#000" },
  "2040": { backgroundColor: "#FFD85D", color: "#000" },
  "2050": { backgroundColor: "#b6bfd2", color: "#000" },
  "2060": { backgroundColor: "#FFD85D", color: "#000" },
  "2070": { backgroundColor: "#929fbb", color: "#fff" },
  "2073": { backgroundColor: "#8090b0", color: "#fff" },
  "2075": { backgroundColor: "#6d80a4", color: "#fff" },
  "2080": { backgroundColor: "#5b7099", color: "#fff" },
  "2090": { backgroundColor: "#49608d", color: "#fff" },
  "2100": { backgroundColor: "#375082", color: "#fff" },
  "2103": { backgroundColor: "#244077", color: "#fff" },
  "2105": { backgroundColor: "#12306b", color: "#fff" },
  "2110": { backgroundColor: "#002060", color: "#fff" },
  "2001": { backgroundColor: "#000000", color: "#fff" },
};

// 센차 setDispatchOperationStatusColor 대응 — 배차진행상태 셀 배경/글자색.
// 매핑이 비어있으면 기본 스타일(영향 없음).
const dispatchStatusCellStyle = (p: any) => {
  const cls = DISPATCH_STATUS_COLOR_MAP[p.value];
  if (!cls) return undefined;
  // TODO: 색상 클래스명만 정해지면 cellClass 로 전환. 현재는 매핑 미정으로 미적용.
  return undefined;
  const code = String(parseInt(p?.data?.DSPCH_OP_STS ?? p?.value ?? "", 10));
  const color = DSPCH_OP_STS_STYLE[code];
  return { textAlign: "center" as const, fontWeight: "bold" as const, ...(color ?? {}) };
};

// ── 메인 그리드 (센차 TenderDispatchMain) ──
// audit 컬럼(CRE_USR_ID/CRE_DTTM/UPD_USR_ID/UPD_DTTM)은 DataGrid audit 으로 자동 처리 → 생략.
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_DISPATCH_NO",
    field: "DSPCH_NO",
    align: "center",
  },
  { type: "text", headerName: "LBL_PLAN_ID", field: "PLN_ID", align: "center" },
  {
    type: "combo",
    headerName: "LBL_DISPATCH_OPERATIONAL_STATUS",
    field: "DSPCH_OP_STS",
    codeKey: "dspchOpSts",
    align: "center",
    cellStyle: dispatchStatusCellStyle,
  },
  { field: "CARR_CD", hide: true },
  {
    type: "text",
    headerName: "LBL_CARRIER_NAME",
    field: "CARR_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_CODE",
    field: "FRM_LOC_CD",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_NAME",
    field: "FRM_LOC_NM",
    align: "center",
  },
  { type: "numeric", headerName: "LBL_VOL", field: "PLN_NET_VOL" },
  { type: "numeric", headerName: "LBL_LOADING_RATE_CBM", field: "PLN_NET_VOL_RT" },
  { type: "numeric", headerName: "LBL_VOL", field: "PLN_GRS_VOL" },
  { type: "numeric", headerName: "LBL_LOADING_RATE_CBM", field: "PLN_GRS_VOL_RT" },
  { type: "numeric", headerName: "LBL_WGT", field: "PLN_NET_WGT" },
  { type: "numeric", headerName: "LBL_WGT_LOADING_RATE", field: "PLN_NET_WGT_RT" },
  { type: "numeric", headerName: "LBL_WGT", field: "PLN_GRS_WGT" },
  { type: "numeric", headerName: "LBL_WGT_LOADING_RATE", field: "PLN_GRS_WGT_RT" },
  { type: "numeric", headerName: "LBL_PLT_QTY", field: "PLN_PLT_QTY" },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY_RT", field: "PLN_PLT_RT" },
  { type: "numeric", headerName: "LBL_RT_QTY", field: "PLN_RTNR_QTY" },
  { type: "numeric", headerName: "LBL_RT_QTY_LOADING_RATE", field: "PLN_RTNR_RT" },
  { type: "numeric", headerName: "LBL_PBOX_QTY", field: "PLN_PBOX_QTY" },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY_RT", field: "PLN_PBOX_RT" },
  { type: "numeric", headerName: "LBL_BOX_QTY", field: "PLN_BOX_QTY" },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY_RT", field: "PLN_BOX_RT" },
  { type: "numeric", headerName: "LBL_FLEX_QTY1", field: "PLN_FLEX_QTY1" },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY1",
    field: "PLN_FLEX_QTY1_RT",
  },
  { type: "numeric", headerName: "LBL_FLEX_QTY2", field: "PLN_FLEX_QTY2" },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY2",
    field: "PLN_FLEX_QTY2_RT",
  },
  { type: "numeric", headerName: "LBL_FLEX_QTY3", field: "PLN_FLEX_QTY3" },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY3",
    field: "PLN_FLEX_QTY3_RT",
  },
  { type: "numeric", headerName: "LBL_FLEX_QTY4", field: "PLN_FLEX_QTY4" },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY4",
    field: "PLN_FLEX_QTY4_RT",
  },
  { type: "numeric", headerName: "LBL_FLEX_QTY5", field: "PLN_FLEX_QTY5" },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY5",
    field: "PLN_FLEX_QTY5_RT",
  },
  { type: "numeric", headerName: "LBL_STOP_CNT", field: "STOP_CNT" },
  { field: "DSPCH_TP", hide: true },
  {
    type: "date",
    headerName: "LBL_REQUESTED_DELIVERY_DATE",
    field: "DLVRY_DT",
    align: "center",
    width: 100,
  },
  { type: "text", headerName: "LBL_DIVISION", field: "DIV_CD", align: "center" },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    align: "center",
  },
  { field: "VEH_TP_CD", hide: true },
  {
    type: "text",
    headerName: "LBL_VEHICLE_TYPE_NAME",
    field: "VEH_TP_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_DRIVER_CODE",
    field: "DRVR_ID",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DRIVER_NAME",
    field: "DRVR_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_VEHICLE_CODE",
    field: "VEH_ID",
    align: "center",
  },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO", align: "center" },
  // hidden (운송요청/매입정산/연계배차/보조원)
  { field: "TNDR_REQ_ID", hide: true },
  { field: "TNDR_REQ_USR_ID", hide: true },
  { field: "TNDR_REQ_DTTM", hide: true },
  { field: "AP_FI_STS", hide: true },
  { field: "AP_PROC_TP", hide: true },
  { field: "TRIP_ID", hide: true },
  { field: "ASST_ID", hide: true },
  { field: "ASST_NM", hide: true },
];

// ── sub01: 경유지/착지 (센차 TenderDispatchSub01) — summaryType:sum → summable ──
export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_DISPATCH_NO",
    field: "DSPCH_NO",
    align: "center",
  },
  {
    type: "numeric",
    headerName: "LBL_STOP_SEQUENCE",
    field: "STOP_SEQ",
  },
  {
    type: "text",
    headerName: "LBL_LOCATION_CODE",
    field: "LOC_CD",
    align: "center",
  },
  { type: "text", headerName: "LBL_LOCATION_NAME", field: "LOC_NM", align: "left" },
  {
    type: "combo",
    headerName: "LBL_PICKDROP_DIV",
    field: "STOP_TP",
    codeKey: "stopTp",
    align: "center",
  },
  { type: "text", headerName: "LBL_STATE", field: "STT_NM", align: "left" },
  { type: "text", headerName: "LBL_CITY", field: "CTY_NM", align: "left", width: 150 },
  {
    type: "text",
    headerName: "LBL_DETAIL_ADDRESS",
    field: "DTL_ADDR1",
    align: "left",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_DETAIL_ADDRESS",
    field: "DTL_ADDR2",
    align: "left",
    width: 150,
  },
  { type: "numeric", headerName: "LBL_LATITUDE", field: "LAT" },
  { type: "numeric", headerName: "LBL_LONGITUDE", field: "LON" },
  { type: "numeric", headerName: "LBL_LOADING_VOL", field: "LDNG_VOL", summable: true },
  { type: "numeric", headerName: "LBL_LOADING_WGT", field: "LDNG_WGT", summable: true },
  {
    type: "numeric",
    headerName: "LBL_LOADING_FLEX_QTY1",
    field: "LDNG_FLEX_QTY1",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_FLEX_QTY2",
    field: "LDNG_FLEX_QTY2",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_FLEX_QTY3",
    field: "LDNG_FLEX_QTY3",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_FLEX_QTY4",
    field: "LDNG_FLEX_QTY4",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_FLEX_QTY5",
    field: "LDNG_FLEX_QTY5",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_UNLOADING_VOL",
    field: "UNLDNG_VOL",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_UNLOADING_WGT",
    field: "UNLDNG_WGT",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_UNLOADING_FLEX_QTY1",
    field: "UNLDNG_FLEX_QTY1",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_UNLOADING_FLEX_QTY2",
    field: "UNLDNG_FLEX_QTY2",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_UNLOADING_FLEX_QTY3",
    field: "UNLDNG_FLEX_QTY3",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_UNLOADING_FLEX_QTY4",
    field: "UNLDNG_FLEX_QTY4",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_UNLOADING_FLEX_QTY5",
    field: "UNLDNG_FLEX_QTY5",
    summable: true,
  },
];

// ── sub02: 배차된 운송지시 (센차 TenderDispatchSub02) ──
export const SUB02_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_ORDER_NO", field: "ORD_NO", align: "center", width: 150 },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_ORDER_NO",
    field: "CUST_ORD_NO",
    align: "center",
  },
  { field: "TO_LOC_ID", hide: true },
  {
    type: "text",
    headerName: "LBL_DESTINATION_CODE",
    field: "TO_LOC_CD",
    align: "center",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_NAME",
    field: "TO_LOC_NM",
    align: "left",
    width: 180,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_ZIP_CODE",
    field: "TO_ZIP_CD",
    align: "center",
  },
  { type: "numeric", headerName: "LBL_TO_LAT", field: "TO_LAT" },
  { type: "numeric", headerName: "LBL_TO_LON", field: "TO_LON" },
  {
    type: "combo",
    headerName: "LBL_ORDER_TYPE",
    field: "ORD_TP",
    codeKey: "ordTp",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_SHIPMENT_NUMBER",
    field: "SHPM_NO",
    align: "center",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_MIT_CODE_NAME",
    field: "MIT_CLSS_CD",
    align: "center",
  },
  { type: "text", headerName: "LBL_CUSTOMER_CODE", field: "CUST_CD", align: "center" },
  { type: "text", headerName: "LBL_CUSTOMER_NAME", field: "CUST_NM", align: "left" },
  { field: "FRM_LOC_ID", hide: true },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_CODE",
    field: "FRM_LOC_CD",
    align: "center",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_NAME",
    field: "FRM_LOC_NM",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_COUNTRY_NAME",
    field: "FRM_CTRY_NM",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_FROM_CITY_NM",
    field: "FRM_CTY_NM",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_FROM_STATE_NM",
    field: "FRM_STT_NM",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_ZIP_CODE",
    field: "FRM_ZIP_CD",
    align: "center",
  },
  { type: "numeric", headerName: "LBL_FROM_LAT", field: "FRM_LAT" },
  { type: "numeric", headerName: "LBL_FROM_LON", field: "FRM_LON" },
];

// ── sub03: 운송지시 상세/품목 (센차 TenderDispatchSub03) — summaryType:sum → summable ──
export const SUB03_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_ITEM_CODE", field: "CUST_ITEM_CD" },
  { type: "text", headerName: "LBL_ITEM_NAME", field: "CUST_ITEM_NM" },
  { type: "numeric", headerName: "LBL_VOL", field: "PLN_VOL", summable: true },
  { type: "numeric", headerName: "LBL_WGT", field: "PLN_WGT", summable: true },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY1",
    field: "PLN_FLEX_QTY1",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY2",
    field: "PLN_FLEX_QTY2",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY3",
    field: "PLN_FLEX_QTY3",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY4",
    field: "PLN_FLEX_QTY4",
    summable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY5",
    field: "PLN_FLEX_QTY5",
    summable: true,
  },
  { type: "numeric", headerName: "LBL_PLAN_QTY", field: "PLN_QTY", summable: true },
];
