export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    align: "center",
    width: 130,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_NAME",
    field: "LGST_GRP_NM",
    align: "center",
    width: 120,
  },
  {
    type: "date",
    headerName: "LBL_DLVRY_DATE",
    field: "DLVRY_DT",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_NO",
    field: "DSPCH_NO",
    align: "center",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_OPERATIONAL_STATUS",
    field: "DSPCH_OP_STS",
    codeKey: "dspchOpSts",
    statusStyle: "DSPCH_OP_STS",
    align: "center",
    width: 140,
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_CODE",
    field: "CARR_CD",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_NAME",
    field: "CARR_NM",
    align: "left",
    width: 140,
  },
  {
    type: "text",
    headerName: "LBL_VEHICLE_TYPE",
    field: "VEH_TP_NM",
    align: "center",
    width: 110,
  },
  {
    type: "text",
    headerName: "LBL_VEH_NO",
    field: "VEH_NO",
    align: "center",
    width: 110,
  },
  {
    type: "text",
    headerName: "LBL_DRIVER_NM",
    field: "DRVR_NM",
    align: "center",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_TRIP_COUNT",
    field: "RTN_NO",
    align: "center",
    width: 60,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_CODE",
    field: "FRM_LOC_CD",
    align: "center",
    width: 80,
    cellStyle: (params: any) =>
      params.value ? { backgroundColor: "#e8f5e9" } : undefined,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_NAME",
    field: "FRM_LOC_NM",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_CD",
    field: "TO_LOC_CD",
    align: "center",
    width: 80,
    cellStyle: (params: any) =>
      params.value ? { backgroundColor: "#e8f5e9" } : undefined,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_NM",
    field: "TO_LOC_NM",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_ORD_DO_NO",
    field: "ORD_NO",
    align: "center",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_ORD_TP",
    field: "ORD_TP",
    codeKey: "orderTp",
    align: "center",
    width: 140,
  },
  {
    type: "text",
    headerName: "LBL_CUST_ITEM_CD",
    field: "CUST_ITEM_CD",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_CUST_ITEM_NM",
    field: "CUST_ITEM_NM",
    align: "left",
    width: 150,
  },
  {
    type: "numeric",
    headerName: "LBL_ORD_QTY",
    field: "PLN_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_QTY",
    field: "CFM_QTY",
    align: "right",
    width: 100,
    cellStyle: (params: any) => (params.value ? { color: "#d32f2f" } : undefined),
  },
  {
    type: "text",
    headerName: "LBL_UOM",
    field: "PLN_QTY_UOM",
    align: "center",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_SHPM_WGT",
    field: "PLN_WGT",
    align: "right",
    width: 90,
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_WEIGHT",
    field: "CFM_WGT",
    align: "right",
    width: 90,
    cellStyle: (params: any) => (params.value ? { color: "#d32f2f" } : undefined),
  },
  {
    type: "datetime",
    headerName: "LBL_DSPCH_CNFRM_DTTM",
    field: "DSPCH_CNFRM_DTTM",
    align: "center",
    width: 150,
  },
  {
    type: "datetime",
    headerName: "LBL_DSPCH_INTRNST_DTTM",
    field: "DSPCH_INTRNST_DTTM",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_DSPCH_INTRNST_USR",
    field: "DSPCH_INTRNST_USR_NM",
    align: "center",
    width: 120,
  },
];
