export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_DIVISION_CODE",
    field: "DIV_CD",
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_DIVISION_NAME",
    field: "DIV_NM",
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_NAME",
    field: "LGST_GRP_NM",
  },
  {
    type: "text",
    headerName: "LBL_QTY_ITNR_CD",
    field: "QTY_ITNR_ID",
    isPrimaryKey: true,
    insertable: true,
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_QTY_ITNR_NM",
    field: "QTY_ITNR_NM",
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "check",
    headerName: "LBL_USE_YN",
    field: "USE_YN",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_VEHICLE_CODE",
    field: "VEH_ID",
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_VEH_NO",
    field: "VEH_NO",
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_CODE",
    field: "CARR_CD",
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_NAME",
    field: "CARR_NM",
  },
  {
    type: "text",
    headerName: "LBL_FROM_ZONE_CD",
    field: "FRM_ZN_CD",
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_FROM_ZONE_NM",
    field: "FRM_ZN_NM",
  },
  {
    type: "text",
    headerName: "LBL_TO_ZONE_CD",
    field: "TO_ZN_CD",
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_TO_ZONE_NM",
    field: "TO_ZN_NM",
  },
];
