export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "datetime",
    headerName: "LBL_RECEIVE_DATE",
    field: "CRE_DTTM",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    width: 110,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_USR_RE_PRCS_YN",
    field: "RE_PRCS_BY_USR_YN",
    width: 120,
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_IF_PRCS_STS",
    field: "IF_PRCS_STS",
    codeKey: "interfaceStatus",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_PRCS_MSG_DESC",
    field: "IF_PRCS_MSG_DESC",
    width: 200,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_TMS_IF_PRCS_ID",
    field: "TMS_IF_PRCS_ID",
    width: 150,
    align: "center",
  },
  {
    type: "datetime",
    headerName: "LBL_TMS_IF_PRCS_START_DTTM",
    field: "TMS_IF_PRCS_START_DTTM",
    width: 160,
    align: "center",
  },
  {
    type: "datetime",
    headerName: "LBL_TMS_IF_PRCS_END_DTTM",
    field: "TMS_IF_PRCS_END_DTTM",
    width: 160,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DTG_NO",
    field: "DTG_NO",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DTG_HLTH_SCD",
    field: "DTG_HLTH_SCD",
    width: 150,
    align: "center",
  },
  {
    type: "datetime",
    headerName: "LBL_PSTN_DTTM",
    field: "PSTN_DTTM",
    width: 150,
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_VEH_MV_STS",
    field: "VEH_MV_STS",
    codeKey: "vehicleMoveStatus",
    width: 150,
    align: "center",
  },
  {
    type: "numeric",
    headerName: "LBL_LATITUDE",
    field: "LAT",
    width: 100,
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_LONGITUDE",
    field: "LON",
    width: 100,
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_CHN_B_TMPR",
    field: "CHN_B_TMPR_NUM_VAL",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_CHN_A_TMPR",
    field: "CHN_A_TMPR_NUM_VAL",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_DLY_TRVL_DIST",
    field: "DLY_TRVL_DIST",
    width: 150,
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_CMLTV_TRVL_DIST",
    field: "CMLTV_TRVL_DIST",
    width: 150,
    align: "right",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 150,
    align: "center",
  },
  {
    type: "datetime",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 150,
    align: "center",
  },
  {
    type: "datetime",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 150,
    align: "center",
  },
];
