export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_RECEIVE_DATE",
    field: "CRE_DTTM",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    width: 110,
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_IF_PRCS_STS",
    field: "IF_PRCS_STS",
    codeKey: "interfaceStatus",
    statusStyle: "IF_PRCS_STS",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_PRCS_MSG_DESC",
    field: "IF_PRCS_MSG_DESC",
    width: 200,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_TMS_IF_PRCS_ID",
    field: "TMS_IF_PRCS_ID",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_TMS_IF_PRCS_START_DTTM",
    field: "TMS_IF_PRCS_START_DTTM",
    width: 160,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_TMS_IF_PRCS_END_DTTM",
    field: "TMS_IF_PRCS_END_DTTM",
    width: 160,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_VEHICLE_CODE",
    field: "VEH_ID",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_VEHICLE_NUMBER",
    field: "VEH_NO",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_NO",
    field: "DSPCH_NO",
    width: 100,
    align: "center",
  },
  {
    type: "numeric",
    headerName: "LBL_LATITUDE",
    field: "LAT",
    width: 100,
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_LONGITUDE",
    field: "LON",
    width: 100,
    align: "right",
  },
  {
    type: "text",
    headerName: "LBL_PSTN_DTTM",
    field: "PSTN_DTTM",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 150,
    align: "center",
  },
  {
    type: "datetime",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 150,
    align: "center",
  },
];
