export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "popup",
    headerName: "LBL_MENU_CD",
    field: "MENU_CD",
    nameField: "MENU_NM",
    sqlId: "selectMenuCodeName",
    popupTitle: "LBL_MENU_CD",
    width: 150,
    align: "center",
    insertable: true,
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_MENU_NM",
    field: "MENU_NM",
    width: 120,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    headerName: "LBL_DB_CLUM_NM",
    field: "DB_CLMN_NM",
    width: 180,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_DSPL_ORD",
    field: "DSPLY_SEQ",
    width: 70,
    align: "right",
    insertable: true,
    editable: true,
  },
  {
    type: "popup",
    headerName: "LBL_MSG_CD",
    field: "MSG_CD",
    sqlId: "selectMsgCodeName",
    popupTitle: "LBL_MSG_CD",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_USE_YN",
    field: "USE_YN",
    width: 60,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_DSPL_TP",
    field: "DSPLY_TP",
    codeKey: "displayTypeList",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_DATA_TYPE",
    field: "DATA_TP",
    codeKey: "dataTypeList",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_RNG_SRCH_YN",
    field: "RNG_SRCH_YN",
    width: 80,
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_MDTR_YN",
    field: "MDTR_YN",
    width: 70,
    insertable: true,
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_SRCH_OPRT",
    field: "SRCH_OPRT",
    codeKey: "operatorTypeList",
    width: 80,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_SRCH_OPRT_FX_YN",
    field: "SRCH_OPRT_FIX_YN",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_DEFAULT",
    field: "DFT_VAL",
    width: 100,
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_DT_MX_BND_NM",
    field: "DT_SRCH_MAX_DAY",
    width: 100,
    align: "right",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_SQL_ID",
    field: "SQL_ID",
    width: 120,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_SQL_PRM_NM",
    field: "SQL_KEY_PARAM",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_SQL_PRM1_NM",
    field: "SQL_PARAM1",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_SQL_PRM2_NM",
    field: "SQL_PARAM2",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_SQL_PRM3_NM",
    field: "SQL_PARAM3",
    width: 100,
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_CNT_PR_PG_NM",
    field: "DATA_CNT_PER_PAGE",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_MN_INPUT_NM",
    field: "MIN_INP_LEN",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_OPRT_USE_YN_NM",
    field: "OPR_USE_YN",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_INCLUD_OPRT_NM",
    field: "OPR_IN",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBLEXCLUD_OPRT_NM",
    field: "OPR_NOT_IN",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_OPRT_MTCH_NM",
    field: "OPR_EQL",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_OPRT_PRT_MTCH_NM",
    field: "OPR_LIKE",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_DT_TP_NM",
    field: "DT_TP",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_DT_STD_TP_NM",
    field: "DT_CRTE_TP",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_DT_SLCT_TP_NM",
    field: "DATA_SLCT_TP",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_CHLD_RLTN_NM",
    field: "CHD_RLT_ID",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_SRCH_COND_TTL_WDT",
    field: "SRCH_COND_TTL_WDT",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_SRCH_COND_FLD_WDT",
    field: "SRCH_COND_FLD_WDT",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_SRCH_COND_FLD_DFT_VAL",
    field: "SRCH_COND_FLD_DFT_VAL",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_SRCH_COND_ALL_YN",
    field: "SRCH_COND_ALL_YN",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_POPUP_DAT_SLCT_TP",
    field: "POPUP_DAT_SLCT_TP",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_FLTR_CMPO_NM",
    field: "FLTR_CMPO_NM",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_FLTR_REF_COL_NM",
    field: "FLTR_REF_COL_NM",
    width: 110,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_DFT_DB_CLMN_CD",
    field: "DFT_DB_CLMN_CD",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_CMB_DLSP_TP",
    field: "CMB_DLSP_TP",
    width: 100,
    align: "center",
    insertable: true,
    editable: true,
  },
];
