// 그리드 컬럼 정의 (서버 CostDistributionMain / CostDistributionSub01 기준)
// 조회 전용 화면 — 편집 없음(editable 미지정). audit 컬럼은 사용 안 함(View audit={false}).
// 숫자 컬럼 summaryType:'sum' → summable:true (하단 합계행 자동).

// ── 주문단위 (MAIN, LBL_ORDER_UOM) ───────────────────────────────
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_MANAGE_ID", field: "CST_DIST_ID", align: "center" },
  { type: "text", headerName: "LBL_DIVISION_CODE", field: "DIV_CD", align: "center" },
  { type: "text", headerName: "LBL_DIVISION_NAME", field: "DIV_NM" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD", align: "center" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_NAME", field: "LGST_GRP_NM" },
  { type: "combo", headerName: "LBL_SETL_TP", field: "CST_DIST_DATA_TCD", codeKey: "cstDistDataTcd", align: "center" },
  { type: "text", headerName: "LBL_BASE_DOC_ID", field: "BASE_DOC_ID", align: "center" },
  { type: "text", headerName: "LBL_BASE_DOC_TP", field: "BASE_DOC_TP", align: "center" },
  { type: "combo", headerName: "LBL_TARIFF_TYPE", field: "AP_TP", codeKey: "cstDistApTp", align: "center" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO", align: "center" },
  { type: "text", headerName: "LBL_VEHICLE_CODE", field: "VEH_ID", align: "center" },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO" },
  { type: "text", headerName: "LBL_PAY_CARRIER_CODE", field: "PAY_CARR_CD", align: "center" },
  { type: "text", headerName: "LBL_PAY_CARRIER_NAME", field: "PAY_CARR_NM" },
  { type: "date", headerName: "LBL_DLVRY_DATE", field: "DLVRY_DT", align: "center", width: 80 },
  { type: "text", headerName: "LBL_SHIPMENT_NO", field: "SHPM_NO", align: "center" },
  { type: "text", headerName: "LBL_ORDER_NO", field: "ORD_NO", align: "center" },
  { type: "combo", headerName: "LBL_SHIPMENT_TYPE", field: "SHPM_TP", codeKey: "shpmTpList", align: "center" },
  { type: "text", headerName: "LBL_AP_CD", field: "CHG_CD", align: "center" },
  { type: "text", headerName: "LBL_AP_NM", field: "CHG_NM" },
  { type: "numeric", headerName: "LBL_SHPM_DIST", field: "SHPM_DIST" },
  { type: "numeric", headerName: "LBL_ORI_CHG_COST", field: "ORI_CHG_COST", summable: true },
  { type: "numeric", headerName: "LBL_TTL_SHPM_DIST", field: "TTL_SHPM_DIST" },
  { type: "numeric", headerName: "LBL_SHPM_DIST_RATIO", field: "SHPM_DIST_RATIO" },
  { type: "numeric", headerName: "LBL_SHPM_WGT", field: "SHPM_WGT" },
  { type: "numeric", headerName: "LBL_TTL_SHPM_WGT", field: "TTL_SHPM_WGT" },
  { type: "numeric", headerName: "LBL_SHPM_WGT_RATIO", field: "SHPM_WGT_RATIO" },
  { type: "numeric", headerName: "LBL_WGT_COE", field: "WGT_COE" },
  { type: "numeric", headerName: "LBL_WGT_COE_RATIO", field: "WGT_COE_RATIO" },
  { type: "numeric", headerName: "LBL_ADJ_CST_DIST_COST", field: "ADJ_CST_DIST_COST", summable: true },
  { type: "numeric", headerName: "LBL_DIST_DED_DIST_COST", field: "DIST_DED_DIST_COST", summable: true },
  { type: "numeric", headerName: "LBL_FINAL_CST_DIST_COST", field: "FINAL_CST_DIST_COST", summable: true },
  { type: "text", headerName: "LBL_GNRL_LDGR_CD", field: "GNRL_LDGR_CD", colId: "GNRL_LDGR_CD_TXT", align: "center" },
  { type: "combo", headerName: "LBL_GNRL_LDGR_NM", field: "GNRL_LDGR_CD", colId: "GNRL_LDGR_CD_NM", codeKey: "gnrlLdgrCd", align: "left" },
  { type: "text", headerName: "LBL_CST_CNTR_CD", field: "CST_CNTR_CD", colId: "CST_CNTR_CD_TXT", align: "center", width: 150 },
  { type: "combo", headerName: "LBL_CST_CNTR_NM", field: "CST_CNTR_CD", colId: "CST_CNTR_CD_NM", codeKey: "cstCntrCdList", align: "left", width: 150 },
  { type: "text", headerName: "LBL_TARGET_SYS", field: "TARGET_SYS", align: "center" },
  { type: "text", headerName: "LBL_CST_DIST_YN", field: "CST_DIST_YN", align: "center" },
  { type: "text", headerName: "LBL_SETL_CST_DIST_YN", field: "SETL_CST_DIST_YN", align: "center" },
  { type: "combo", headerName: "LBL_CST_DIST_STS", field: "CST_DIST_STS", codeKey: "cstDistSts", align: "center" },
  // TODO: 서버 bindStore 'cstDistTcd' 미정의(코드맵 없음) → 텍스트로 노출.
  { type: "text", headerName: "LBL_CST_DIST_TCD", field: "CST_DIST_TCD", align: "center" },
  { type: "text", headerName: "LBL_FI_ID", field: "AP_ID", align: "center" },
  { type: "text", headerName: "LBL_FI_SETL_ID", field: "AP_SETL_ID", align: "center" },
  { type: "text", headerName: "LBL_FI_SETL_GRP_ID", field: "AP_SETL_GRP_ID", align: "center" },
  { type: "text", headerName: "LBL_INSERT_PERSON_ID", field: "CRE_USR_ID", align: "center" },
  { type: "datetime", headerName: "LBL_INSERT_DATE", field: "CRE_DTTM", align: "center" },
  { type: "text", headerName: "LBL_UPDATE_PERSON_ID", field: "UPD_USR_ID", align: "center" },
  { type: "datetime", headerName: "LBL_UPDATE_TIME", field: "UPD_DTTM", align: "center" },
];

// ── 품목단위 (SUB01, LBL_ITEM_UOM) ───────────────────────────────
export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_MANAGE_ID", field: "CST_DIST_ID", align: "center" },
  { type: "text", headerName: "LBL_DIVISION_CODE", field: "DIV_CD", align: "center" },
  { type: "text", headerName: "LBL_DIVISION_NAME", field: "DIV_NM" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD", align: "center" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_NAME", field: "LGST_GRP_NM" },
  { type: "combo", headerName: "LBL_SETL_TP", field: "CST_DIST_DATA_TCD", codeKey: "cstDistDataTcd", align: "center" },
  { type: "text", headerName: "LBL_BASE_DOC_ID", field: "BASE_DOC_ID", align: "center" },
  { type: "text", headerName: "LBL_BASE_DOC_TP", field: "BASE_DOC_TP", align: "center" },
  { type: "combo", headerName: "LBL_TARIFF_TYPE", field: "AP_TP", codeKey: "cstDistApTp", align: "center" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO", align: "center" },
  { type: "text", headerName: "LBL_VEHICLE_CODE", field: "VEH_ID", align: "center" },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO" },
  { type: "text", headerName: "LBL_PAY_CARRIER_CODE", field: "PAY_CARR_CD", align: "center" },
  { type: "text", headerName: "LBL_PAY_CARRIER_NAME", field: "PAY_CARR_NM" },
  { type: "date", headerName: "LBL_DLVRY_DATE", field: "DLVRY_DT", align: "center", width: 80 },
  { type: "text", headerName: "LBL_SHIPMENT_NO", field: "SHPM_NO", align: "center" },
  { type: "text", headerName: "LBL_ORDER_NO", field: "ORD_NO", align: "center" },
  { type: "combo", headerName: "LBL_SHIPMENT_TYPE", field: "SHPM_TP", codeKey: "shpmTpList", align: "center" },
  { type: "text", headerName: "LBL_SHPM_DTL_ID", field: "SHPM_DTL_ID", align: "center" },
  { type: "text", headerName: "LBL_AP_CD", field: "CHG_CD", align: "center" },
  { type: "text", headerName: "LBL_AP_NM", field: "CHG_NM" },
  { type: "numeric", headerName: "LBL_HDR_DIST_COST", field: "HDR_DIST_COST", summable: true },
  { type: "numeric", headerName: "LBL_DTL_DIST_COST", field: "DTL_DIST_COST", summable: true },
  { type: "text", headerName: "LBL_GNRL_LDGR_CD", field: "GNRL_LDGR_CD", colId: "GNRL_LDGR_CD_TXT", align: "center" },
  { type: "combo", headerName: "LBL_GNRL_LDGR_NM", field: "GNRL_LDGR_CD", colId: "GNRL_LDGR_CD_NM", codeKey: "gnrlLdgrCd", align: "left" },
  { type: "text", headerName: "LBL_CST_CNTR_CD", field: "CST_CNTR_CD", colId: "CST_CNTR_CD_TXT", align: "center", width: 150 },
  { type: "combo", headerName: "LBL_CST_CNTR_NM", field: "CST_CNTR_CD", colId: "CST_CNTR_CD_NM", codeKey: "cstCntrCdList", align: "left", width: 150 },
  { type: "text", headerName: "LBL_POSTING_DT", field: "POSTING_DT" },
  // TODO: 서버 editType:'date' 이나 전표번호 → 포맷 왜곡 방지 위해 text 로 노출.
  { type: "text", headerName: "LBL_DOC_NO", field: "DOC_NO" },
  { type: "numeric", headerName: "LBL_SHPM_DTL_WGT", field: "SHPM_DTL_WGT" },
  { type: "text", headerName: "LBL_COMPANY_CD", field: "CUST_CD", align: "center" },
  { type: "text", headerName: "LBL_SALES_NO", field: "SALES_NO", align: "center" },
  { type: "text", headerName: "LBL_SALES_LINE", field: "SALES_LINE_NO", align: "center" },
  { type: "text", headerName: "LBL_SALES_OFC", field: "SALES_OFC", align: "center" },
  { type: "text", headerName: "LBL_SALES_GRP_CD", field: "SALES_GRP", align: "center" },
  { type: "text", headerName: "LBL_BIZUNIT_GCD", field: "SALES_ORG_CD", align: "center" },
  { type: "text", headerName: "LBL_DISTBUTE_CHANNEL", field: "DIST_CHANNEL", align: "center" },
  { type: "text", headerName: "LBL_SOLD_TO", field: "SOLD_TO_CD", align: "center" },
  { type: "text", headerName: "LBL_ITEM_CD", field: "ITEM_CD", align: "center" },
  { type: "text", headerName: "LBL_PLANT", field: "PLANT_CD", align: "center" },
  { type: "text", headerName: "LBL_SHIP_TO", field: "SHIP_TO_CD", align: "center" },
  { type: "text", headerName: "LBL_PAS_NO", field: "PAS_NO", align: "center" },
  { type: "text", headerName: "LBL_STG_LOC", field: "SLOC_CD", align: "center" },
  { type: "combo", headerName: "LBL_CST_DIST_STS", field: "CST_DIST_STS", codeKey: "cstDistSts", align: "center" },
  { type: "text", headerName: "LBL_FI_SETL_ID", field: "AP_SETL_ID", align: "center" },
  { type: "text", headerName: "LBL_FI_SETL_GRP_ID", field: "AP_SETL_GRP_ID", align: "center" },
  { type: "text", headerName: "LBL_INSERT_PERSON_ID", field: "CRE_USR_ID", align: "center" },
  { type: "datetime", headerName: "LBL_INSERT_DATE", field: "CRE_DTTM", align: "center" },
  { type: "text", headerName: "LBL_UPDATE_PERSON_ID", field: "UPD_USR_ID", align: "center" },
  { type: "datetime", headerName: "LBL_UPDATE_TIME", field: "UPD_DTTM", align: "center" },
];
