// 운송상세 그리드 컬럼 (서버 TransportationDetailMain 기준 — 읽기전용 inquiry)
// editType 은 서버 정의를 따르되, KPI 조회 화면이라 편집은 켜지 않는다(insertable/editable 미지정).
// summaryType:'sum' → summable:true (하단 합계행), numberComma/number → numeric.

export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD", align: "center" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO", align: "center" },
  { type: "text", headerName: "LBL_CARRIER_CODE", field: "CARR_CD", align: "center", width: 120 },
  { type: "text", headerName: "LBL_CARRIER_NAME", field: "CARR_NM", align: "left", width: 120 },
  { type: "text", headerName: "LBL_PAY_CARRIER_CODE", field: "PAY_CARR_CD", align: "center", width: 150 },
  { type: "text", headerName: "LBL_PAY_CARRIER_NAME", field: "PAY_CARR_NM", align: "left", width: 200 },
  { type: "date", headerName: "LBL_DLVRY_DATE", field: "DLVRY_DT", align: "center", width: 80 },
  { type: "text", headerName: "LBL_VEHICLE_NUMBER", field: "VEH_NO", align: "center" },
  { type: "text", headerName: "LBL_VEHICLE_TYPE", field: "VEH_TP_NM", align: "center" },
  { type: "text", headerName: "LBL_DRIVER_CODE", field: "DRVR_ID", align: "center", width: 80 },
  { type: "text", headerName: "LBL_DRIVER_NAME", field: "DRVR_NM", align: "left", width: 80 },
  { type: "text", headerName: "LBL_ROTATION", field: "RTN_NO", align: "right", width: 40 },
  { type: "combo", headerName: "LBL_AP_CLASSIFICATION", field: "AP_PROC_TP", codeKey: "apProcTp", align: "center", width: 80 },
  { type: "numeric", headerName: "LBL_TRANS_COST", field: "CFM_COST", align: "right", width: 80, summable: true },
  { type: "numeric", headerName: "LBL_PBOX_QTY", field: "UNLDNG_FLEX_QTY1", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_FLEX_QTY2", field: "UNLDNG_FLEX_QTY2", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_PLT_QTY", field: "UNLDNG_FLEX_QTY3", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_TTL_WGT", field: "UNLDNG_FLEX_QTY4", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY1", field: "PLN_FLEX_QTY1", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY2", field: "PLN_FLEX_QTY2", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY3", field: "PLN_FLEX_QTY3", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY4", field: "PLN_FLEX_QTY4", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY1", field: "CFM_FLEX_QTY1", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY2", field: "CFM_FLEX_QTY2", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY3", field: "CFM_FLEX_QTY3", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY4", field: "CFM_FLEX_QTY4", align: "right", width: 120, summable: true },
  { type: "numeric", headerName: "LBL_RTR_PBOX", field: "RTRN_QTY", align: "right", summable: true },
  { type: "numeric", headerName: "LBL_RTR_PLT", field: "PLT_RTRN_QTY", align: "right", summable: true },
  { type: "numeric", headerName: "LBL_TTL_DIST", field: "TTL_DIST", align: "right", width: 90 },
  { type: "numeric", headerName: "LBL_DIRECT_DIST", field: "DIRECT_DIST", align: "right", width: 150 },
  { type: "numeric", headerName: "LBL_TRNST_PREVSTOP_DIST", field: "TRNST_PREVSTOP_DIST", align: "right", width: 150 },
  { type: "text", headerName: "LBL_DESTINATION_CD", field: "TO_LOC_CD", align: "center", width: 80 },
  { type: "text", headerName: "LBL_DESTINATION_NM", field: "TO_LOC_NM", align: "left", width: 80 },
  { type: "text", headerName: "LBL_ITEM_CD", field: "CUST_ITEM_CD", align: "left", width: 80 },
  { type: "text", headerName: "LBL_ITEM_NM", field: "CUST_ITEM_NM", align: "left", width: 80 },
  { type: "datetime", headerName: "LBL_ARRIVAL_TIME", field: "ATD_DTTM", align: "center", width: 80 },
  { type: "datetime", headerName: "LBL_DEPARTURE_TIME", field: "ATA_DTTM", align: "center", width: 80 },
  { type: "text", headerName: "LBL_DESTINATION_ZIP_CODE", field: "TO_ZIP_CD", align: "center", width: 60 },
  { type: "text", headerName: "LBL_DETAIL_ADDRESS", field: "TO_DTL_ADDR1", align: "left", width: 160 },
];
