export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_OVERHEAD_CODE",
    field: "CHG_CD",
    isPrimaryKey: true,
    align: "center",
    insertable: true,
    validators: {
      required: true,
      regexTp: "GCODE",
      max: 60,
    },
  },
  {
    type: "text",
    headerName: "LBL_OVERHEAD_NAME",
    field: "CHG_NM",
    align: "center",
    insertable: true,
    editable: true,
    validators: {
      required: true,
      max: 200,
    },
  },
  {
    type: "combo",
    headerName: "LBL_GNRL_LDGR_CD",
    field: "GNRL_LDGR_CD",
    codeKey: "gnrlLdgrCd",
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_CST_CNTR_CD",
    field: "CST_CNTR_CD",
    codeKey: "cstCntrCdList",
    align: "left",
    width: 150,
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_USE_Y/N",
    field: "USE_YN",
    align: "center",
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_UPDATE_YN",
    field: "ALW_RATE_UPD_YN",
    align: "center",
    width: 100,
    insertable: true,
    editable: true,
  },
];
