import { makeAuditColumns } from "@/app/components/grid/columns/commonColumns";

// 키 컬럼에 isPrimaryKey:true — DataGrid 가 첫행 자동선택을 자동 활성화.
// FRM_LOC_ID / TO_LOC_ID 는 화면 표시 X — hidden 으로 메타만 유지.
// 출발/도착 코드는 popup(selectLocationCodeName) — 선택 시 LOC_ID 도 callback 으로 세팅.
export const MAIN_COLUMN_DEFS = [
  { field: "FRM_LOC_ID", hide: true, isPrimaryKey: true },
  { field: "TO_LOC_ID", hide: true, isPrimaryKey: true },
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_DIVISION_CODE",
    field: "DIV_CD",
    isPrimaryKey: true,
    align: "center",
    width: 90,
  },
  {
    type: "text",
    headerName: "LBL_DIVISION_NAME",
    field: "DIV_NM",
    width: 100,
  },
  {
    type: "popup",
    headerName: "LBL_DEPARTURE_CODE",
    field: "FRM_LOC_CD",
    sqlId: "selectLocationCodeName",
    nameField: "FRM_LOC_NM",
    insertable: true,
    required: true,
    align: "center",
    width: 150,
    validators: { max: 60 },
    callback: ({ picked, commit }: any) =>
      commit({ FRM_LOC_ID: picked.LOC_ID }),
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_NAME",
    field: "FRM_LOC_NM",
    width: 150,
  },
  {
    type: "popup",
    headerName: "LBL_DESTINATION_CODE",
    field: "TO_LOC_CD",
    sqlId: "selectLocationCodeName",
    nameField: "TO_LOC_NM",
    insertable: true,
    required: true,
    align: "center",
    width: 150,
    validators: { max: 60 },
    callback: ({ picked, commit }: any) => commit({ TO_LOC_ID: picked.LOC_ID }),
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_NAME",
    field: "TO_LOC_NM",
    width: 150,
  },
  {
    type: "numeric",
    headerName: "LBL_TZ_DIST",
    field: "DIST",
    insertable: true,
    editable: true,
    width: 150,
    validators: { integerLength: 10, pointLength: 3, min: 0 },
  },
  {
    type: "numeric",
    headerName: "LBL_TZ_DIST_TMAP",
    field: "TMAP_DIST",
    decimalPlaces: 3,
    width: 150,
    validators: { integerLength: 10, pointLength: 3, min: 0 },
  },
  {
    type: "numeric",
    headerName: "LBL_TRANSIT_TIME",
    field: "TRANSITTIME",
    insertable: true,
    editable: true,
    width: 150,
    validators: { integerLength: 20, min: 0 },
  },
  {
    type: "numeric",
    headerName: "LBL_EXP_TOLL_RATE",
    field: "RATE",
    decimalPlaces: 0,
    width: 150,
    validators: { integerLength: 20, min: 0 },
  },
  {
    type: "combo",
    headerName: "LBL_ROUTE_SEARCH_OPTION",
    field: "MAP_RTNG_OPTN_TCD",
    codeKey: "mapRtngOptnTcd",
    insertable: true,
    editable: true,
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_CHG_REASON",
    field: "CHG_RSN",
    editable: true,
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_REMARK",
    field: "RMK",
    editable: true,
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_PRCS_STS",
    field: "DTTO_PRCS_STS",
    codeKey: "dttoPrcsStatus",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_DTTO_BASE_TIME",
    field: "BASE_TIME",
    align: "center",
    width: 100,
  },
];

// 추가 DTTO 그리드 (DistanceTransitTimeSub01)
export const HISTORY_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "numeric",
    headerName: "LBL_TZ_DIST",
    field: "DIST",
    insertable: true,
    editable: true,
    decimalPlaces: 3,
    width: 150,
    validators: { integerLength: 10, pointLength: 3, min: 0 },
  },
  {
    type: "numeric",
    headerName: "LBL_TZ_DIST_TMAP",
    field: "TMAP_DIST",
    decimalPlaces: 3,
    width: 150,
    validators: { integerLength: 10, pointLength: 3, min: 0 },
  },
  {
    type: "numeric",
    headerName: "LBL_TRANSIT_TIME",
    field: "TRANSITTIME",
    insertable: true,
    editable: true,
    width: 150,
    validators: { integerLength: 20, min: 0 },
  },
  {
    type: "numeric",
    headerName: "LBL_EXP_TOLL_RATE",
    field: "RATE",
    decimalPlaces: 0,
    width: 150,
    validators: { integerLength: 20, min: 0 },
  },
  {
    type: "text",
    headerName: "LBL_CHG_REASON",
    field: "CHG_RSN",
    editable: true,
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_DTTO_BASE_TIME",
    field: "BASE_TIME",
    align: "center",
    width: 100,
  },
];
