import { numberValueFormatter } from "@/app/components/grid/columns/commonFormatters";

export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "popup",
    headerName: "LBL_DIVISION_CODE",
    field: "DIV_CD",
    nameField: "DIV_NM",
    sqlId: "selectDivisionCodeName",
    popupTitle: "LBL_DIVISION_CODE",
    required: true,
    insertable: true,
    callback: ({ commit }) => {
      commit({ LGST_GRP_CD: "", LGST_GRP_NM: "", TRF_CD: "", TRF_NM: "" });
    },
  },
  {
    type: "text",
    headerName: "LBL_DIVISION_NAME",
    field: "DIV_NM",
  },
  {
    type: "popup",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    nameField: "LGST_GRP_NM",
    sqlId: "selectLogisticsgroupCodeName",
    popupTitle: "LBL_LOGISTICS_GROUP_CODE",
    required: true,
    insertable: true,
    extraParams: (row) => ({ keyParam: row?.DIV_CD ?? "" }),
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_NAME",
    field: "LGST_GRP_NM",
  },
  {
    type: "popup",
    headerName: "LBL_TARIFF_CODE",
    field: "TRF_CD",
    nameField: "TRF_NM",
    sqlId: "selectTariffCodeName",
    popupTitle: "LBL_TARIFF_CODE",
    required: true,
    insertable: true,
    extraParams: (row) => ({
      param1: row?.DIV_CD ?? "",
      param2: row?.LGST_GRP_CD ?? "",
    }),
  },
  {
    type: "text",
    headerName: "LBL_TARIFF_NAME",
    field: "TRF_NM",
  },
  {
    type: "number",
    headerName: "LBL_CHG_CAL_RNK",
    field: "CALC_RNK",
    valueFormatter: numberValueFormatter,
  },
  {
    type: "popup",
    headerName: "LBL_RATE_ITEM_CD",
    field: "CHG_CD",
    nameField: "CHG_NM",
    sqlId: "selectTariffChgCodeName",
    popupTitle: "LBL_RATE_ITEM_CD",
    required: true,
    insertable: true,
  },
  {
    type: "text",
    headerName: "LBL_RATE_ITEM_NAME",
    field: "CHG_NM",
  },
  {
    type: "check",
    headerName: "LBL_SUPERSEDE_YN",
    field: "SUPERSEDE_YN",
    editable: true,
    insertable: true,
    defaultValue: "N",
  },
  {
    type: "combo",
    headerName: "LBL_SUPERSEDE_TP",
    field: "SUPERSEDE_TP",
    codeKey: "supersedeTpList",
    align: "left",
    editable: true,
    insertable: true,
  },
  {
    type: "combo",
    headerName: "LBL_RDNG_RCD",
    field: "RDNG_RCD",
    codeKey: "rdngRcdList",
    align: "center",
    required: true,
    editable: true,
    insertable: true,
  },
  {
    type: "check",
    headerName: "LBL_USE_YN",
    field: "USE_YN",
    editable: true,
    insertable: true,
    defaultValue: "Y",
  },
];

export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_TARIFF_CODE",
    field: "TRF_CD",
    hide: true
  },
  {
    type: "text",
    headerName: "LBL_RATE_ITEM_CD",
    field: "CHG_CD",
    hide: true
  },
  {
    type: "number",
    headerName: "LBL_CAL_RNK",
    field: "CALC_RNK",
    required: true,
    editable: true,
    insertable: true,
    valueFormatter: numberValueFormatter,
  },
  {
    type: "combo",
    headerName: "LBL_CAL_OPT_FROM",
    field: "FNT_OPR",
    codeKey: "calcOptTypeList",
    align: "center",
    editable: true,
    insertable: true,
    validators: { max: 20 },
  },
  {
    type: "text",
    headerName: "LBL_SERVICE_CD",
    field: "SUBCHG_CD",
  },
  {
    type: "text",
    headerName: "LBL_SERVICE_NM",
    field: "SUBCHG_NM",
  },
  {
    type: "combo",
    headerName: "LBL_CAL_OPT_TO",
    field: "END_OPR",
    codeKey: "calcOptTypeList",
    align: "center",
    editable: true,
    insertable: true,
    validators: { max: 20 },
  },
];
