export const MAIN_COLUMN_DEFS = [
  {
    type: "text",
    headerName: "LBL_PRNT_RSRC_ID",
    field: "PRNT_RSRC_ID",
    width: 200,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    headerName: "LBL_RSRC_DESC",
    field: "RSRC_DESC",
    width: 200,
    editable: true,
    insertable: true,
  },
  {
    type: "text",
    headerName: "LBL_MENU_NM",
    field: "MSG_DESC",
    width: 150,
    editable: false,
    insertable: false,
  },
  {
    // codeKey → 자동 combo(라벨 표시 + 편집 시 dropdown). resourceType 코드맵.
    type: "combo",
    headerName: "LBL_RSRC_TP",
    field: "RSRC_TP",
    width: 100,
    align: "center",
    editable: false,
    insertable: true,
    codeKey: "resourceType",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 100,
    align: "center",
    editable: false,
    insertable: false,
  },
  {
    type: "date",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 150,
    align: "center",
    editable: false,
    insertable: false,
  },
];
