export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "datetime",
    headerName: "LBL_RECEIVE_DATE",
    field: "CRE_DTTM",
    width: 120,
    align: "center",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    width: 110,
    align: "center",
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_INTERFACE_TCD",
    field: "IF_TCD",
    codeKey: "interfaceType",
    width: 100,
    align: "center",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_USR_RE_PRCS_YN",
    field: "RE_PRCS_BY_USR_YN",
    width: 120,
    align: "center",
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_IF_PRCS_STS",
    field: "IF_PRCS_STS",
    codeKey: "interfaceStatus",
    width: 120,
    align: "center",
  },
  {
    type: "combo",
    headerName: "LBL_PRCS_MSG",
    field: "IF_PRCS_MSG_CD",
    codeKey: "interfaceMessage",
    width: 150,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_PRCS_MSG_DESC",
    field: "IF_PRCS_MSG_DESC",
    width: 150,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_CODE",
    field: "CARR_CD",
    width: 100,
    align: "center",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_NAME",
    field: "CARR_NM",
    width: 130,
    align: "left",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_ZIP_CODE",
    field: "ZIP_CD",
    width: 60,
    align: "center",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_ADDR",
    field: "DTL_ADDR1",
    width: 250,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ADDR",
    field: "DTL_ADDR2",
    width: 250,
    align: "left",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_REPRESENTITIVE",
    field: "REP_NM",
    width: 100,
    align: "center",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_REPRESENTATIVE_TEL",
    field: "REP_CNTC_NO",
    width: 120,
    align: "left",
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 150,
    align: "center",
    editable: true,
  },
  {
    type: "datetime",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 150,
    align: "center",
    editable: true,
  },
];

export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    width: 110,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DEL_FLAG",
    field: "DEL_FLAG",
    width: 80,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_CODE",
    field: "CARR_CD",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_BANK_ACCOUNT_ID",
    field: "BANK_ACNT_ID",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_BANK_KEY",
    field: "BANK_KEY",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_BANK_ACNT_HOLDER",
    field: "ACNT_HOLDER",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_ACNT_HOLDER",
    field: "ACNT_DESCR",
    width: 150,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_CODE",
    field: "CUST_CD",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 120,
    align: "center",
    editable: false,
  },
];

export const SUB02_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    width: 110,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DEL_FLAG",
    field: "DEL_FLAG",
    width: 80,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_CODE",
    field: "CARR_CD",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_CODE",
    field: "CUST_CD",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_PAYMENT_TERM",
    field: "PAYMENT_TERM",
    width: 150,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 120,
    align: "center",
  },
];
