export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "numeric",
    headerName: "LBL_JOB_ID",
    field: "JOB_ID",
    editable: false,
    insertable: false,
    width: 70,
  },
  {
    type: "text",
    headerName: "LBL_HSTR_RSLT",
    field: "JOB_PRCS_STS",
    editable: false,
    insertable: false,
    width: 80,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_JOB_NM",
    field: "JOB_NM",
    editable: true,
    insertable: true,
    width: 170,
  },
  {
    type: "text",
    headerName: "LBL_JOB_CLS",
    field: "JOB_CLS",
    editable: true,
    insertable: true,
    width: 240,
  },
  {
    type: "combo",
    headerName: "LBL_JOB_TYP",
    field: "JOB_TYP",
    codeKey: "jobType",
    editable: true,
    insertable: true,
    width: 90,
  },
  {
    type: "combo",
    headerName: "LBL_JOB_RUN_TYP",
    field: "JOB_RUN_TYP",
    codeKey: "jobRunType",
    editable: true,
    insertable: true,
    width: 90,
  },
  {
    type: "text",
    headerName: "LBL_JOB_DESC",
    field: "JOB_DESC",
    editable: true,
    insertable: true,
    width: 260,
  },
  {
    type: "text",
    headerName: "LBL_JOB_IN_VALS",
    field: "JOB_IN_VALS",
    editable: true,
    insertable: true,
    width: 90,
  },
  {
    type: "check",
    headerName: "LBL_JOB_USE_YN",
    field: "JOB_USE_YN",
    editable: true,
    insertable: true,
    defaultValue: "Y",
    width: 80,
  },
];

export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "numeric",
    headerName: "LBL_JOB_ID",
    field: "JOB_ID",
    editable: false,
    insertable: false,
    width: 80,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "numeric",
    headerName: "LBL_TRGR_ID",
    field: "TRGR_ID",
    editable: false,
    insertable: false,
    width: 90,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_USE_YN",
    field: "TRGR_USE_YN",
    editable: true,
    insertable: true,
    defaultValue: "Y",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_JOB_TYP",
    field: "JOB_TYP",
    editable: false,
    insertable: false,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_JOB_RUN_TYP",
    field: "JOB_RUN_TYP",
    editable: false,
    insertable: false,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_JOB_CLS",
    field: "JOB_CLS",
    editable: false,
    insertable: false,
    hide: true,
  },
  {
    type: "datetime",
    headerName: "LBL_TRGR_STRT_DTTM",
    field: "TRGR_STRT_DTTM",
    editable: true,
    insertable: true,
    width: 150,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "datetime",
    headerName: "LBL_TRGR_END_DTTM",
    field: "TRGR_END_DTTM",
    editable: true,
    insertable: true,
    width: 150,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "combo",
    headerName: "LBL_TRGR_CCL_TYP",
    field: "TRGR_CCL_TYP",
    codeKey: "triggerCycleType",
    editable: true,
    insertable: true,
    width: 110,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "numeric",
    headerName: "LBL_TRGR_CCL",
    field: "TRGR_CCL",
    editable: true,
    insertable: true,
    width: 90,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "numeric",
    headerName: "LBL_TRGR_RPT_CNT",
    field: "TRGR_RPT_CNT",
    editable: true,
    insertable: true,
    width: 90,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "numeric",
    headerName: "LBL_TRGR_RUN_CNT",
    field: "TRGR_RUN_CNT",
    editable: false,
    insertable: false,
    width: 90,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_TRGR_SEC",
    field: "TRGR_SEC",
    editable: true,
    insertable: true,
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_TRGR_MIN",
    field: "TRGR_MIN",
    editable: true,
    insertable: true,
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_TRGR_HOUR",
    field: "TRGR_HOUR",
    editable: true,
    insertable: true,
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_TRGR_DATE",
    field: "TRGR_DATE",
    editable: true,
    insertable: true,
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_TRGR_MONTH",
    field: "TRGR_MONTH",
    editable: true,
    insertable: true,
    width: 80,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_LAST_DAY",
    field: "TRGR_LAST_DAY",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 90,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "numeric",
    headerName: "LBL_TRGR_TH_DAY",
    field: "TRGR_TH_DAY",
    editable: true,
    insertable: true,
    width: 90,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_SUN",
    field: "TRGR_SUN",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_MON",
    field: "TRGR_MON",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_TUE",
    field: "TRGR_TUE",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_WED",
    field: "TRGR_WED",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_THU",
    field: "TRGR_THU",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_FRI",
    field: "TRGR_FRI",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "check",
    headerName: "LBL_TRGR_SAT",
    field: "TRGR_SAT",
    editable: true,
    insertable: true,
    defaultValue: "N",
    width: 70,
    cellStyle: { textAlign: "center" },
  },
  {
    type: "numeric",
    headerName: "LBL_TRGR_YEAR",
    field: "TRGR_YEAR",
    editable: true,
    insertable: true,
    width: 80,
  },
];

export const SUB02_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "numeric",
    headerName: "LBL_JOB_ID",
    field: "JOB_ID",
    editable: false,
    insertable: false,
    hide: true,
  },
  {
    type: "numeric",
    headerName: "LBL_TRGR_ID",
    field: "TRGR_ID",
    editable: false,
    insertable: false,
    hide: true,
  },
  {
    type: "numeric",
    headerName: "LBL_HSTR_SEQ",
    field: "HSTR_SEQ",
    editable: false,
    insertable: false,
    width: 90,
  },
  {
    type: "text",
    headerName: "LBL_SCHDLR_ID",
    field: "SCHDLR_ID",
    editable: false,
    insertable: false,
    width: 90,
  },
  {
    type: "text",
    headerName: "LBL_HSTR_RSLT",
    field: "HSTR_RSLT",
    editable: false,
    insertable: false,
    width: 70,
    cellStyle: (params: any) =>
      String(params.value ?? "").trim() === "F"
        ? { textAlign: "center", backgroundColor: "#fee2e2", color: "#991b1b" }
        : { textAlign: "center" },
  },
  {
    type: "text",
    headerName: "LBL_TRGR_RSLT",
    field: "TRGR_RSLT",
    editable: false,
    insertable: false,
    width: 80,
  },
  {
    type: "date",
    headerName: "LBL_TRGR_STRT_DTTM",
    field: "TRGR_STRT_DTTM",
    editable: false,
    insertable: false,
    width: 150,
  },
  {
    type: "date",
    headerName: "LBL_TRGR_END_DTTM",
    field: "TRGR_END_DTTM",
    editable: false,
    insertable: false,
    width: 150,
  },
];
