export const MAIN_COLUMN_DEFS = [
  {
    type: "text",
    headerName: "LBL_MENU_CD",
    field: "MENUCODE",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_MENU_NM",
    field: "MENUNAME",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_APPL_CD",
    field: "APPLCODE",
    width: 200,
    codeKey: "codeList",
  },
  {
    type: "text",
    headerName: "LBL_MLT_LANG_KEY",
    field: "MSG_CD",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_OLDER_MENU_PATH",
    field: "SUPERMENUCODE",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_ORDER_BY",
    field: "DSPLY_SEQ",
    width: 80,
    editable: true,
    insertable: true,
  },
  {
    type: "text",
    headerName: "LBL_URL_PATH",
    field: "URL",
    minWidth: 200,
    flex: 1,
    editable: true,
    insertable: true,
  },
  {
    type: "check",
    headerName: "LBL_USE_YN",
    field: "USE_YN",
    width: 70,
    editable: true,
    insertable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_RSRC_CNT",
    field: "RSRC_CNT",
    width: 55,
  },
];
