export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "datetime",
    headerName: "LBL_RECEIVE_DATE",
    field: "CRE_DTTM",
    width: 150,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_INTERFAE_ID",
    field: "IF_ID",
    width: 110,
    align: "center",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_INTERFACE_TCD",
    field: "IF_TCD",
    codeKey: "interfaceType",
    width: 100,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_USR_RE_PRCS_YN",
    field: "RE_PRCS_BY_USR_YN",
    width: 120,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_IF_PRCS_STS",
    field: "IF_PRCS_STS",
    codeKey: "interfaceStatus",
    statusStyle: "IF_PRCS_STS",
    width: 120,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_PRCS_MSG",
    field: "IF_PRCS_MSG_CD",
    codeKey: "interfaceMessage",
    width: 150,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_PRCS_MSG_DESC",
    field: "IF_PRCS_MSG_DESC",
    width: 150,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_CODE",
    field: "CUST_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_NAME",
    field: "CUST_NM",
    width: 130,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_SALES_ORG_CD",
    field: "SALES_ORG_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_SALES_ORG_NM",
    field: "SALES_ORG_NM",
    width: 130,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_PLANT_CD",
    field: "PLANT_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_PLANT_NM",
    field: "PLANT_NM",
    width: 130,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_SHPNT_CD",
    field: "SHPNT_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_SHPNT_NM",
    field: "SHPNT_NM",
    width: 130,
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_BP_CD",
    field: "BP_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_SLOC_CD",
    field: "SLOC_CD",
    width: 100,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_SLOC_NM",
    field: "SLOC_NM",
    width: 130,
    align: "left",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    width: 150,
    align: "center",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    width: 150,
    align: "center",
    editable: false,
  },
  {
    type: "datetime",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    width: 150,
    align: "center",
    editable: false,
  },
];
