import { makeAuditColumns } from "@/app/components/grid/commonColumns";
import { numberValueFormatter } from "@/app/components/grid/commonFormatters";

// 메인 그리드
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_AP_ID", field: "AP_ID" },
  {
    type: "text",
    headerName: "LBL_FINANCIAL_STATUS",
    field: "AP_FI_STS",
    codeKey: "financialStatus",
  },
  { type: "text", headerName: "LBL_COST_CHECK", field: "COST_CHECK" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  { type: "text", headerName: "LBL_PAY_CARRIER_CODE", field: "PAY_CARR_CD" },
  { type: "text", headerName: "LBL_PAY_CARRIER_NAME", field: "PAY_CARR_NM" },
  { type: "text", headerName: "LBL_INS_COST", field: "INS_COST" },
  { type: "text", headerName: "LBL_ADJ_COST", field: "ADJ_COST" },
  { type: "text", headerName: "LBL_CFM_COST", field: "CFM_COST" },
  { type: "text", headerName: "LBL_CURRENCY", field: "CURR_CD" },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO" },
  { type: "text", headerName: "LBL_CARRIER_CODE", field: "CARR_CD" },
  { type: "text", headerName: "LBL_CARRIER_NAME", field: "CARR_NM" },
  { type: "text", headerName: "LBL_CLOSING_REF_NUM", field: "AP_CLZ_REF_NO" },
  { type: "text", headerName: "LBL_DLVRY_DATE", field: "DLVRY_DT" },
  { type: "text", headerName: "LBL_AP_TP", field: "AP_TP", codeKey: "apType" },
  { type: "text", headerName: "LBL_DRIVER_NAME", field: "DRVR_NM" },
  { type: "text", headerName: "LBL_TARIFF_CODE", field: "TRF_CD" },
  { type: "text", headerName: "LBL_TARIFF_NAME", field: "TRF_NM" },
  { type: "text", headerName: "LBL_VEHICLE_TYPE_NAME", field: "VEH_TP_NM" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD" },
  ...makeAuditColumns({
    delete: true,
    rowStatus: true,
    insertPerson: true,
    insertDate: true,
    updatePerson: true,
    updateTime: true,
  }),
];

// 비용상세정보
export const COST_DETAIL_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  { type: "text", headerName: "LBL_RATE_ITEM_CD", field: "CHG_CD" },
  { type: "text", headerName: "LBL_RATE_ITEM_NM", field: "CHG_NM" },
  {
    type: "text",
    headerName: "LBL_INS_COST",
    field: "INS_COST",
    aggFunc: "sum",
    summable: true,
    valueFormatter: numberValueFormatter,
  },
  {
    type: "text",
    headerName: "LBL_ADJ_COST",
    field: "ADJ_COST",
    aggFunc: "sum",
    summable: true,
    valueFormatter: numberValueFormatter,
  },
  {
    type: "text",
    headerName: "LBL_CFM_COST",
    field: "CFM_COST",
    aggFunc: "sum",
    summable: true,
    valueFormatter: numberValueFormatter,
  },
  { type: "text", headerName: "LBL_OP_ADJUST_REASON", field: "ADJ_RSN" },
  { type: "text", headerName: "LBL_MG_ADJUST_REASON", field: "CFM_RSN" },
  { type: "text", headerName: "LBL_ADJ_PERSON_ID", field: "ADJ_USR_ID" },
  { type: "text", headerName: "LBL_ADJ_DATETIME", field: "ADJ_DTTM" },
  { type: "text", headerName: "LBL_CFM_PERSON_ID", field: "CFM_USR_ID" },
  { type: "text", headerName: "LBL_CFM_DATETIME", field: "CFM_DTTM" },
  { type: "text", headerName: "LBL_AP_ID", field: "AP_ID" },
  ...makeAuditColumns({
    delete: true,
    rowStatus: true,
    insertPerson: true,
    insertDate: true,
    updatePerson: true,
    updateTime: true,
  }),
];

// 경유처
export const WAYPOINT_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  { type: "text", headerName: "LBL_LOCATION_ID", field: "LOC_CD" },
  { type: "text", headerName: "LBL_LOCATION_NAME", field: "LOC_NM" },
  { type: "text", headerName: "LBL_PICKDROP_DIV", field: "STOP_TP", codeKey: "pickDropDiv" },
  { type: "text", headerName: "LBL_ZONE_CD", field: "ZN_CD" },
  { type: "text", headerName: "LBL_ZONE_NM", field: "ZN_NM" },
  { type: "text", headerName: "LBL_STATE", field: "STATE" },
  { type: "text", headerName: "LBL_CITY", field: "CITY" },
  { type: "text", headerName: "LBL_DETAIL_ADDRESS", field: "STREET" },
  { type: "text", headerName: "LBL_LATITUDE", field: "LAT" },
  { type: "text", headerName: "LBL_LONGITUDE", field: "LON" },
  { type: "text", headerName: "LBL_ZIP_CODE", field: "ZIP" },
  { type: "text", headerName: "LBL_LOADING_CBM", field: "LDNG_VOL" },
  { type: "text", headerName: "LBL_LOADING_WEIGHT_KG", field: "LDNG_WGT" },
  { type: "text", headerName: "LBL_LOADING_FLEX_QTY1", field: "LDNG_FLEX_QTY1" },
  { type: "text", headerName: "LBL_LOADING_FLEX_QTY2", field: "LDNG_FLEX_QTY2" },
  { type: "text", headerName: "LBL_LOADING_FLEX_QTY3", field: "LDNG_FLEX_QTY3" },
  { type: "text", headerName: "LBL_LOADING_FLEX_QTY4", field: "LDNG_FLEX_QTY4" },
  { type: "text", headerName: "LBL_LOADING_FLEX_QTY5", field: "LDNG_FLEX_QTY5" },
  { type: "text", headerName: "LBL_UNLOADING_CBM", field: "UNLDNG_VOL" },
  { type: "text", headerName: "LBL_UNLOADING_WEIGHT_KG", field: "UNLDNG_WGT" },
  { type: "text", headerName: "LBL_UNLOADING_FLEX_QTY1", field: "UNLDNG_FLEX_QTY1" },
  { type: "text", headerName: "LBL_UNLOADING_FLEX_QTY2", field: "UNLDNG_FLEX_QTY2" },
  { type: "text", headerName: "LBL_UNLOADING_FLEX_QTY3", field: "UNLDNG_FLEX_QTY3" },
  { type: "text", headerName: "LBL_UNLOADING_FLEX_QTY4", field: "UNLDNG_FLEX_QTY4" },
  { type: "text", headerName: "LBL_UNLOADING_FLEX_QTY5", field: "UNLDNG_FLEX_QTY5" },
];
