// 그리드 컬럼 정의 (서버 NoticeMain / NoticeSub01 기준)
// audit 컬럼(삭제/상태/등록자·등록일시/수정자·수정일시)은 DataGrid 가 자동 추가(model.bind).

// ── 메인: 공지 ─────────────────────────────────────────────────────
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "NOTICE_ID", field: "NOTICE_ID", align: "center", width: 100, hide: true },
  {
    type: "combo",
    headerName: "LBL_DISPLAY_TP",
    field: "DSPLY_TP_CD",
    codeKey: "ntceDpTp",
    align: "center",
    width: 100,
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "TITLE",
    field: "TITLE",
    align: "center",
    width: 150,
    insertable: true,
    editable: true,
    required: true,
    validators: { required: true, max: 100 },
  },
  {
    type: "text",
    headerName: "CONTENTS",
    field: "CONTENTS",
    align: "left",
    width: 410,
    insertable: true,
    editable: true,
    required: true,
    validators: { required: true, max: 1000 },
  },
  { type: "text", headerName: "LBL_DIVISION_CODE", field: "DIV_CD", align: "center", width: 100, hide: true },
  { type: "text", headerName: "LBL_DIVISION", field: "DIV_NM", align: "left", width: 100 },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD", align: "center", width: 100, hide: true },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP", field: "LGST_GRP_NM", align: "left", width: 120 },
  {
    type: "check",
    headerName: "LBL_POPUP_DISPLAY_YN",
    field: "POPUP_DSPLY_YN",
    align: "center",
    width: 80,
    insertable: true,
    editable: true,
    defaultValue: "N",
  },
  {
    type: "check",
    headerName: "FIX_YN",
    field: "FIX_YN",
    align: "center",
    width: 80,
    insertable: true,
    editable: true,
    defaultValue: "N",
  },
  {
    type: "datetime",
    headerName: "NOTI_RESERV_DTTM",
    field: "NOTI_RESERV_DTTM",
    align: "center",
    width: 150,
    insertable: true,
    editable: true,
  },
  {
    type: "date",
    headerName: "NOTI_VALID_FROM_DTTM",
    field: "NOTI_VALID_FRM_DTTM",
    align: "center",
    width: 100,
    insertable: true,
    editable: true,
    required: true,
    validators: { required: true },
  },
  {
    type: "date",
    headerName: "NOTI_VALID_TO_DTTM",
    field: "NOTI_VALID_TO_DTTM",
    align: "center",
    width: 100,
    insertable: true,
    editable: true,
    required: true,
    validators: { required: true },
  },
  { type: "text", headerName: "FILE_ID", field: "FILE_ID", hide: true },
  { type: "text", headerName: "LBL_FILE_ATTACH", field: "FILE_NM", align: "left", width: 150 },
];

// ── sub01: 공지대상차량 ─────────────────────────────────────────────
export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_VEHICLE_CODE", field: "VEH_ID", align: "center", width: 120 },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO", align: "left", width: 120 },
  { type: "text", headerName: "LBL_CARRIER_CODE", field: "CARR_CD", align: "center", width: 90 },
  { type: "text", headerName: "LBL_CARRIER_NAME", field: "CARR_NM", align: "left", width: 90 },
  { type: "text", headerName: "LBL_DRIVER_CODE", field: "DRVR_ID", align: "center", width: 90 },
  { type: "text", headerName: "LBL_DRIVER_NM", field: "DRVR_NM", align: "left", width: 90 },
  {
    type: "combo",
    headerName: "LBL_VEHICLE_OPERATION_TYPE",
    field: "VEH_OP_TP",
    codeKey: "vehicleOpType",
    align: "center",
    width: 90,
  },
  { type: "text", headerName: "LBL_WORK_STIME", field: "WORK_STIME", align: "center", width: 90 },
  { type: "text", headerName: "LBL_WORK_ETIME", field: "WORK_ETIME", align: "center", width: 90 },
];
