import { makeAuditColumns } from "@/app/components/grid/commonColumns";
import { numberValueFormatter } from "@/app/components/grid/commonFormatters";

// 메인 그리드
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  { type: "text", headerName: "LBL_AP_ID", field: "AP_ID" },
  {
    type: "text",
    headerName: "LBL_FINANCIAL_STATUS",
    field: "AP_FI_STS",
    codeKey: "dsFiSts",
  },
  { type: "text", headerName: "LBL_DLVRY_DATE", field: "DLVRY_DT" },
  { type: "text", headerName: "LBL_PAY_CARRIER_CODE", field: "PAY_CARR_CD" },
  { type: "text", headerName: "LBL_PAY_CARRIER_NAME", field: "PAY_CARR_NM" },
  {
    type: "text",
    headerName: "LBL_DLY_SETL_STS",
    field: "DLY_SETL_STS",
    codeKey: "dlySetlSts",
  },
  { type: "text", headerName: "LBL_TOTAL_INS_COST", field: "INS_COST" },
  { type: "text", headerName: "LBL_TOTAL_ADJ_COST", field: "ADJ_COST" },
  { type: "text", headerName: "LBL_DEPARTURE", field: "LOC_DE_NM" },
  { type: "text", headerName: "LBL_DESTINATION", field: "LOC_NM" },
  { type: "text", headerName: "LBL_CARRIER_NAME", field: "CARR_NM" },
  { type: "text", headerName: "LBL_VEHICLE_TYPE_NAME", field: "VEH_TP_NM" },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO" },
  { type: "text", headerName: "LBL_DRIVER_NAME", field: "DRVR_NM" },
  { type: "text", headerName: "LBL_FI_SETL_GRP_ID", field: "AP_SETL_GRP_ID" },
  { type: "text", headerName: "LBL_AP_END_DATE", field: "TO_DTTM" },
  { type: "text", headerName: "LBL_DISPATCH_REFERENCE", field: "DSP_MEMO_DESC" },
  { type: "text", headerName: "LBL_ORDER_TYPE", field: "SHPM_TP_NM" },
  { type: "text", headerName: "LBL_CFM_NET_WGT", field: "CFM_NET_WGT" },
  { type: "text", headerName: "LBL_CFM_GRS_WGT", field: "CFM_GRS_WGT" },
  { type: "text", headerName: "LBL_PBOX_QTY", field: "CFM_PBOX_QTY" },
  { type: "text", headerName: "LBL_BOX_QTY", field: "CFM_BOX_QTY" },
  { type: "text", headerName: "LBL_PLT_QTY", field: "CFM_PLT_QTY" },
  { type: "text", headerName: "LBL_RTNR_QTY", field: "CFM_RTNR_QTY" },
  { type: "text", headerName: "LBL_CONFIRMED_QTY_UOM", field: "SHPM_CFM_UOM" },
  { type: "text", headerName: "LBL_REP_ITEM_CD", field: "REP_ITEM_CD" },
  { type: "text", headerName: "LBL_REP_ITEM_NM", field: "REP_ITEM_NM" },
  { type: "text", headerName: "LBL_AP_TP", field: "AP_TP", codeKey: "apType" },
  { type: "text", headerName: "LBL_CLOSING_REF_NUM", field: "AP_CLZ_REF_NO" },
  { type: "text", headerName: "LBL_TARIFF_CODE", field: "TRF_CD" },
  { type: "text", headerName: "LBL_TARIFF_NAME", field: "TRF_NM" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD" },
  { type: "text", headerName: "LBL_PAY_TO_CD", field: "PAY_TO_CD", codeKey: "payTo" },
  { type: "text", headerName: "LBL_AP_MEMO", field: "MEMO_DESC" },
  { type: "text", headerName: "LBL_FIX_SEQ", field: "RTN_NO" },
  { type: "text", headerName: "LBL_TARGET_SYS", field: "AP_TARGET_SYS_LIST" },
  { type: "text", headerName: "LBL_REFERENCE_1", field: "REF_VAL_1" },
  { type: "text", headerName: "LBL_REFERENCE_2", field: "REF_VAL_2" },
  { type: "text", headerName: "LBL_REFERENCE_3", field: "REF_VAL_3" },
  { type: "text", headerName: "LBL_REFERENCE_4", field: "REF_VAL_4" },
  { type: "text", headerName: "LBL_REFERENCE_5", field: "REF_VAL_5" },
  { type: "text", headerName: "LBL_REFERENCE_6", field: "REF_VAL_6" },
  { type: "text", headerName: "LBL_REFERENCE_7", field: "REF_VAL_7" },
  { type: "text", headerName: "LBL_REFERENCE_8", field: "REF_VAL_8" },
  { type: "text", headerName: "LBL_REFERENCE_9", field: "REF_VAL_9" },
  { type: "text", headerName: "LBL_REFERENCE_10", field: "REF_VAL_10" },
  { type: "text", headerName: "LBL_REFERENCE_11", field: "REF_VAL_11" },
  { type: "text", headerName: "LBL_REFERENCE_12", field: "REF_VAL_12" },
  { type: "text", headerName: "LBL_CHCKD_DTTM", field: "CHCKD_DTTM" },
  { type: "text", headerName: "LBL_CHCKD_USR_ID", field: "CHCKD_USR_ID" },
  ...makeAuditColumns({
    delete: true,
    rowStatus: true,
    insertPerson: true,
    insertDate: true,
    updatePerson: true,
    updateTime: true,
  }),
];

// 비용상세정보 (좌측)
export const COST_DETAIL_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_RATE_ITEM_CD", field: "CHG_CD" },
  { type: "text", headerName: "LBL_RATE_ITEM_NM", field: "CHG_NM" },
  {
    headerName: "LBL_INS_COST",
    field: "INS_COST",
    type: "numeric",
    aggFunc: "sum",
    summable: true,
    valueFormatter: numberValueFormatter,
  },
  {
    headerName: "LBL_ADJ_COST",
    field: "ADJ_COST",
    type: "numeric",
    aggFunc: "sum",
    summable: true,
    valueFormatter: numberValueFormatter,
  },
  { type: "text", headerName: "LBL_OP_ADJUST_REASON", field: "ADJ_RSN" },
  { type: "text", headerName: "LBL_DOC_CNT", field: "FILE_CNT" },
  { type: "text", headerName: "LBL_CAL_TCD", field: "CAL_TCD", codeKey: "calTcd" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  { type: "text", headerName: "LBL_ADJ_PERSON_ID", field: "ADJ_USR_ID" },
  { type: "text", headerName: "LBL_ADJ_DATETIME", field: "ADJ_DTTM" },
  { type: "text", headerName: "LBL_AP_ID", field: "AP_ID" },
  {
    type: "text",
    headerName: "LBL_FINANCIAL_STATUS",
    field: "AP_FI_STS",
    codeKey: "financialStatus",
  },
  ...makeAuditColumns({
    delete: true,
    rowStatus: true,
  }),
];

// 비용상세정보 (우측) — 함수
export const COST_FUNCTION_COLUMN_DEFS = [
  { type: "text", headerName: "LBL_COST_CD", field: "COST_CD" },
  { type: "text", headerName: "LBL_COST_NM", field: "COST_NM" },
  { type: "text", headerName: "LBL_CLASS_CODE", field: "CLSS_CD" },
  { type: "text", headerName: "LBL_CLASS_NAME", field: "CLSS_NM" },
  { type: "text", headerName: "LBL_CLSS_CD_VAL", field: "CLSS_CD_VAL" },
  { type: "text", headerName: "LBL_ADJ_CLSS_CD_VAL", field: "ADJ_CLSS_CD_VAL" },
  { type: "text", headerName: "LBL_COND_CLSS_CD", field: "COND_CLSS_CD" },
  { type: "text", headerName: "LBL_COND_CLSS_CD_VAL", field: "COND_CLSS_CD_VAL" },
  { type: "text", headerName: "LBL_COST_OPTION", field: "OPR", codeKey: "operatorType" },
  { type: "text", headerName: "LBL_COST_UNIT", field: "ADJ_RT" },
  { type: "text", headerName: "LBL_UNIT_COST", field: "COST" },
  { type: "text", headerName: "LBL_ADJ_CALC_COST", field: "ADJ_CALC_COST" },
  { type: "text", headerName: "LBL_DESTINATION_CODE", field: "LOC_CD" },
  { type: "text", headerName: "LBL_DESTINATION_NM", field: "LOC_NM" },
];

// 경유처
export const WAYPOINT_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  { type: "text", headerName: "LBL_LOCATION_ID", field: "LOC_CD" },
  { type: "text", headerName: "LBL_LOCATION_NAME", field: "LOC_NM" },
  { type: "text", headerName: "LBL_PICKDROP_DIV", field: "STOP_TP", codeKey: "pickDropDiv" },
  { type: "text", headerName: "LBL_DIRECT_DIST", field: "DIRECT_DIST" },
  { type: "text", headerName: "LBL_ADJ_DIRECT_DIST", field: "ADJ_DIRECT_DIST" },
  {
    headerName: "LBL_TRNST_PREVSTOP_DIST",
    field: "PRVS_DIST",
    type: "numeric",
    aggFunc: "sum",
    summable: true,
  },
  {
    type: "text",
    headerName: "LBL_ADJ_PRVS_DIST",
    field: "ADJ_PRVS_DIST",
  },
  {
    type: "text",
    headerName: "LBL_DISIT_ADJ_RSN",
    field: "ADJ_RSN",
  },
  { type: "text", headerName: "LBL_STATE", field: "STATE" },
  { type: "text", headerName: "LBL_CITY", field: "CITY" },
  { type: "text", headerName: "LBL_DETAIL_ADDRESS", field: "STREET" },
  { type: "text", headerName: "LBL_LATITUDE", field: "LAT" },
  { type: "text", headerName: "LBL_LONGITUDE", field: "LON" },
  { type: "text", headerName: "LBL_ZIP_CODE", field: "ZIP" },
  { type: "text", headerName: "LBL_LD_PLN_QTY_UOM", field: "LD_PLN_QTY_UOM" },
  { type: "text", headerName: "LBL_LDNG_CFM_QTY_UOM", field: "LDNG_CFM_QTY_UOM" },
  { type: "text", headerName: "LBL_LDNG_PLN_WGT", field: "LDNG_PLN_WGT" },
  { type: "text", headerName: "LBL_LDNG_CFM_WGT", field: "LDNG_CFM_WGT" },
  { type: "text", headerName: "LBL_LDNG_PLN_FLEX_QTY1", field: "LDNG_PLN_FLEX_QTY1" },
  { type: "text", headerName: "LBL_LDNG_CFM_FLEX_QTY1", field: "LDNG_CFM_FLEX_QTY1" },
  { type: "text", headerName: "LBL_LDNG_PLN_FLEX_QTY2", field: "LDNG_PLN_FLEX_QTY2" },
  { type: "text", headerName: "LBL_LDNG_CFM_FLEX_QTY2", field: "LDNG_CFM_FLEX_QTY2" },
  { type: "text", headerName: "LBL_LDNG_PLN_FLEX_QTY3", field: "LDNG_PLN_FLEX_QTY3" },
  { type: "text", headerName: "LBL_LDNG_CFM_FLEX_QTY3", field: "LDNG_CFM_FLEX_QTY3" },
  { type: "text", headerName: "LBL_LDNG_PLN_FLEX_QTY4", field: "LDNG_PLN_FLEX_QTY4" },
  { type: "text", headerName: "LBL_LDNG_CFM_FLEX_QTY4", field: "LDNG_CFM_FLEX_QTY4" },
  { type: "text", headerName: "LBL_LDNG_PLN_FLEX_QTY5", field: "LDNG_PLN_FLEX_QTY5" },
  { type: "text", headerName: "LBL_LDNG_CFM_FLEX_QTY5", field: "LDNG_CFM_FLEX_QTY5" },
  { type: "text", headerName: "LBL_UNLD_PLN_QTY_UOM", field: "UNLD_PLN_QTY_UOM" },
  { type: "text", headerName: "LBL_UNLDNG_CFM_QTY_UOM", field: "UNLDNG_CFM_QTY_UOM" },
  { type: "text", headerName: "LBL_UNLDNG_PLN_WGT", field: "UNLDNG_PLN_WGT" },
  { type: "text", headerName: "LBL_UNLDNG_CFM_WGT", field: "UNLDNG_CFM_WGT" },
  { type: "text", headerName: "LBL_UNLDNG_PLN_FLEX_QTY1", field: "UNLDNG_PLN_FLEX_QTY1" },
  { type: "text", headerName: "LBL_UNLDNG_CFM_FLEX_QTY1", field: "UNLDNG_CFM_FLEX_QTY1" },
  { type: "text", headerName: "LBL_UNLDNG_PLN_FLEX_QTY2", field: "UNLDNG_PLN_FLEX_QTY2" },
  { type: "text", headerName: "LBL_UNLDNG_CFM_FLEX_QTY2", field: "UNLDNG_CFM_FLEX_QTY2" },
  { type: "text", headerName: "LBL_UNLDNG_PLN_FLEX_QTY3", field: "UNLDNG_PLN_FLEX_QTY3" },
  { type: "text", headerName: "LBL_UNLDNG_CFM_FLEX_QTY3", field: "UNLDNG_CFM_FLEX_QTY3" },
  { type: "text", headerName: "LBL_UNLDNG_PLN_FLEX_QTY4", field: "UNLDNG_PLN_FLEX_QTY4" },
  { type: "text", headerName: "LBL_UNLDNG_CFM_FLEX_QTY4", field: "UNLDNG_CFM_FLEX_QTY4" },
  { type: "text", headerName: "LBL_UNLDNG_PLN_FLEX_QTY5", field: "UNLDNG_PLN_FLEX_QTY5" },
  { type: "text", headerName: "LBL_UNLDNG_CFM_FLEX_QTY5", field: "UNLDNG_CFM_FLEX_QTY5" },
  { type: "text", headerName: "LBL_RTR_PBOX", field: "OUT_COUNT" },
  { type: "text", headerName: "LBL_RTR_PLT", field: "PLT_OUT_COUNT" },
];

// 증빙문서
export const EVIDENCE_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_OPER_TCD", field: "CHG_CD" },
  { type: "text", headerName: "LBL_OPER_TNM", field: "CHG_NM" },
  { type: "text", headerName: "LBL_FILE_ID", field: "FILE_ID" },
  { type: "text", headerName: "LBL_ORG_FILE_NM", field: "ORG_FILE_NM" },
  { type: "text", headerName: "LBL_FILE_EXTENSION", field: "FILE_NM_EXTENSION" },
  ...makeAuditColumns({
    delete: true,
    insertPerson: true,
    insertDate: true,
  }),
];
