import { Lang } from "@/app/services/common/Lang";

export const MAIN_COLUMN_DEFS = [
  { headerName: "No" }, // 자동 일련번호
  {
    type: "text",
    headerName: "LBL_AR_CHG_CD",
    field: "AR_CHG_CD",
    required: true,
    insertable: true,
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_AR_CHG_NM",
    field: "AR_CHG_NM",
    required: true,
    insertable: true,
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_AR_CHG_TP",
    field: "AR_CHG_TP",
    codeKey: "arChgTpList",
    required: true,
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: Lang.get ("LBL_GL_LDGR_CD") + "(" + Lang.get("LBL_DEFAULT") + ")",
    noLang:true,
    field: "GNRL_LDGR_CD",
    insertable: true,
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_CHG_SIGN_TP",
    field: "CHG_SIGN_TP",
    codeKey: "chgSignTpList",
    required: true,
    insertable: true,
    editable: true,
  },
  {
    type: "combo",
    headerName: Lang.get("LBL_TAX_TCD") + "(" + Lang.get("LBL_DEFAULT") + ")",
    noLang:true,
    field: "TAX_TCD",
    codeKey: "taxTcdList",
    required: true,
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_INV_PRINT_YN",
    field: "INV_PRINT_YN",
    insertable: true,
    editable: true,
  },
  {
    type: "numeric",
    headerName: "LBL_DSPL_ORD",
    field: "DSPLY_SEQ",
    required: true,
    insertable: true,
    editable: true,
  },
  {
    type: "text",
    headerName: "LBL_REMARK",
    field: "RMK",
    insertable: true,
    editable: true,
  },
  {
    type: "check",
    headerName: "LBL_USE_YN",
    field: "USE_YN",
    insertable: true,
    editable: true,
  },
];
