const DAY_COLUMN = (headerName: string, field: string) => ({
  type: "numeric" as const,
  headerName,
  field,
  align: "right" as const,
  insertable: true,
  editable: true,
  validators: {
    min: 0,
    max: 999,
  },
});

export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_LDTM_ID",
    field: "DLVRY_LDTM_ID",
    align: "center",
    width: 120,
  },
  {
    type: "popup",
    headerName: "LBL_CARRIER_CODE",
    field: "CARR_CD",
    nameField: "CARR_NM",
    sqlId: "selectCarrListWithLgst",
    popupTitle: "LBL_CARRIER_CODE",
    required: true,
    insertable: true,
    align: "center",
    width: 130,
    extraParams: (row) => ({ keyParam: row?.LGST_GRP_CD ?? "" }),
  },
  {
    type: "text",
    headerName: "LBL_CARRIER_NAME",
    field: "CARR_NM",
    align: "left",
    width: 120,
  },
  {
    type: "date",
    headerName: "LBL_FROM_DTTM",
    field: "FRM_DT",
    required: true,
    insertable: true,
    align: "center",
    width: 80,
  },
  {
    type: "date",
    headerName: "LBL_TO_DTTM",
    field: "TO_DT",
    required: true,
    insertable: true,
    editable: true,
    align: "center",
    width: 80,
  },
  {
    type: "check",
    headerName: "LBL_USE_Y/N",
    field: "USE_YN",
    insertable: true,
    editable: true,
    align: "center",
    width: 70,
  },
  DAY_COLUMN("LBL_SUN", "SUNDAY"),
  DAY_COLUMN("LBL_MON", "MONDAY"),
  DAY_COLUMN("LBL_TUE", "TUESDAY"),
  DAY_COLUMN("LBL_WED", "WEDNESDAY"),
  DAY_COLUMN("LBL_THU", "THURSDAY"),
  DAY_COLUMN("LBL_FRI", "FRIDAY"),
  DAY_COLUMN("LBL_SAT", "SATURDAY"),
  {
    type: "text",
    headerName: "LBL_DIVISION_CODE",
    field: "DIV_CD",
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    hide: true,
  },
];
