// 배차상세정보 팝업 컬럼 정의 — DispatchDetailPop 에서 분리 (정적 컬럼 4벌 + 주문 탭).
//  헤더명(LBL 키)/필드/폭/정렬은 센차 DispatchDetailPop* 그리드 기준.

// ── 배차정보 컬럼 (센차 DispatchDetailPopDspchGrid 기준, headerName=LBL 키) ──
export const DSPCH_INFO_COLS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_BATCH",
    field: "BATCH_NO",
    align: "right",
    width: 40,
    hide: true,
  },
  {
    type: "numeric",
    headerName: "LBL_ROTATION",
    field: "RTN_NO",
    align: "right",
    width: 40,
  },
  {
    type: "combo",
    headerName: "LBL_OP_STATUS",
    field: "DSPCH_OP_STS",
    codeKey: "dspchOpSts",
    statusStyle: "DSPCH_OP_STS",
    align: "center",
    width: 80,
  },
  {
    type: "text",
    headerName: "LBL_TO_ADDRESS",
    field: "LOC_NM",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_UOM",
    field: "QTY",
    align: "left",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE",
    field: "PLN_LD_RT",
    align: "right",
    width: 80,
    decimalPlaces: 1,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_VOL_RT",
    field: "PLN_GRS_VOL_RT",
    align: "right",
    width: 80,
    decimalPlaces: 1,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_WGT_RT",
    field: "PLN_GRS_WGT_RT",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PLT_QTY_RT",
    field: "PLN_PLT_RT",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_RTNR_QTY_RT",
    field: "PLN_RTNR_RT",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PBOX_QTY_RT",
    field: "PLN_PBOX_RT",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_BOX_QTY_RT",
    field: "PLN_BOX_RT",
    align: "right",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_FLEX_QTY1_RT",
    field: "PLN_FLEX_QTY1_RT",
    align: "right",
    width: 80,
    decimalPlaces: 1,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_FLEX_QTY2_RT",
    field: "PLN_FLEX_QTY2_RT",
    align: "right",
    width: 80,
    decimalPlaces: 1,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_FLEX_QTY3_RT",
    field: "PLN_FLEX_QTY3_RT",
    align: "right",
    width: 80,
    decimalPlaces: 1,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_FLEX_QTY4_RT",
    field: "PLN_FLEX_QTY4_RT",
    align: "right",
    width: 80,
    decimalPlaces: 1,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_FLEX_QTY5_RT",
    field: "PLN_FLEX_QTY5_RT",
    align: "right",
    width: 80,
    decimalPlaces: 1,
    summaryType: "sum",
  },
  {
    type: "text",
    headerName: "LBL_TRIP_NO",
    field: "TRIP_ID",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_NO",
    field: "DSPCH_NO",
    align: "center",
  },
  {
    type: "check",
    headerName: "LBL_CONST_OVRD_YN",
    field: "CONSTRAINT_OVRD_YN",
    align: "center",
    width: 80,
    editable: true,
  },
  {
    type: "combo",
    headerName: "LBL_CONST_OVRD_RSN_CD",
    field: "CONSTRAINT_OVRD_RSN_CD",
    codeKey: "constraintOvrdCd",
    align: "left",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_TRIP_COUNT",
    field: "RTN_NO",
    colId: "RTN_NO_TRIP_COUNT",
    align: "center",
    width: 80,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "VEH_OP_TP",
    noLang: true,
    field: "VEH_OP_TP",
    hide: true,
  },
];

// ── 배송경로 컬럼 (센차 DispatchDetailPopRouteGrid 기준, headerName=LBL 키) ──
export const ROUTE_COLS = [
  {
    type: "text",
    headerName: "TTL_FI_DIST",
    noLang: true,
    field: "TTL_FI_DIST",
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_PLAN_TYPE",
    field: "DSPCH_TP",
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_NO",
    field: "DSPCH_NO",
    align: "right",
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_PLAN_ID",
    field: "PLN_ID",
    align: "right",
    hide: true,
  },
  {
    type: "numeric",
    headerName: "LBL_STOP_SEQUENCE",
    field: "STOP_SEQ",
    align: "right",
    width: 60,
  },
  {
    type: "text",
    headerName: "LBL_LOCATION_CODE",
    field: "LOC_CD",
    align: "center",
    width: 200,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_LOCATION_NAME",
    field: "LOC_NM",
    align: "left",
    width: 140,
  },
  {
    type: "combo",
    headerName: "LBL_PICKDROP_DIV",
    field: "STOP_TP",
    codeKey: "stopTp",
    align: "center",
    width: 60,
  },
  {
    type: "datetime",
    headerName: "LBL_ETA_DTTM",
    field: "ETA_DTTM",
    align: "center",
    width: 120,
  },
  {
    type: "datetime",
    headerName: "LBL_ATA_DTTM",
    field: "ATA_DTTM",
    align: "center",
    width: 120,
  },
  {
    type: "datetime",
    headerName: "LBL_ATD_DTTM",
    field: "ATD_DTTM",
    align: "center",
    width: 120,
  },
  {
    type: "datetime",
    headerName: "LBL_ATC_DTTM",
    field: "ATC_DTTM",
    align: "center",
    width: 120,
  },
  {
    type: "datetime",
    headerName: "LBL_ETD_DTTM",
    field: "ETD_DTTM",
    align: "center",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_TRNST_PREVSTOP_DIST",
    field: "TRNST_PREVSTOP_DIST",
    align: "right",
    summaryType: "sum",
  },
];

// ── 주문(할당/미할당) 컬럼 (센차 DispatchDetailPopAssignedShpm 기준) ──
export const ORDER_COLS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_BATCH_NO",
    field: "BATCH_NO",
    align: "center",
    width: 70,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_NAME",
    field: "FRM_LOC_NM",
    align: "left",
    width: 80,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_NAME",
    field: "TO_LOC_NM",
    align: "left",
    width: 80,
  },
  {
    type: "combo",
    headerName: "LBL_ORDER_TYPE",
    field: "ORD_TP",
    codeKey: "ordTp",
    align: "center",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_TEMP_TCD",
    field: "CMDT_CD",
    codeKey: "cmdtTp",
    align: "center",
    width: 70,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_VOL",
    field: "PLN_GRS_VOL",
    align: "right",
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_WGT",
    field: "PLN_GRS_WGT",
    align: "right",
    summaryType: "sum",
  },
  {
    type: "text",
    headerName: "LBL_ORDER_NO",
    field: "ORD_NO",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_ORDER_NO",
    field: "CUST_ORD_NO",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_CODE",
    field: "TO_LOC_CD",
    align: "center",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_COUNTRY_NAME",
    field: "TO_CTRY_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_STATE",
    field: "TO_STT_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_CITY",
    field: "TO_CTY_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_TO_DETAIL_ADDRESS_1",
    field: "TO_DTL_ADDR1",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_TO_DETAIL_ADDRESS_2",
    field: "TO_DTL_ADDR2",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_ZIP_CODE",
    field: "TO_ZIP_CD",
    align: "center",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PLT_QTY",
    field: "PLN_PLT_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_RTNR_QTY",
    field: "PLN_RTNR_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PBOX_QTY",
    field: "PLN_PBOX_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_BOX_QTY",
    field: "PLN_BOX_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY1",
    field: "PLN_FLEX_QTY1",
    align: "right",
    width: 80,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY2",
    field: "PLN_FLEX_QTY2",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY3",
    field: "PLN_FLEX_QTY3",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY4",
    field: "PLN_FLEX_QTY4",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY5",
    field: "PLN_FLEX_QTY5",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_QTY",
    field: "PLN_QTY",
    align: "right",
    summaryType: "sum",
  },
  {
    type: "text",
    headerName: "LBL_SHIPMENT_NUMBER",
    field: "SHPM_NO",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_MIT_CODE_NAME",
    field: "MIT_CLSS_CD",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_CODE",
    field: "CUST_CD",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_NAME",
    field: "CUST_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_CODE",
    field: "FRM_LOC_CD",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_COUNTRY_NAME",
    field: "FRM_CTRY_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_STATE",
    field: "FRM_STT_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_FROM_CITY_NM",
    field: "FRM_CTY_NM",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_FRM_DETAIL_ADDRESS_1",
    field: "FRM_DTL_ADDR1",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_FRM_DETAIL_ADDRESS_2",
    field: "FRM_DTL_ADDR2",
    align: "left",
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_ZIP_CODE",
    field: "FRM_ZIP_CD",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_SHPM_RMRK",
    field: "SHPM_RSN_DESC",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_SOLD_TO_CD",
    field: "SOLD_TO_CD",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_SOLD_TO_NM",
    field: "SOLD_TO_NM",
    align: "left",
    width: 160,
  },
  {
    type: "text",
    headerName: "LBL_CUST_PICKUP_YN",
    field: "CUST_PICKUP_YN",
    align: "center",
    width: 100,
  },
];

// ── 할당주문 품목 컬럼 (센차 DispatchDetailPopAssignedShpmDtl 기준) ──
export const ITEM_COLS = [
  { headerName: "No" },
  // hidden
  {
    type: "text",
    headerName: "ShipmentId",
    noLang: true,
    field: "SHPM_ID",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "LGST_GRP_CD",
    noLang: true,
    field: "LGST_GRP_CD",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "CustCd",
    noLang: true,
    field: "CUST_CD",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "ShipmentDetailCd",
    noLang: true,
    field: "SHPM_DTL_ID",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "OrderLineNumber",
    noLang: true,
    field: "ORD_LINE_NO",
    colId: "ORD_LINE_NO_HIDDEN",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "ItemSystemCd",
    noLang: true,
    field: "ITEM_SYS_CD",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "CmdtCd",
    noLang: true,
    field: "CMDT_CD",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "CUST_ORD_NO",
    noLang: true,
    field: "CUST_ORD_NO",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "SHPM_NO",
    noLang: true,
    field: "SHPM_NO",
    align: "center",
    width: 100,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_SHIPMENT_SPLIT_ALW_YN",
    field: "ALLOW_SHIPMENT_SPLIT",
    align: "center",
    width: 150,
    hide: true,
  },
  // 품목라인
  {
    type: "text",
    headerName: "LBL_ORD_ITM_LINE_NO",
    field: "ORD_LINE_NO",
    align: "left",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_CD",
    field: "CUST_ITEM_CD",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_NM",
    field: "CUST_ITEM_NM",
    align: "left",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_ORD_QTY",
    field: "PLN_ORD_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_PLN_ORD_QTY_UOM",
    field: "PLN_ORD_QTY_UOM",
    codeKey: "itmUom",
    align: "center",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_INV_QTY",
    field: "PLN_INV_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_PLN_INV_QTY_UOM",
    field: "PLN_INV_QTY_UOM",
    codeKey: "itmUom",
    align: "center",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_NET_WGT",
    field: "PLN_NET_WGT",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_WGT",
    field: "PLN_GRS_WGT",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PLT_QTY",
    field: "PLN_PLT_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_RTNR_QTY",
    field: "PLN_RTNR_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PBOX_QTY",
    field: "PLN_PBOX_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_BOX_QTY",
    field: "PLN_BOX_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY1",
    field: "PLN_FLEX_QTY1",
    align: "right",
    width: 80,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY2",
    field: "PLN_FLEX_QTY2",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY3",
    field: "PLN_FLEX_QTY3",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY4",
    field: "PLN_FLEX_QTY4",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY5",
    field: "PLN_FLEX_QTY5",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_ORD_QTY",
    field: "CFM_ORD_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_CFM_ORD_QTY_UOM",
    field: "CFM_ORD_QTY_UOM",
    codeKey: "itmUom",
    align: "left",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_INV_QTY",
    field: "CFM_INV_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_CFM_INV_QTY_UOM",
    field: "CFM_INV_QTY_UOM",
    codeKey: "itmUom",
    align: "left",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_NET_WGT",
    field: "CFM_NET_WGT",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_GRS_WGT",
    field: "CFM_GRS_WGT",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_PLT_QTY",
    field: "CFM_PLT_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_RTNR_QTY",
    field: "CFM_RTNR_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_PBOX_QTY",
    field: "CFM_PBOX_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CFM_BOX_QTY",
    field: "CFM_BOX_QTY",
    align: "right",
    width: 100,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY1",
    field: "CFM_FLEX_QTY1",
    align: "right",
    width: 80,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY2",
    field: "CFM_FLEX_QTY2",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY3",
    field: "CFM_FLEX_QTY3",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY4",
    field: "CFM_FLEX_QTY4",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY5",
    field: "CFM_FLEX_QTY5",
    align: "right",
    width: 90,
    summaryType: "sum",
  },
  {
    type: "text",
    headerName: "LBL_ITEM_REMARK",
    field: "SHPM_DTL_RSN_DESC",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_FEED_FCD",
    field: "ITEM_FCD",
    align: "left",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_TEMPER_ZONE",
    field: "TEMP_TCD",
    align: "left",
    width: 80,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_DATE",
    field: "CRE_DTTM",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_INSERT_PERSON_ID",
    field: "CRE_USR_ID",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_TIME",
    field: "UPD_DTTM",
    align: "center",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_UPDATE_PERSON_ID",
    field: "UPD_USR_ID",
    align: "center",
    width: 150,
  },
];

// 주문 그리드 탭 — 할당/미할당
export const ORDER_TABS = [
  { key: "ALLOC", label: "LBL_ASSIGNED_SHIPMENTS" },
  { key: "UNALLOC", label: "LBL_UNASSIGNED_SHIPMENTS" },
];
