// 그리드 컬럼 정의 (서버 IfVehicleDspchMain 기준) — 읽기전용 조회 화면, audit 컬럼 제외.

export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "datetime", headerName: "LBL_SEND_DATE", field: "CRE_DTTM", align: "center", width: 150 },
  { type: "text", headerName: "LBL_USR_RE_PRCS_YN", field: "RE_PRCS_BY_USR_YN", align: "center", width: 110 },
  { type: "text", headerName: "LBL_INTERFAE_ID", field: "IF_ID", align: "center", width: 130 },
  { type: "combo", headerName: "LBL_INTERFACE_TCD", field: "IF_TCD", codeKey: "interfaceType", align: "center", width: 100 },
  { type: "combo", headerName: "LBL_PRCS_STS", field: "IF_PRCS_STS", codeKey: "interfaceStatus", align: "center", width: 70 },
  { type: "text", headerName: "LBL_PRCS_MSG", field: "IF_PRCS_MSG_DESC", width: 200 },
  { type: "combo", headerName: "LBL_IF_PRCS_MSG_CD", field: "IF_PRCS_MSG_CD", codeKey: "ifPrcsMsgCd", align: "left", width: 150 },
  { type: "text", headerName: "LBL_DIVISION_CODE", field: "DIV_CD", align: "center" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD", align: "center" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_NAME", field: "LGST_GRP_CD", align: "center" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO", align: "center" },
  { type: "text", headerName: "LBL_SOLD_TO_CD", field: "SOLD_TO_CD", align: "center", width: 80 },
  { type: "text", headerName: "LBL_SOLD_TO_NM", field: "SOLD_TO_NM", align: "left", width: 80 },
  { type: "date", headerName: "LBL_DSPCH_DLVRY_DT", field: "DLVRY_DT", align: "center" },
  { type: "text", headerName: "LBL_VEHICLE_NUMBER", field: "VEH_NO", align: "center" },
  { type: "text", headerName: "LBL_DRIVER_TEL", field: "MBL_PHN_NO", align: "center" },
  { type: "datetime", headerName: "LBL_ATD_TIME", field: "ATD_DTTM", align: "center" },
  { type: "text", headerName: "LBL_TMS_IF_PRCS_ID", field: "TMS_IF_PRCS_ID", align: "center", width: 150 },
  { type: "datetime", headerName: "LBL_TMS_IF_PRCS_START_DTTM", field: "TMS_IF_PRCS_START_DTTM", align: "center", width: 200 },
  { type: "datetime", headerName: "LBL_TMS_IF_PRCS_END_DTTM", field: "TMS_IF_PRCS_END_DTTM", align: "center", width: 200 },
];
