export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_SHIPMENT_NUMBER",
    field: "SHPM_NO",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_ORD_DO",
    field: "ORD_NO",
    align: "left",
    width: 120,
  },
  {
    type: "date",
    headerName: "LBL_REQUESTED_DELIVERY_DATE",
    field: "DLVRY_DT",
    align: "center",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_ORDER_TYPE",
    field: "ORD_TP",
    codeKey: "ordType",
    align: "left",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_SHIPMENT_TYPE",
    field: "SHPM_TP",
    codeKey: "shipmentType",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_CODE",
    field: "FRM_LOC_CD",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_NAME",
    field: "FRM_LOC_NM",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_ADDRESS",
    field: "FRM_DTL_ADDR1",
    align: "left",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_CD",
    field: "TO_LOC_CD",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_NM",
    field: "TO_LOC_NM",
    align: "left",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DESTINATION_ADDRESS",
    field: "TO_DTL_ADDR1",
    align: "left",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_SOLD_TO",
    field: "SOLD_TO_CD",
    align: "left",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_SOLD_TO_NAME",
    field: "SOLD_TO_NM",
    align: "left",
    width: 120,
  },
  {
    type: "combo",
    headerName: "LBL_DLVRY_TP",
    field: "DLVRY_TP",
    codeKey: "dlvryType",
    align: "center",
    width: 120,
  },
  {
    type: "combo",
    headerName: "LBL_PLN_ORD_QTY_UOM",
    field: "PLN_ORD_QTY_UOM",
    codeKey: "itmUomList",
    align: "center",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_ORD_QTY",
    field: "PLN_ORD_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_PLN_INV_QTY_UOM",
    field: "PLN_INV_QTY_UOM",
    codeKey: "itmUomList",
    align: "center",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_INV_QTY",
    field: "PLN_INV_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_NET_VOL",
    field: "PLN_NET_VOL",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_VOL",
    field: "PLN_GRS_VOL",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_NET_WGT",
    field: "PLN_NET_WGT",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_GRS_WGT",
    field: "PLN_GRS_WGT",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PLT_QTY",
    field: "PLN_PLT_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_RTNR_QTY",
    field: "PLN_RTNR_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_PBOX_QTY",
    field: "PLN_PBOX_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLN_BOX_QTY",
    field: "PLN_BOX_QTY",
    align: "right",
    width: 100,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY1",
    field: "PLN_FLEX_QTY1",
    align: "right",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY2",
    field: "PLN_FLEX_QTY2",
    align: "right",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY3",
    field: "PLN_FLEX_QTY3",
    align: "right",
    width: 120,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY4",
    field: "PLN_FLEX_QTY4",
    align: "right",
    width: 150,
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY5",
    field: "PLN_FLEX_QTY5",
    align: "right",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DIVISION_CODE",
    field: "DIV_CD",
    align: "center",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_DIVISION_NAME",
    field: "DIV_NM",
    align: "left",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    align: "center",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_NAME",
    field: "LGST_GRP_NM",
    align: "left",
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_COMPANY_CD",
    field: "CUST_CD",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_BIZUNIT_GCD",
    field: "SALES_ORG_CD",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_PLANT_CD",
    field: "FRM_PLANT_CD",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_SLOC_CD",
    field: "FRM_SLOC_CD",
    align: "center",
    width: 100,
  },
  {
    type: "combo",
    headerName: "LBL_ORD_CRE_FLAG",
    field: "ORD_PRCS_TCD",
    codeKey: "ordCreFleg",
    align: "center",
    width: 120,
  },
  {
    type: "text",
    headerName: "LBL_COST_DISTR_FLAG",
    field: "AP_ALLOC_REQ_YN",
    align: "center",
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_RCV_DSPCH_NO",
    field: "DSPCH_NO",
    align: "center",
    width: 100,
  },
];
