import { makeAuditColumns } from "@/app/components/grid/commonColumns";
import { numberValueFormatter } from "@/app/components/grid/commonFormatters";

// 메인 배차 그리드 (DepartArrivalManagementMainGrid)
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { headerName: "LBL_REQUESTED_DELIVERY_DATE", field: "DLVRY_DT" },
  { headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  {
    headerName: "LBL_DISPATCH_OPERATIONAL_STATUS",
    field: "DSPCH_OP_STS",
    codeKey: "dspchOpStsList",
  },
  { headerName: "LBL_CARRIER_CODE", field: "CARR_CD" },
  { headerName: "LBL_CARRIER_NAME", field: "CARR_NM" },
  { headerName: "LBL_LANE", field: "LOC_NM" },
  {
    headerName: "LBL_CFM_NET_WGT",
    field: "CFM_NET_WGT",
  },
  { headerName: "LBL_DLVRY_STT_DTTM", field: "DLVRY_START_DTTM" },
  { headerName: "LBL_DLVRY_STT_USR_ID", field: "DLVRY_START_USR_ID" },
  { headerName: "LBL_DLVRY_END_DTTM", field: "DLVRY_END_DTTM" },
  { headerName: "LBL_DLVRY_END_USR_ID", field: "DLVRY_END_USR_ID" },
  { headerName: "LBL_FORCED_DSPCH", field: "FORCED_BY_DSPCH" },
  { headerName: "LBL_ROTATION", field: "RTN_NO" },
  { headerName: "LBL_VEH_NO", field: "VEH_NO" },
  { headerName: "LBL_DRIVER_NAME", field: "DRVR_NM" },
  { headerName: "LBL_VEHICLE_TYPE_NAME", field: "VEH_TP_NM" },
  {
    headerName: "LBL_VEHICLE_OPERATION_TYPE",
    field: "VEH_OP_TP",
    codeKey: "vehOpType",
  },
  {
    headerName: "LBL_DISPATCH_PLAN_TYPE",
    field: "DSPCH_TP",
    codeKey: "dspchTpList",
  },
  { headerName: "LBL_MEMO", field: "MEMO_DESC" },
  { headerName: "LBL_PLAN_ID", field: "PLN_ID" },
  { headerName: "LBL_PLAN_NAME", field: "PLN_NM" },
  { headerName: "LBL_REFERENCE1", field: "REF_VAL_1" },
  { headerName: "LBL_REFERENCE2", field: "REF_VAL_2" },
  { headerName: "LBL_REFERENCE3", field: "REF_VAL_3" },
  { headerName: "LBL_REFERENCE4", field: "REF_VAL_4" },
  { headerName: "LBL_REFERENCE5", field: "REF_VAL_5" },
  { headerName: "LBL_REFERENCE6", field: "REF_VAL_6" },
  { headerName: "LBL_REFERENCE7", field: "REF_VAL_7" },
  { headerName: "LBL_REFERENCE8", field: "REF_VAL_8" },
  { headerName: "LBL_REFERENCE9", field: "REF_VAL_9" },
  { headerName: "LBL_REFERENCE10", field: "REF_VAL_10" },
  { headerName: "LBL_REFERENCE11", field: "REF_VAL_11" },
  { headerName: "LBL_REFERENCE12", field: "REF_VAL_12" },
  ...makeAuditColumns({
    rowStatus: true,
    insertPerson: true,
    insertDate: true,
    updatePerson: true,
    updateTime: true,
  }),
];

// 경유처 (DepartArrivalManagementSubGrid01)
export const STOPOVER_COLUMN_DEFS = [
  { headerName: "No" },
  { headerName: "LBL_STOP_SEQUENCE", field: "STOP_SEQ" },
  { headerName: "LBL_ACTUAL_STOP_SEQUENCE", field: "ACTUAL_STOP_SEQ" },
  {
    headerName: "LBL_PICKDROP_DIV",
    field: "STOP_TP",
    codeKey: "stopTpList",
  },
  { headerName: "LBL_DESTINATION_CODE", field: "LOC_CD" },
  { headerName: "LBL_LOCATION_NAME", field: "LOC_NM" },
  { headerName: "LBL_ETA_DTTM", field: "ETA_DTTM" },
  { headerName: "LBL_ATA_DTTM", field: "ATA_DTTM" },
  { headerName: "LBL_ATD_DTTM", field: "ATD_DTTM" },
  {
    headerName: "LBL_ARRIVAL_REGISTRATION_MODE",
    field: "PICK_REG_DIV",
    codeKey: "depArrRegDivList",
  },
  { headerName: "LBL_ARRIVAL_REGISTER", field: "PICK_REG_USER" },
  {
    headerName: "LBL_DEPARTURE_REGISTRATION_MODE",
    field: "DROP_REG_DIV",
    codeKey: "depArrRegDivList",
  },
  { headerName: "LBL_DEPARTURE_REGISTER", field: "DROP_REG_USER" },
  { headerName: "LBL_FEED_MOVE", field: "FEED_MOVE_CNT" },
  { headerName: "LBL_SERVICE_ACTIVITY", field: "SRVC_ATVT_YN" },
  {
    headerName: "LBL_TRNST_PREVSTOP_DIST",
    field: "TRNST_PREVSTOP_DIST",
  },
  { headerName: "LBL_DETAIL_ADDRESS", field: "DTL_ADDR1" },
  { headerName: "LBL_LATITUDE", field: "LAT" },
  { headerName: "LBL_LONGITUDE", field: "LON" },
  { headerName: "LBL_STATE", field: "STT_NM" },
  { headerName: "LBL_CITY_NAME", field: "CTY_NM" },
  { headerName: "LBL_ETD_DTTM", field: "ETD_DTTM" },
  ...makeAuditColumns({
    rowStatus: true,
    insertPerson: true,
    insertDate: true,
    updatePerson: true,
    updateTime: true,
  }),
];

// 할당주문 (DepartArrivalManagementSubGrid02)
export const ASSIGNED_ORDER_COLUMN_DEFS = [
  { headerName: "No" },
  { headerName: "LBL_DEPARTURE_NAME", field: "FRM_LOC_NM" },
  { headerName: "LBL_DESTINATION_NAME", field: "TO_LOC_NM" },
  { headerName: "LBL_TO_DETAIL_ADDRESS_1", field: "TO_DTL_ADDR1" },
  { headerName: "LBL_DESTINATION_ZIP_CODE", field: "TO_ZIP_CD" },
  { headerName: "LBL_ORDER_TYPE", field: "ORD_TP", codeKey: "ordTpList" },
  { headerName: "LBL_ITEM_UOM", field: "QTY" },
  {
    headerName: "LBL_PLN_NET_VOL",
    field: "PLN_NET_VOL",
  },
  {
    headerName: "LBL_PLN_GRS_VOL",
    field: "PLN_GRS_VOL",
  },
  {
    headerName: "LBL_PLN_NET_WGT",
    field: "PLN_NET_WGT",
  },
  {
    headerName: "LBL_PLN_GRS_WGT",
    field: "PLN_GRS_WGT",
  },
  { headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY" },
  { headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY" },
  { headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY" },
  { headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY" },
  { headerName: "LBL_CFM_ORD_QTY", field: "CFM_ORD_QTY" },
  {
    headerName: "LBL_CFM_ORD_QTY_UOM",
    field: "CFM_ORD_QTY_UOM",
    codeKey: "itmUomList",
  },
  { headerName: "LBL_CFM_INV_QTY", field: "CFM_INV_QTY" },
  {
    headerName: "LBL_CFM_INV_QTY_UOM",
    field: "CFM_INV_QTY_UOM",
    codeKey: "itmUomList",
  },
  {
    headerName: "LBL_CFM_NET_WGT",
    field: "CFM_NET_WGT",
  },
  {
    headerName: "LBL_CFM_GRS_WGT",
    field: "CFM_GRS_WGT",
  },
  { headerName: "LBL_CFM_PLT_QTY", field: "CFM_PLT_QTY" },
  { headerName: "LBL_CFM_RTNR_QTY", field: "CFM_RTNR_QTY" },
  { headerName: "LBL_CFM_PBOX_QTY", field: "CFM_PBOX_QTY" },
  { headerName: "LBL_CFM_BOX_QTY", field: "CFM_BOX_QTY" },
  { headerName: "LBL_CUSTOMER_ORDER_NO", field: "CUST_ORD_NO" },
  { headerName: "LBL_ORDER_NO", field: "ORD_NO" },
  { headerName: "LBL_SHIPMENT_NUMBER", field: "SHPM_NO" },
  { headerName: "LBL_DESTINATION_CODE", field: "TO_LOC_CD" },
  { headerName: "LBL_DEPARTURE_CODE", field: "FRM_LOC_CD" },
  { headerName: "LBL_FRM_DETAIL_ADDRESS_1", field: "FRM_DTL_ADDR1" },
  { headerName: "LBL_DEPARTURE_ZIP_CODE", field: "FRM_ZIP_CD" },
  { headerName: "LBL_SHPM_RMRK", field: "SHPM_RSN_DESC" },
  { headerName: "LBL_SOLD_TO_CD", field: "SOLD_TO_CD" },
  { headerName: "LBL_SOLD_TO_NM", field: "SOLD_TO_NM" },
  { headerName: "LBL_CUST_PICKUP_YN", field: "CUST_PICKUP_YN" },
];
