import { makeAuditColumns } from "@/app/components/grid/columns/commonColumns";
import { Lang } from "@/app/services/common/Lang";

const referenceHeader = (index: number) => `${Lang.get("LBL_REFERENCE")}${index}`;

// 메인 배차 그리드 (DepartArrivalManagementMainGrid)
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_REQUESTED_DELIVERY_DATE", field: "DLVRY_DT" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  {
    type: "text",
    headerName: "LBL_DISPATCH_OPERATIONAL_STATUS",
    field: "DSPCH_OP_STS",
    codeKey: "dspchOpStsList",
    statusStyle: "DSPCH_OP_STS",
  },
  { type: "text", headerName: "LBL_CARRIER_CODE", field: "CARR_CD" },
  { type: "text", headerName: "LBL_CARRIER_NAME", field: "CARR_NM" },
  { type: "text", headerName: "LBL_LANE", field: "LOC_NM" },
  {
    type: "text",
    headerName: "LBL_CFM_NET_WGT",
    field: "CFM_NET_WGT",
  },
  { type: "text", headerName: "LBL_DLVRY_STT_DTTM", field: "DLVRY_START_DTTM" },
  { type: "text", headerName: "LBL_DLVRY_STT_USR_ID", field: "DLVRY_START_USR_ID" },
  { type: "text", headerName: "LBL_DLVRY_END_DTTM", field: "DLVRY_END_DTTM" },
  { type: "text", headerName: "LBL_DLVRY_END_USR_ID", field: "DLVRY_END_USR_ID" },
  { type: "text", headerName: "LBL_FORCED_DSPCH", field: "FORCED_BY_DSPCH" },
  { type: "text", headerName: "LBL_ROTATION", field: "RTN_NO" },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO" },
  { type: "text", headerName: "LBL_DRIVER_NAME", field: "DRVR_NM" },
  { type: "text", headerName: "LBL_VEHICLE_TYPE_NAME", field: "VEH_TP_NM" },
  {
    type: "text",
    headerName: "LBL_VEHICLE_OPERATION_TYPE",
    field: "VEH_OP_TP",
    codeKey: "vehOpType",
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_PLAN_TYPE",
    field: "DSPCH_TP",
    codeKey: "dspchTpList",
  },
  { type: "text", headerName: "LBL_MEMO", field: "MEMO_DESC", editable: true },
  { type: "text", headerName: "LBL_PLAN_ID", field: "PLN_ID" },
  { type: "text", headerName: "LBL_PLAN_NAME", field: "PLN_NM" },
  { type: "text", headerName: referenceHeader(1), field: "REF_VAL_1", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(2), field: "REF_VAL_2", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(3), field: "REF_VAL_3", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(4), field: "REF_VAL_4", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(5), field: "REF_VAL_5", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(6), field: "REF_VAL_6", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(7), field: "REF_VAL_7", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(8), field: "REF_VAL_8", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(9), field: "REF_VAL_9", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(10), field: "REF_VAL_10", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(11), field: "REF_VAL_11", editable: true, noLang: true },
  { type: "text", headerName: referenceHeader(12), field: "REF_VAL_12", editable: true, noLang: true },
  ...makeAuditColumns({
    rowStatus: true,
    insertPerson: true,
    insertDate: true,
    updatePerson: true,
    updateTime: true,
  }),
];

// 경유처 (DepartArrivalManagementSubGrid01)
export const STOPOVER_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "numeric", headerName: "LBL_STOP_SEQUENCE", field: "STOP_SEQ" },
  { type: "numeric", headerName: "LBL_ACTUAL_STOP_SEQUENCE", field: "ACTUAL_STOP_SEQ" },
  {
    type: "combo",
    headerName: "LBL_PICKDROP_DIV",
    field: "STOP_TP",
    codeKey: "stopTpList",
    insertable: true,
  },
  { type: "text", headerName: "LBL_LOCATION_ID", field: "LOC_ID", hide: true },
  { type: "text", headerName: "LBL_DESTINATION_CODE", field: "LOC_CD" },
  { type: "text", headerName: "LBL_LOCATION_NAME", field: "LOC_NM" },
  { type: "datetime", headerName: "LBL_ETA_DTTM", field: "ETA_DTTM", editable: false, insertable: false },
  { type: "datetime", headerName: "LBL_ATA_DTTM", field: "ATA_DTTM", editable: true },
  { type: "datetime", headerName: "LBL_ATD_DTTM", field: "ATD_DTTM", editable: true },
  {
    type: "text",
    headerName: "LBL_ARRIVAL_REGISTRATION_MODE",
    field: "PICK_REG_DIV",
    codeKey: "depArrRegDivList",
  },
  { type: "text", headerName: "LBL_ARRIVAL_REGISTER", field: "PICK_REG_USER" },
  {
    type: "text",
    headerName: "LBL_DEPARTURE_REGISTRATION_MODE",
    field: "DROP_REG_DIV",
    codeKey: "depArrRegDivList",
  },
  { type: "text", headerName: "LBL_DEPARTURE_REGISTER", field: "DROP_REG_USER" },
  {
    type: "text",
    headerName: "LBL_SERVICE_ACTIVITY",
    field: "SRVC_ATVT_YN",
    cellRenderer: (params: any) => {
      if (params.node?.rowPinned) return "";
      const isClickable = String(params.data?.STOP_TP ?? "") !== "99";
      return (
        <span
          className={
            isClickable
              ? "cursor-pointer text-blue-600 underline underline-offset-2"
              : undefined
          }
        >
          {params.value === "Y" ? "예" : "아니오"}
        </span>
      );
    },
  },
  {
    type: "numeric",
    headerName: "LBL_TRNST_PREVSTOP_DIST",
    field: "TRNST_PREVSTOP_DIST",
    summaryType: "sum",
  },
  { type: "text", headerName: "LBL_DETAIL_ADDRESS", field: "DTL_ADDR1" },
  { type: "numeric", headerName: "LBL_LATITUDE", field: "LAT" },
  { type: "numeric", headerName: "LBL_LONGITUDE", field: "LON" },
  { type: "text", headerName: "LBL_STATE_CODE", field: "STT_CD", hide: true },
  { type: "text", headerName: "LBL_STATE", field: "STT_NM" },
  { type: "text", headerName: "LBL_CITY_CODE", field: "CTY_CD", hide: true },
  { type: "text", headerName: "LBL_CITY_NAME", field: "CTY_NM" },
  { type: "datetime", headerName: "LBL_ETD_DTTM", field: "ETD_DTTM", editable: false, insertable: false },
  ...makeAuditColumns({
    rowStatus: true,
    insertPerson: true,
    insertDate: true,
    updatePerson: true,
    updateTime: true,
  }),
];

// 할당주문 (DepartArrivalManagementSubGrid02)
export const ASSIGNED_ORDER_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "SHPM_OP_STS", field: "SHPM_OP_STS", hide: true, noLang: true },
  { type: "text", headerName: "SHPM_TP", field: "SHPM_TP", hide: true, noLang: true },
  { type: "text", headerName: "DSPCH_NO", field: "DSPCH_NO", hide: true, noLang: true },
  { type: "text", headerName: "PLN_ID", field: "PLN_ID", hide: true, noLang: true },
  { type: "text", headerName: "SHPM_ID", field: "SHPM_ID", hide: true, noLang: true },
  { type: "text", headerName: "FRM_STOP_ID", field: "FRM_STOP_ID", hide: true, noLang: true },
  { type: "text", headerName: "TO_STOP_ID", field: "TO_STOP_ID", hide: true, noLang: true },
  { type: "text", headerName: "TO_LOC_ID", field: "TO_LOC_ID", hide: true, noLang: true },
  { type: "text", headerName: "FRM_LOC_ID", field: "FRM_LOC_ID", hide: true, noLang: true },
  { type: "text", headerName: "LBL_DEPARTURE_NAME", field: "FRM_LOC_NM" },
  { type: "text", headerName: "LBL_DESTINATION_NAME", field: "TO_LOC_NM" },
  { type: "text", headerName: "LBL_TO_DETAIL_ADDRESS_1", field: "TO_DTL_ADDR1" },
  { type: "text", headerName: "LBL_DESTINATION_ZIP_CODE", field: "TO_ZIP_CD" },
  { type: "text", headerName: "LBL_ORDER_TYPE", field: "ORD_TP", codeKey: "ordTpList" },
  { type: "text", headerName: "LBL_ITEM_UOM", field: "QTY" },
  {
    type: "text",
    headerName: "LBL_PLN_NET_VOL",
    field: "PLN_NET_VOL",
  },
  {
    type: "text",
    headerName: "LBL_PLN_GRS_VOL",
    field: "PLN_GRS_VOL",
  },
  {
    type: "text",
    headerName: "LBL_PLN_NET_WGT",
    field: "PLN_NET_WGT",
  },
  {
    type: "text",
    headerName: "LBL_PLN_GRS_WGT",
    field: "PLN_GRS_WGT",
  },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY1", field: "PLN_FLEX_QTY1", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY2", field: "PLN_FLEX_QTY2", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY3", field: "PLN_FLEX_QTY3", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY4", field: "PLN_FLEX_QTY4", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY5", field: "PLN_FLEX_QTY5", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_ORD_QTY", field: "CFM_ORD_QTY" },
  {
    type: "text",
    headerName: "LBL_CFM_ORD_QTY_UOM",
    field: "CFM_ORD_QTY_UOM",
    codeKey: "itmUomList",
  },
  { type: "numeric", headerName: "LBL_CFM_INV_QTY", field: "CFM_INV_QTY" },
  {
    type: "text",
    headerName: "LBL_CFM_INV_QTY_UOM",
    field: "CFM_INV_QTY_UOM",
    codeKey: "itmUomList",
  },
  {
    type: "text",
    headerName: "LBL_CFM_NET_WGT",
    field: "CFM_NET_WGT",
  },
  {
    type: "text",
    headerName: "LBL_CFM_GRS_WGT",
    field: "CFM_GRS_WGT",
  },
  { type: "numeric", headerName: "LBL_CFM_PLT_QTY", field: "CFM_PLT_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_RTNR_QTY", field: "CFM_RTNR_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_PBOX_QTY", field: "CFM_PBOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_BOX_QTY", field: "CFM_BOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY1", field: "CFM_FLEX_QTY1", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY2", field: "CFM_FLEX_QTY2", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY3", field: "CFM_FLEX_QTY3", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY4", field: "CFM_FLEX_QTY4", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY5", field: "CFM_FLEX_QTY5", summaryType: "sum", decimalPlaces: 4 },
  { type: "text", headerName: "LBL_CUSTOMER_ORDER_NO", field: "CUST_ORD_NO" },
  { type: "text", headerName: "LBL_ORDER_NO", field: "ORD_NO" },
  { type: "text", headerName: "LBL_SHIPMENT_NUMBER", field: "SHPM_NO" },
  { type: "text", headerName: "LBL_DESTINATION_CODE", field: "TO_LOC_CD" },
  { type: "text", headerName: "LBL_DEPARTURE_CODE", field: "FRM_LOC_CD" },
  { type: "text", headerName: "LBL_FRM_DETAIL_ADDRESS_1", field: "FRM_DTL_ADDR1" },
  { type: "text", headerName: "LBL_DEPARTURE_ZIP_CODE", field: "FRM_ZIP_CD" },
  { type: "text", headerName: "LBL_SHPM_RMRK", field: "SHPM_RSN_DESC" },
  { type: "text", headerName: "LBL_SOLD_TO_CD", field: "SOLD_TO_CD" },
  { type: "text", headerName: "LBL_SOLD_TO_NM", field: "SOLD_TO_NM" },
  { type: "text", headerName: "LBL_CUST_PICKUP_YN", field: "CUST_PICKUP_YN" },
];

// 할당주문 품목상세 (DepartArrivalManagementSubGrid03)
export const SHIPMENT_DETAIL_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "ShipmentId", field: "SHPM_ID", hide: true, noLang: true },
  { type: "text", headerName: "LGST_GRP_CD", field: "LGST_GRP_CD", hide: true, noLang: true },
  { type: "text", headerName: "CustCd", field: "CUST_CD", hide: true, noLang: true },
  { type: "text", headerName: "ShipmentDetailCd", field: "SHPM_DTL_ID", hide: true, noLang: true },
  { type: "text", headerName: "OrderLineNumber", field: "ORD_LINE_NO", colId: "HIDDEN_ORD_LINE_NO", hide: true, noLang: true },
  { type: "text", headerName: "ItemSystemCd", field: "ITEM_SYS_CD", hide: true, noLang: true },
  { type: "text", headerName: "CmdtCd", field: "CMDT_CD", hide: true, noLang: true },
  { type: "text", headerName: "CUST_ORD_NO", field: "CUST_ORD_NO", hide: true, noLang: true },
  { type: "text", headerName: "SHPM_NO", field: "SHPM_NO", hide: true, noLang: true },
  { type: "text", headerName: "LBL_SHIPMENT_SPLIT_ALW_YN", field: "ALLOW_SHIPMENT_SPLIT", hide: true },
  { type: "text", headerName: "LBL_ORD_ITM_LINE_NO", field: "ORD_LINE_NO" },
  { type: "text", headerName: "LBL_ITEM_CD", field: "CUST_ITEM_CD", align: "center" },
  { type: "text", headerName: "LBL_ITEM_NM", field: "CUST_ITEM_NM", align: "left" },
  { type: "numeric", headerName: "LBL_PLN_ORD_QTY", field: "PLN_ORD_QTY" },
  { type: "text", headerName: "LBL_PLN_ORD_QTY_UOM", field: "PLN_ORD_QTY_UOM", codeKey: "itmUomList" },
  { type: "numeric", headerName: "LBL_PLN_INV_QTY", field: "PLN_INV_QTY" },
  { type: "text", headerName: "LBL_PLN_INV_QTY_UOM", field: "PLN_INV_QTY_UOM", codeKey: "itmUomList" },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL", field: "PLN_NET_VOL", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_GRS_VOL", field: "PLN_GRS_VOL", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_NET_WGT", field: "PLN_NET_WGT", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_GRS_WGT", field: "PLN_GRS_WGT", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY1", field: "PLN_FLEX_QTY1", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY2", field: "PLN_FLEX_QTY2", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY3", field: "PLN_FLEX_QTY3", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY4", field: "PLN_FLEX_QTY4", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY5", field: "PLN_FLEX_QTY5", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_ORD_QTY", field: "CFM_ORD_QTY" },
  { type: "text", headerName: "LBL_CFM_ORD_QTY_UOM", field: "CFM_ORD_QTY_UOM", codeKey: "itmUomList" },
  { type: "numeric", headerName: "LBL_CFM_INV_QTY", field: "CFM_INV_QTY" },
  { type: "text", headerName: "LBL_CFM_INV_QTY_UOM", field: "CFM_INV_QTY_UOM", codeKey: "itmUomList" },
  { type: "numeric", headerName: "LBL_CFM_NET_VOL", field: "CFM_NET_VOL", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_GRS_VOL", field: "CFM_GRS_VOL", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_NET_WGT", field: "CFM_NET_WGT", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_GRS_WGT", field: "CFM_GRS_WGT", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_PLT_QTY", field: "CFM_PLT_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_RTNR_QTY", field: "CFM_RTNR_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_PBOX_QTY", field: "CFM_PBOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CFM_BOX_QTY", field: "CFM_BOX_QTY", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY1", field: "CFM_FLEX_QTY1", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY2", field: "CFM_FLEX_QTY2", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY3", field: "CFM_FLEX_QTY3", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY4", field: "CFM_FLEX_QTY4", summaryType: "sum", decimalPlaces: 4 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY5", field: "CFM_FLEX_QTY5", summaryType: "sum", decimalPlaces: 4 },
  { type: "text", headerName: "LBL_ITEM_REMARK", field: "SHPM_DTL_RSN_DESC" },
  { type: "text", headerName: "LBL_TEMPER_ZONE", field: "TEMP_TCD", codeKey: "vehTempTcd" },
  ...makeAuditColumns({
    rowStatus: true,
    insertDate: true,
    insertPerson: true,
    updateTime: true,
    updatePerson: true,
  }),
];
