// 그리드 컬럼 정의 (서버 ContractMain / ContractSub01 / ContractSub02 기준)
// audit 컬럼(등록자/등록일시/수정자/수정일시)·삭제·상태는 DataGrid 가 자동 추가(model.bind).

// ── 메인: 고객사 ───────────────────────────────────────────────
export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    // 고객사코드 (PK) — 추가행만 입력, 기존행 잠금. 영숫자/언더스코어만.
    type: "text",
    headerName: "LBL_CUSTOMER_CODE",
    field: "CUST_CD",
    isPrimaryKey: true,
    insertable: true,
    align: "center",
    locked: true,
    width: 150,
    regex: /^[a-zA-Z0-9_]+$/,
    validators: {
      required: true,
      max: 60,
      regex: /^[a-zA-Z0-9_]+$/,
    },
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_NAME",
    field: "CUST_NM",
    locked: true,
    editable: true,
    insertable: true,
    width: 150,
    validators: { required: true, max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_CUST_GRP_CD",
    field: "CUST_GRP_CD",
    locked: true,
    editable: true,
    insertable: true,
    width: 150,
    validators: { required: true, max: 60 },
  },
  {
    type: "text",
    headerName: "LBL_REPRESENTITIVE",
    field: "REP_NM",
    editable: true,
    insertable: true,
    width: 150,
    validators: { max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_REPRESENTATIVE_TEL",
    field: "REP_CNTC_NO",
    editable: true,
    insertable: true,
    width: 150,
    validators: { max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_PIC",
    field: "CUST_PIC_NM",
    editable: true,
    insertable: true,
    width: 150,
    validators: { max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_PIC_TEL_NO",
    field: "CUST_PIC_TEL_NO",
    editable: true,
    insertable: true,
    width: 150,
    validators: { max: 60 },
  },
  {
    type: "text",
    headerName: "LBL_PIC_HP_NO",
    field: "CUST_PIC_MBL_NO",
    editable: true,
    insertable: true,
    width: 150,
    validators: { max: 60 },
  },
  {
    type: "text",
    headerName: "LBL_EMAIL",
    field: "CUST_PIC_EMAIL_ADDR",
    align: "center",
    width: 100,
    hide: true,
    editable: true,
    insertable: true,
    validators: { min: 1, max: 50 },
  },
  {
    // 주소찾기 — 선택 시 CTRY/STT/CTY/ZIP/DTL_ADDR1·2 다중 write-back.
    type: "address",
    headerName: "LBL_FIND_ADDRESS",
    colId: "ADDR_SEARCH",
    align: "center",
    insertable: true,
    editable: true,
    width: 100,
  },
  {
    type: "text",
    headerName: "LBL_COUNTRY_CODE",
    field: "CTRY_CD",
    align: "center",
    width: 150,
    validators: { max: 2 },
  },
  {
    type: "text",
    headerName: "LBL_COUNTRY_NAME",
    field: "CTRY_NM",
    width: 150,
    validators: { required: true, max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_STATE_CODE",
    field: "STT_CD",
    align: "center",
    width: 150,
    validators: { required: true, max: 20 },
  },
  {
    type: "text",
    headerName: "LBL_STATE_NAME",
    field: "STT_NM",
    width: 150,
    validators: { required: true, max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_CITY_CODE",
    field: "CTY_CD",
    align: "center",
    width: 150,
    validators: { required: true, max: 20 },
  },
  {
    type: "text",
    headerName: "LBL_CITY_NAME",
    field: "CTY_NM",
    width: 150,
    validators: { required: true, max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_ADDR",
    field: "DTL_ADDR1",
    editable: true,
    insertable: true,
    width: 150,
    validators: { required: true, max: 200 },
  },
  {
    type: "text",
    headerName: "LBL_DETAIL_ADDRESS",
    field: "DTL_ADDR2",
    editable: true,
    insertable: true,
    width: 150,
    validators: { max: 1000 },
  },
  {
    type: "text",
    headerName: "LBL_ZIP_CODE",
    field: "ZIP_CD",
    editable: true,
    insertable: true,
    width: 150,
    validators: { max: 20 },
  },
  {
    // 우편번호 사용여부 (마스크 검증 플래그) — 표시/편집 안 함.
    type: "text",
    headerName: "LBL_ZIP_REQ_YN",
    field: "CTRY_MSK_YN",
    align: "center",
    width: 150,
    hide: true,
  },
  {
    // 식별코드 — 대문자 1글자. (서버 userValidator: 한 글자/대문자/중복체크)
    type: "text",
    headerName: "LBL_CUST_PREFIX",
    field: "CUST_PREFIX",
    align: "center",
    editable: true,
    insertable: true,
    width: 100,
    regex: /^[A-Z]$/,
    validators: {
      required: true,
      max: 1,
      regex: /^[A-Z]$/,
    },
  },
];

// ── sub01: 사업장 ──────────────────────────────────────────────
export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", field: "CUST_CD", hide: true },
  {
    // 사업장코드 — 추가행만 입력.
    type: "text",
    headerName: "LBL_BUPLA_CD",
    field: "BUPLA_CD",
    align: "center",
    insertable: true,
    width: 150,
  },
  {
    type: "text",
    headerName: "LBL_BUPLA_NM",
    field: "BUPLA_NM",
    align: "center",
    editable: true,
    insertable: true,
    width: 150,
  },
];

// ── sub02: 매출계약 ────────────────────────────────────────────
export const SUB02_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", field: "CUST_CD", hide: true },
  {
    // 매출계약코드 — 추가행만 입력. (서버 text 리터럴 → noLang)
    type: "text",
    headerName: "매출계약코드",
    noLang: true,
    field: "CUST_CNTRCT_CD",
    align: "center",
    insertable: true,
    width: 220,
    validators: { required: true, max: 60 },
  },
  {
    type: "text",
    headerName: "매출계약명",
    noLang: true,
    field: "CUST_CNTRCT_NM",
    align: "left",
    editable: true,
    insertable: true,
    width: 260,
    validators: { required: true, max: 200 },
  },
];
