// src/views/tender/tenderSearchMeta.ts
export const TENDER_SEARCH_META = [
  {
    key: "LGST_GRP_CD",
    type: "popup",
    label: "물류운영그룹",
    span: 5,
    condition: "equal",
    sqlId: "selectLogisticsgroupCodeName",
    dataType: "STRING",
  },
  {
    key: "DLVRY_DT",
    type: "dateRange",
    label: "납품일",
    span: 5,
    required: true,
    condition: "equal",
    dataType: "DATE",
  },
  {
    key: "FRM_LOC_NM",
    type: "text",
    label: "출발지명",
    span: 5,
    condition: "percent",
    dataType: "STRING",
  },
  {
    key: "ROUTH",
    type: "text",
    label: "경로",
    span: 5,
    condition: "percent",
    dataType: "STRING",
  },
  {
    key: "DSPCH_OP_STS",
    type: "combo",
    label: "배차진행상태",
    span: 5,
    condition: "chevronLast",
    sqlProp: "CODE",
    keyParam: "DSPCH_OP_STS",
    dataType: "STRING",
  },
  {
    key: "DSPCH_NO",
    type: "text",
    label: "배차번호",
    span: 5,
    condition: "percent",
    dataType: "NUMBER",
  },
  {
    key: "CARR_CD",
    type: "popup",
    label: "운송협력사",
    span: 5,
    condition: "equal",
    sqlId: "selectCarrList",
    dataType: "STRING",
  },
  {
    key: "DRVR_NM",
    type: "text",
    label: "운전자명",
    span: 5,
    condition: "percent",
    dataType: "STRING",
  },
  {
    key: "VEH_NO",
    type: "text",
    label: "차량번호",
    span: 5,
    condition: "percent",
    dataType: "STRING",
  },
  {
    key: "FREIGHT_YN",
    type: "checkbox",
    label: "운임예약가능여부",
    span: 5,
    condition: "equal",
    dataType: "STRING",
  },
  {
    key: "ARR_REQ_DTTM",
    type: "dateRange",
    label: "입차요청일시",
    span: 5,
    mode: "single",
    condition: "equal",
    dataType: "DATE",
  },
  {
    key: "VEH_TP_CD",
    type: "popup",
    label: "차량유형",
    span: 5,
    condition: "equal",
    sqlId: "selectVehTpList",
    dataType: "STRING",
  },
  {
    key: "VEH_OP_TP",
    type: "combo",
    label: "운영형태",
    span: 5,
    condition: "equal",
    sqlProp: "CODE",
    keyParam: "VEH_OP_TP",
    dataType: "STRING",
  },
] as const;
