// src/views/tender/tenderSearchMeta.ts
export const TENDER_SEARCH_META = [
  {
    key: "logiGroup",
    type: "popup",
    label: "물류운영그룹",
    span: 5,
    condition: "equal",
    sqlId: "selectLogisticsgroupCodeName",
  },
  {
    key: "deliveryDate",
    type: "dateRange",
    label: "납품일",
    span: 5,
    required: true,
    condition: "equal",
  },
  {
    key: "fromLocName",
    type: "text",
    label: "출발지명",
    span: 5,
    condition: "percent",
  },
  {
    key: "route",
    type: "text",
    label: "경로",
    span: 5,
    condition: "percent",
  },
  {
    key: "dispatchStatus",
    type: "combo",
    label: "배차진행상태",
    span: 5,
    condition: "chevronLast",
    sqlProp: "CODE",
    keyParam: "DSPCH_OP_STS",
  },
  {
    key: "dispatchNo",
    type: "text",
    label: "배차번호",
    span: 5,
    condition: "percent",
  },
  {
    key: "carrier",
    type: "popup",
    label: "운송협력사",
    span: 5,
    condition: "equal",
    sqlId: "selectCarrList",
  },
  {
    key: "driverName",
    type: "text",
    label: "운전자명",
    span: 5,
    condition: "percent",
  },
  {
    key: "vehicleNo",
    type: "text",
    label: "차량번호",
    span: 5,
    condition: "percent",
  },
  {
    key: "freightReservable",
    type: "combo",
    label: "운임예약가능여부",
    span: 5,
    condition: "equal",
    sqlProp: "CODE",
    keyParam: "YN",
  },
  {
    key: "arrivalRequestDateTime",
    type: "dateRange",
    label: "입차요청일시",
    span: 5,
    mode: "single",
    condition: "equal",
  },
  {
    key: "vehicleType",
    type: "popup",
    label: "차량유형",
    span: 5,
    condition: "equal",
    sqlId: "selectVehTpList",
  },
  {
    key: "operationType",
    type: "combo",
    label: "운영형태",
    span: 5,
    condition: "equal",
    sqlProp: "CODE",
    keyParam: "VEH_OP_TP",
  },
] as const;
