import { Lang } from "@/app/services/common/Lang";

export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_STATUS",
    field: "SIGNAL",
    align: "center",
    width: 50,
  },
  {
    type: "text",
    headerName: "LBL_DIVISION_CODE",
    field: "DIV_CD",
    editable: true,
    insertable: true,
    fieldType: "text",
    isPrimaryKey: true,
    lock: true,
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_DIVISION_NAME",
    field: "DIV_NM",
    editable: true,
    insertable: true,
    fieldType: "text",
    required: true,
    maxLength: 200,
  },
  {
    type: "text",
    headerName: "LBL_CUSTOMER_NAME",
    field: "CUST_CD",
    editable: true,
    insertable: true,
    fieldType: "combo",
    required: true,
  },
  {
    type: "address",
    headerName: "LBL_FIND_ADDRESS",
    colId: "ADDR_SEARCH",
    align: "center",
    width: 90,
    editable: true,
    insertable: true,
  },
  // ── 주소 (주소찾기 결과 write-back 대상, 읽기전용) ──────────────
  {
    type: "text",
    headerName: "LBL_ADDR",
    field: "ADDR_ID",
    width: 100,
    maxLength: 20,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_REPRESENTITIVE_ADDR",
    field: "DTL_ADDR1",
    width: 200,
    maxLength: 200,
  },
  {
    type: "text",
    headerName: "LBL_ZIP_CODE",
    field: "ZIP_CD",
    width: 70,
    maxLength: 20,
  },
  {
    type: "text",
    headerName: "LBL_STATE_CODE",
    field: "STT_CD",
    width: 150,
    align: "center",
    maxLength: 200,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_STATE_NAME",
    field: "STT_NM",
    width: 150,
    maxLength: 200,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_CITY_CODE",
    field: "CTY_CD",
    width: 150,
    align: "center",
    maxLength: 200,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_CITY_NAME",
    field: "CTY_NM",
    width: 150,
    maxLength: 200,
  },
  {
    type: "text",
    headerName: "LBL_COUNTRY",
    field: "CTRY_CD",
    width: 150,
    align: "center",
    maxLength: 200,
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_COUNTRY_NAME",
    field: "CTRY_NM",
    width: 150,
    maxLength: 200,
  },
  // ── 대표 정보 / 외부코드 (편집) ──────────────────────────────
  {
    type: "text",
    headerName: "LBL_REPRESENTATIVE_TEL_NO",
    field: "REP_TEL_NO",
    width: 150,
    editable: true,
    insertable: true,
    maskRe: /[0-9]/,
  },
  {
    type: "text",
    headerName: "LBL_REPRESENTITIVE",
    field: "REP_NM",
    width: 100,
    editable: true,
    insertable: true,
  },
  {
    type: "text",
    headerName: Lang.get("LBL_EXTERNAL_CODE") + "1",
    noLang: true,
    field: "REF1",
    width: 100,
    editable: true,
    insertable: true,
  },
  {
    type: "text",
    headerName: Lang.get("LBL_EXTERNAL_CODE") + "2",
    noLang: true,
    field: "REF2",
    width: 100,
    editable: true,
    insertable: true,
  },
];

export const SUB01_COLUMN_DEFS = [
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    editable: true,
    insertable: true,
    fieldType: "text",
    required: true,
    maxLength: 60,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_NAME",
    field: "LGST_GRP_NM",
    editable: true,
    insertable: true,
    fieldType: "text",
    required: true,
    maxLength: 200,
  },
];
