export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },

  {
    type: "text",
    headerName: "LBL_VEHICLE_TYPE_CODE",
    field: "VEH_TP_CD",
    isPrimaryKey: true,
    insertable: true,
    width: 150,
    areaNo: 0,
    areaLabel: "기본 정보",
    fieldType: "text",
    required: true,
  },
  {
    type: "text",
    headerName: "LBL_VEHICLE_TYPE_NAME",
    field: "VEH_TP_NM",
    insertable: true,
    editable: true,
    width: 150,
    areaNo: 0,
    fieldType: "text",
    required: true,
  },
  {
    type: "combo",
    headerName: "LBL_EX_VEH_TCD",
    field: "EX_VEH_TCD",
    codeKey: "exVehTcd",
    insertable: true,
    editable: true,
    width: 130,
    areaNo: 0,
    fieldType: "select",
  },
  {
    type: "combo",
    headerName: "LBL_VEH_TP_GRP",
    field: "VEH_TP_GRP",
    codeKey: "vehTpGrp",
    insertable: true,
    editable: true,
    width: 120,
    areaNo: 0,
    fieldType: "select",
  },
  {
    type: "numeric",
    headerName: "LBL_FUEL_EFFICIENCY",
    field: "FUEL_EFFICIENCY",
    insertable: true,
    editable: true,
    width: 80,
    areaNo: 0,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_DSPL_ORD",
    field: "DSPLY_SEQ",
    insertable: true,
    editable: true,
    width: 80,
    areaNo: 0,
    fieldType: "number",
  },
  {
    type: "check",
    headerName: "LBL_USE_YN",
    field: "USE_YN",
    insertable: true,
    editable: true,
    width: 80,
    areaNo: 0,
    fieldType: "check",
  },
  {
    type: "check",
    headerName: "LBL_ROOM_TEMP_YN",
    field: "ROOM_TEMP_YN",
    insertable: true,
    editable: true,
    width: 90,
    areaNo: 0,
    fieldType: "check",
  },

  {
    type: "numeric",
    headerName: "LBL_VOL",
    field: "LDNG_VOL",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    areaLabel: "적재 정보",
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_WGT",
    field: "LDNG_WGT",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_PALET",
    field: "LDNG_PLT_QTY",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_ROLLTAINER",
    field: "LDNG_RTNR_QTY",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_PBOX",
    field: "LDNG_PBOX_QTY",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_PAPER_BOX",
    field: "LDNG_BOX_QTY",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY1",
    field: "LDNG_FLEX_QTY1",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY2",
    field: "LDNG_FLEX_QTY2",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY3",
    field: "LDNG_FLEX_QTY3",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY4",
    field: "LDNG_FLEX_QTY4",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_FLEX_QTY5",
    field: "LDNG_FLEX_QTY5",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 1,
    fieldType: "number",
  },

  {
    type: "numeric",
    headerName: "LBL_EMPTY_VEH_WGT",
    field: "EMPTY_VEH_WGT",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 2,
    areaLabel: "차량 제원",
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_VEH_LENGTH",
    field: "VEH_LENGTH",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 2,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_VEH_WIDTH",
    field: "VEH_WIDTH",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 2,
    fieldType: "number",
  },
  {
    type: "numeric",
    headerName: "LBL_VEH_HEIGHT",
    field: "VEH_HEIGHT",
    insertable: true,
    editable: true,
    width: 100,
    areaNo: 2,
    fieldType: "number",
  },
];
