export const MAIN_ROW_KEYS = ["ITEM_CD", "SALES_ORG_CD"] as const;

export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_ITEM_CD",
    field: "ITEM_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_NM",
    field: "ITEM_NM",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_ITEM_TP",
    field: "ITEM_TP",
    codeKey: "itemType",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_STRG_CODE",
    field: "ITEM_STRG_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GRP",
    field: "ITEM_GRP_CD",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_EXT_ITEM_GRP",
    field: "EXT_ITEM_GRP_CD",
    codeKey: "extItemGrp",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_ITEM_FCD",
    field: "ITEM_FCD",
    codeKey: "itemFcd",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_CLASS",
    field: "ITEM_CCD_NM",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_PLANT_ITEM_STS",
    field: "PLANT_ITEM_STS",
    codeKey: "plantItemSts",
    editable: false,
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_WGT",
    field: "GROSS_WEIGHT",
    editable: false,
  },
  {
    type: "numeric",
    headerName: "LBL_NET_WGT",
    field: "NET_WEIGHT",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_WEIGHT_SCD",
    field: "WEIGHT_SCD",
    editable: false,
  },
  {
    type: "numeric",
    headerName: "LBL_VOL",
    field: "VOL",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_VOL_UOM",
    field: "VOL_SCD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_SIZE_DESCR",
    field: "SIZE_DESCR",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_PKG_GRP",
    field: "PKG_TP",
    codeKey: "pkgType",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_TEMP_CAL_OPT",
    field: "TEMP_TCD",
    codeKey: "vehTempTcd",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_DISTCHAIN_ITEM_STS",
    field: "DISTCHAIN_ITEM_STS",
    codeKey: "chaItemSts",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_SPEC_DESCR",
    field: "SPEC_DESCR",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_PLT_SPEC_TP",
    field: "PLT_SPEC_TP",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_BX_TP",
    field: "BOX_TP_DESCR",
    editable: false,
  },
  {
    type: "combo",
    headerName: "LBL_EXT_BOX_TP",
    field: "EXT_BOX_TP",
    codeKey: "extBoxType",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ORIGIN_NM",
    field: "ORIGIN_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_LB_MEAT_CUT_NM",
    field: "LB_MEAT_CUT_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_LB_ITEM_NM",
    field: "LB_ITEM_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_LB_TEMP_TP",
    field: "LB_TEMP_TP",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ALT_ITEM_NM",
    field: "ALT_ITEM_NM",
    editable: false,
  },
  {
    type: "numeric",
    headerName: "LBL_VOL_PER_BOX",
    field: "VOL_PER_BOX",
    editable: false,
  },
  {
    type: "numeric",
    headerName: "LBL_QTY_PER_BOX",
    field: "QTY_PER_BOX",
    editable: false,
  },
  {
    type: "numeric",
    headerName: "LBL_BOX_QTY_PER_PLT",
    field: "BOX_QTY_PER_PLT",
    editable: false,
  },
];

export const SUB02_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_ITEM_CD",
    field: "ITEM_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_NM",
    field: "ITEM_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_STRG_CODE",
    field: "ITEM_STRG_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_NUMERATOR",
    field: "NUMERATOR",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_DENOMINATOR",
    field: "DENOMINATOR",
    editable: false,
  },
];

export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_COMPANY_CD",
    field: "CUST_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_COMPANY_GROUP",
    field: "CUST_GRP_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_SALES_ORG",
    field: "SALES_ORG_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_DISTBUTE_CHANNEL",
    field: "DIST_CHANNEL",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_SALES_STRG_CODE",
    field: "SALES_UNIT_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_DELI_PLANT_CD",
    field: "DELI_PLANT_CD",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD1",
    field: "ITEM_GCD1",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD1_NM",
    field: "ITEM_GCD1_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD2",
    field: "ITEM_GCD2",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD2_NM",
    field: "ITEM_GCD2_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD3",
    field: "ITEM_GCD3",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD3_NM",
    field: "ITEM_GCD3_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD4",
    field: "ITEM_GCD4",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD4_NM",
    field: "ITEM_GCD4_NM",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD5",
    field: "ITEM_GCD5",
    editable: false,
  },
  {
    type: "text",
    headerName: "LBL_ITEM_GCD5_NM",
    field: "ITEM_GCD5_NM",
    editable: false,
  },
];
