export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_DIVISION_CODE",
    field: "DIV_CD",
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    align: "center",
    width: 140,
  },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_NAME",
    field: "LGST_GRP_NM",
    width: 200,
  },
];

export const DETAIL_COLUMN_DEFS = [
  { headerName: "No" },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
    hide: true,
  },
  {
    type: "text",
    headerName: "LBL_CNTR_CD",
    field: "CNTR_CD",
    align: "center",
    width: 150,
    flex: 1,
  },
  {
    type: "text",
    headerName: "LBL_CNTR_NM",
    field: "CNTR_NM",
    align: "left",
    width: 150,
    flex: 2,
  },
  {
    type: "numeric",
    headerName: "LBL_VOL",
    field: "VOL",
    align: "right",
    width: 80,
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "numeric",
    headerName: "LBL_WGT",
    field: "WGT",
    align: "right",
    width: 80,
    insertable: true,
    editable: true,
    required: true,
  },
  {
    type: "combo",
    headerName: "LBL_MAPPING_FLEX_QTY_FIELD",
    field: "MAPPING_FLEX_QTY_FIELD",
    codeKey: "flexQty",
    align: "center",
    width: 140,
    flex: 1,
    insertable: true,
    editable: true,
    required: true,
  },
];
