export const MAIN_COLUMN_DEFS = () => [
  {
    type: "text",
    field: "VEH_ID",
    hide: true,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    headerName: "LBL_VEH_NO",
    field: "VEH_NO",
    align: "center",
    width: 90,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_NO",
    field: "DSPCH_NO",
    align: "center",
    width: 90,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    headerName: "LBL_PLN_DSPCH_ROUTE",
    field: "ROUTE",
    align: "left",
    width: 150,
    editable: false,
    insertable: false,
  },
  {
    type: "combo",
    headerName: "LBL_TEMPER_STANDARD",
    field: "TMPR_VLTN_PLCY_CD",
    codeKey: "temperCntrlType",
    align: "center",
    width: 140,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    field: "FRZN_FRM_VAL",
    hide: true,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    field: "FRZN_TO_VAL",
    hide: true,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    field: "CHLD_FRM_VAL",
    hide: true,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    field: "CHLD_TO_VAL",
    hide: true,
    editable: false,
    insertable: false,
  },
  {
    type: "text",
    headerName: "LBL_DRIVER_NAME",
    field: "DRVR_NM",
    align: "center",
    width: 60,
    editable: false,
    insertable: false,
  },
  {
    type: "combo",
    headerName: "LBL_VEHICLE_OPERATION_TYPE",
    field: "VEH_OP_TP",
    codeKey: "vehOpTypeList",
    width: 60,
    align: "center",
    editable: false,
    insertable: false,
  },
  {
    type: "date",
    headerName: "LBL_DLVRY_DATE",
    field: "DLVRY_DT",
    width: 80,
    align: "center",
    editable: false,
    insertable: false,
  },
];
