export const MAIN_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "date", headerName: "LBL_REQUESTED_DELIVERY_DATE", field: "DLVRY_DT", align: "center", width: 100 },
  { type: "text", headerName: "LBL_INV_SYS_ID", field: "TO_SYS_CD", align: "center", width: 120 },
  { type: "text", headerName: "LBL_SHIPMENT_NUMBER", field: "SHPM_NO", align: "center", width: 120 },
  { type: "text", headerName: "LBL_ORDER_NO", field: "ORD_NO", align: "center", width: 140 },
  { type: "combo", headerName: "LBL_SHIPMENT_TYPE", field: "SHPM_TP", codeKey: "shpmTpList", align: "center", width: 100 },
  { type: "combo", headerName: "LBL_SHIPMENT_OP_STATUS", field: "SHPM_OP_STS", codeKey: "shpmOpStsList", align: "center", width: 120 },
  { type: "combo", headerName: "LBL_ORD_DLV_TP", field: "DLVRY_TP", codeKey: "dlvryTp", align: "center", width: 100 },
  { type: "text", headerName: "LBL_RMRK", field: "SHPM_RSN_DESC", align: "left", width: 200 },
  { type: "text", headerName: "LBL_DEPARTURE_CODE", field: "FRM_LOC_CD", align: "center", width: 80 },
  { type: "text", headerName: "LBL_DEPARTURE_NAME", field: "FRM_LOC_NM", align: "left", width: 120 },
  { type: "text", headerName: "LBL_DEPARTURE_ADDRESS", field: "FRM_DTL_ADDR1", align: "left", width: 220 },
  { type: "text", headerName: "LBL_DESTINATION_CODE", field: "TO_LOC_CD", align: "center", width: 80 },
  { type: "text", headerName: "LBL_DESTINATION_NAME", field: "TO_LOC_NM", align: "left", width: 120 },
  { type: "text", headerName: "LBL_DESTINATION_ADDRESS", field: "TO_DTL_ADDR1", align: "left", width: 220 },
  { type: "text", headerName: "LBL_SOLD_TO_CD", field: "SOLD_TO_CD", align: "center", width: 80 },
  { type: "text", headerName: "LBL_SOLD_TO_NM", field: "SOLD_TO_NM", align: "left", width: 120 },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL", field: "PLN_NET_VOL", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_GRS_VOL", field: "PLN_GRS_VOL", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_NET_WGT", field: "PLN_NET_WGT", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_GRS_WGT", field: "PLN_GRS_WGT", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY1", field: "PLN_FLEX_QTY1", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY2", field: "PLN_FLEX_QTY2", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY3", field: "PLN_FLEX_QTY3", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY4", field: "PLN_FLEX_QTY4", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY5", field: "PLN_FLEX_QTY5", align: "right", width: 100 },
  { type: "text", headerName: "LBL_PLAN_ID", field: "PLN_ID", align: "center", width: 100 },
  { type: "text", headerName: "LBL_PLAN_NAME", field: "PLN_NM", align: "left", width: 150 },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD", align: "center", width: 100 },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_NAME", field: "LGST_GRP_NM", align: "left", width: 150 },
  { type: "text", headerName: "LBL_DIVISION_CODE", field: "DIV_CD", align: "center", width: 100 },
  { type: "text", headerName: "LBL_DIVISION_NAME", field: "DIV_NM", align: "left", width: 150 },
  { type: "text", headerName: "LBL_COMPANY_CD", field: "CUST_CD", align: "center", width: 100 },
  { type: "text", headerName: "LBL_SALES_ORG_CD", field: "SALES_ORG_CD", align: "center", width: 100 },
  { type: "text", headerName: "LBL_PLANT_CD", field: "PLANT_CD", align: "center", width: 100 },
  { type: "text", headerName: "LBL_SLOC_CD", field: "SLOC_CD", align: "center", width: 100 },
  { type: "combo", headerName: "LBL_ORD_CRE_FLAG", field: "ORD_PRCS_TCD", codeKey: "ordCreFlag", align: "center", width: 100 },
  { type: "text", headerName: "LBL_COST_DISTR_FLAG", field: "AP_ALLOC_REQ_YN", align: "center", width: 100 },
  { type: "text", headerName: "LBL_CUST_PICKUP_YN", field: "CUST_PICKUP_YN", align: "center", width: 100 },
  { type: "combo", headerName: "LBL_DOC_TYPE", field: "DOC_TYPE", codeKey: "docTp", align: "center", width: 100 },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO", align: "center", width: 100 },
  { type: "text", headerName: "LBL_TARGET_SYS", field: "FINAL_AP_TARGET_SYS", align: "center", width: 120 },
  { type: "text", headerName: "LBL_FINL_DEST_CD", field: "FINL_DEST_CD", align: "center", width: 100 },
  { type: "text", headerName: "LBL_FINL_DEST_NM", field: "FINL_DEST_NM", align: "left", width: 120 },
];

export const SUB01_COLUMN_DEFS = [
  { headerName: "No" },
  { type: "text", headerName: "LBL_ORD_LINE_NO", field: "ORD_LINE_NO", align: "center", width: 100 },
  { type: "text", headerName: "LBL_ITEM_CD", field: "CUST_ITEM_CD", align: "left", width: 120 },
  { type: "text", headerName: "LBL_ITEM_NM", field: "CUST_ITEM_NM", align: "left", width: 120 },
  { type: "combo", headerName: "LBL_COMMODITY_CODE", field: "CMDT_CD", codeKey: "cmdtTpList", align: "left", width: 120 },
  { type: "numeric", headerName: "LBL_PLN_ORD_QTY", field: "PLN_ORD_QTY", align: "right", width: 100 },
  { type: "combo", headerName: "LBL_PLN_ORD_QTY_UOM", field: "PLN_ORD_QTY_UOM", codeKey: "itmUomList", align: "left", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_INV_QTY", field: "PLN_INV_QTY", align: "right", width: 100 },
  { type: "combo", headerName: "LBL_PLN_INV_QTY_UOM", field: "PLN_INV_QTY_UOM", codeKey: "itmUomList", align: "left", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL", field: "PLN_NET_VOL", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_GRS_VOL", field: "PLN_GRS_VOL", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_NET_WGT", field: "PLN_NET_WGT", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_GRS_WGT", field: "PLN_GRS_WGT", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY", align: "right", width: 100 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY1", field: "PLN_FLEX_QTY1", align: "right", width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY2", field: "PLN_FLEX_QTY2", align: "right", width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY3", field: "PLN_FLEX_QTY3", align: "right", width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY4", field: "PLN_FLEX_QTY4", align: "right", width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY5", field: "PLN_FLEX_QTY5", align: "right", width: 120 },
  { type: "text", headerName: "LBL_ITEM_REMARK", field: "SHPM_DTL_RSN_DESC", align: "left", width: 160 },
  { type: "text", headerName: "LBL_REFER_ORD_NO", field: "REFER_ORD_NO", align: "center", width: 100 },
  { type: "text", headerName: "LBL_REFER_ORD_LINE_NO", field: "REFER_ORD_LINE_NO", align: "center", width: 100 },
  { type: "text", headerName: "LBL_SALES_OFC_CD", field: "SALES_OFC", align: "center", width: 100 },
  { type: "text", headerName: "LBL_SALES_ORG_CD", field: "SALES_GRP", align: "center", width: 100 },
  { type: "text", headerName: "LBL_DISTR_CHNL", field: "DIST_CHANNEL", align: "center", width: 100 },
];
