import { standardAudit } from "@/app/components/grid/commonColumns";

// 메인 그리드
export const MAIN_COLUMN_DEFS = (setGridData?: (updater: any) => void) => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_LDNG_STAT", field: "SIGNAL" },
  {
    type: "date",
    headerName: "LBL_REQUESTED_DELIVERY_DATE",
    field: "DLVRY_DT",
  },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  {
    type: "numeric",
    headerName: "LBL_PLAN_ID",
    field: "PLN_ID",
    align: "center",
  },
  {
    type: "text",
    headerName: "LBL_DISPATCH_OPERATIONAL_STATUS",
    field: "DSPCH_OP_STS",
    codeKey: "dspchOpSts",
  },
  { type: "text", headerName: "LBL_CARRIER_NAME", field: "CARR_NM" },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO" },
  { type: "text", headerName: "LBL_ORDER_TYPE", field: "SHPM_TP_NM" },
  {
    type: "text",
    headerName: "LBL_VEHICLE_OPERATION_TYPE",
    field: "VEH_OP_TP",
    codeKey: "vehOpType",
  },
  {
    type: "text",
    headerName: "LBL_DSPCH_POD_OP_STS",
    field: "DSPCH_POD_OP_STS",
    codeKey: "dspchPodOpSts",
  },
  { type: "numeric", headerName: "LBL_ISSUED_POD_COUNT", field: "POD_CNT" },
  {
    type: "text",
    headerName: "LBL_POD_TCD",
    field: "POD_TCD",
    codeKey: "podTcd",
  },
  { type: "numeric", headerName: "LBL_STOP_CNT", field: "STOP_CNT" },
  { type: "text", headerName: "LBL_LANE", field: "LOC_LANE" },
  { type: "numeric", headerName: "LBL_FIX_SEQ", field: "RTN_NO" },
  { type: "text", headerName: "LBL_CONFIRMED_QTY_UOM", field: "SHPM_CFM_UOM" },
  { type: "text", headerName: "LBL_MEMO", field: "MEMO_DESC" },
  { type: "numeric", headerName: "LBL_VOL", field: "TTL_LD_VOL" },
  { type: "text", headerName: "LBL_LOADING_RATE_CBM", field: "TTL_LD_VOL_RT" },
  { type: "numeric", headerName: "LBL_WGT", field: "TTL_LD_WGT" },
  {
    type: "numeric",
    headerName: "LBL_WGT_LOADING_RATE",
    field: "TTL_LD_WGT_RT",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_FLEX_QTY1",
    field: "TTL_LD_FLEX_QTY1",
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY1",
    field: "TTL_LD_FLEX_QTY1_RT",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_FLEX_QTY2",
    field: "TTL_LD_FLEX_QTY2",
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY2",
    field: "TTL_LD_FLEX_QTY2_RT",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_FLEX_QTY3",
    field: "TTL_LD_FLEX_QTY3",
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY3",
    field: "TTL_LD_FLEX_QTY3_RT",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_FLEX_QTY4",
    field: "TTL_LD_FLEX_QTY4",
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY5",
    field: "TTL_LD_FLEX_QTY4_RT",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_FLEX_QTY5",
    field: "TTL_LD_FLEX_QTY5",
  },
  {
    type: "numeric",
    headerName: "LBL_LOADING_RATE_FLEX_QTY5",
    field: "TTL_LD_FLEX_QTY5_RT",
  },
  { type: "numeric", headerName: "LBL_TOTAL_CFM_VOL", field: "CFM_GRS_VOL" },
  { type: "numeric", headerName: "LBL_TOTAL_CFM_WGT", field: "CFM_NET_WGT" },
  { type: "numeric", headerName: "LBL_TTL_PBOX_QTY", field: "CFM_PBOX_QTY" },
  {
    type: "numeric",
    headerName: "LBL_TTL_CFM_FLEX_QTY2",
    field: "TTL_CFM_FLEX_QTY2",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_CFM_FLEX_QTY3",
    field: "TTL_CFM_FLEX_QTY3",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_CFM_FLEX_QTY4",
    field: "TTL_CFM_FLEX_QTY4",
  },
  {
    type: "numeric",
    headerName: "LBL_TTL_CFM_FLEX_QTY5",
    field: "TTL_CFM_FLEX_QTY5",
  },
  { type: "text", headerName: "LBL_DISPATCH_PLAN_TYPE", field: "DSPCH_TP" },
  { type: "text", headerName: "LBL_DIVISION", field: "DIV_CD" },
  {
    type: "text",
    headerName: "LBL_LOGISTICS_GROUP_CODE",
    field: "LGST_GRP_CD",
  },
  { type: "text", headerName: "LBL_ASISTANT_NUM", field: "ASST_NM" },
  { type: "text", headerName: "LBL_VEHICLE_CODE", field: "VEH_ID" },
  { type: "text", headerName: "LBL_VEHICLE_TYPE_NAME", field: "VEH_TP_NM" },
  { type: "text", headerName: "LBL_DRIVER_CODE", field: "DRVR_ID" },
  { type: "text", headerName: "LBL_DRIVER_NAME", field: "DRVR_NM" },
  ...standardAudit(setGridData),
  { type: "numeric", headerName: "TNDR_REQ_ID", field: "TNDR_REQ_ID" },
  { type: "text", headerName: "TNDR_REQ_USR_ID", field: "TNDR_REQ_USR_ID" },
  { type: "text", headerName: "TNDR_REQ_DTTM", field: "TNDR_REQ_DTTM" },
  { type: "text", headerName: "AP_FI_STS", field: "AP_FI_STS" },
  { type: "text", headerName: "AP_PROC_TP", field: "AP_PROC_TP" },
  { type: "numeric", headerName: "TRIP_ID", field: "TRIP_ID" },
  { type: "text", headerName: "LBL_CARRIER_CODE", field: "CARR_CD" },
  { type: "text", headerName: "LBL_VEHICLE_TYPE_CODE", field: "VEH_TP_CD" },
];

// 주문정보 - 좌측
export const ORDER_COLUMN_DEFS = (setGridData?: (updater: any) => void) => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_LDNG_STAT", field: "SIGNAL" },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO" },
  { type: "numeric", headerName: "LBL_PLAN_ID", field: "PLN_ID" },
  {
    type: "numeric",
    headerName: "LBL_INV_SYS_ID",
    field: "INV_SYS_ID",
    codeKey: "invSys",
  },
  { type: "text", headerName: "LBL_ORDER_NO", field: "ORD_NO" },
  { type: "text", headerName: "LBL_DEPARTURE_CODE", field: "FRM_LOC_CD" },
  { type: "text", headerName: "LBL_DEPARTURE_NAME", field: "FRM_LOC_NM" },
  { type: "text", headerName: "LBL_DESTINATION_CD", field: "TO_LOC_CD" },
  { type: "text", headerName: "LBL_DESTINATION_NAME", field: "TO_LOC_NM" },
  { type: "numeric", headerName: "LBL_PLANNED_QTY", field: "PLN_ORD_QTY_LIST" },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_QTY",
    field: "CFM_ORD_QTY_LIST_QTY",
  },
  { type: "text", headerName: "LBL_CUSTOMER_CODE", field: "CUST_CD" },
  { type: "text", headerName: "LBL_CUSTOMER_NAME", field: "CUST_NM" },
  { type: "text", headerName: "LBL_SOLD_TO_CD", field: "SOLD_TO_CD" },
  { type: "text", headerName: "LBL_SOLD_TO_NM", field: "SOLD_TO_NM" },
  {
    type: "text",
    headerName: "LBL_SHIPMENT_OP_STATUS",
    field: "SHPM_OP_STS",
    codeKey: "shpmOpSts",
  },
  { type: "text", headerName: "LBL_SHIPMENT_NUMBER", field: "SHPM_NO" },
  { type: "text", headerName: "LBL_TO_STATE_CD", field: "STT_CD" },
  { type: "text", headerName: "LBL_TO_STATE_NM", field: "STT_NM" },
  { type: "text", headerName: "LBL_TO_DETAIL_ADDRESS_1", field: "DTL_ADDR1" },
  { type: "text", headerName: "LBL_TO_DETAIL_ADDRESS_2", field: "DTL_ADDR2" },
  { type: "text", headerName: "LBL_CUST_PICKUP_YN", field: "CUST_PICKUP_YN" },
];

// 주문정보 - 우측 (품목)
export const ORDER_ITEM_COLUMN_DEFS = (
  setGridData?: (updater: any) => void,
) => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_ITEM_CODE", field: "CUST_ITEM_CD" },
  { type: "text", headerName: "LBL_ITEM_NAME", field: "CUST_ITEM_NM" },
  { type: "text", headerName: "LBL_PLN_ORD_QTY", field: "PLN_ORD_QTY" },
  { type: "text", headerName: "LBL_CFM_ORD_QTY", field: "CFM_ORD_QTY" },
  {
    type: "text",
    headerName: "LBL_PLN_ORD_QTY_UOM",
    field: "PLN_ORD_QTY_UOM",
    codeKey: "itmUom",
  },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL", field: "PLN_NET_VOL" },
  { type: "numeric", headerName: "LBL_CFM_NET_VOL", field: "CFM_NET_VOL" },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL", field: "PLN_GRS_VOL" },
  { type: "numeric", headerName: "LBL_CFM_NET_VOL", field: "CFM_GRS_VOL" },
  { type: "numeric", headerName: "LBL_PLN_NET_WGT", field: "PLN_NET_WGT" },
  { type: "numeric", headerName: "LBL_CFM_NET_WGT", field: "CFM_NET_WGT" },
  { type: "numeric", headerName: "LBL_PLN_GRS_WGT", field: "PLN_GRS_WGT" },
  { type: "numeric", headerName: "LBL_CFM_GRS_WGT", field: "CFM_GRS_WGT" },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY" },
  { type: "numeric", headerName: "LBL_CFM_PLT_QTY", field: "CFM_PLT_QTY" },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY" },
  { type: "numeric", headerName: "LBL_CFM_RTNR_QTY", field: "CFM_RTNR_QTY" },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY" },
  { type: "numeric", headerName: "LBL_CFM_PBOX_QTY", field: "CFM_PBOX_QTY" },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY" },
  { type: "numeric", headerName: "LBL_CFM_BOX_QTY", field: "CFM_BOX_QTY" },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY1",
    field: "PLN_FLEX_QTY1",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY1",
    field: "CFM_FLEX_QTY1",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY2",
    field: "PLN_FLEX_QTY2",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY2",
    field: "CFM_FLEX_QTY2",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY3",
    field: "PLN_FLEX_QTY3",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY3",
    field: "CFM_FLEX_QTY3",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY4",
    field: "PLN_FLEX_QTY4",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY4",
    field: "CFM_FLEX_QTY4",
  },
  {
    type: "numeric",
    headerName: "LBL_PLANNED_FLEX_QTY5",
    field: "PLN_FLEX_QTY5",
  },
  {
    type: "numeric",
    headerName: "LBL_CONFIRMED_FLEX_QTY5",
    field: "CFM_FLEX_QTY5",
  },
  ...standardAudit(setGridData),
];

// 인수증
export const RECEIPT_COLUMN_DEFS = (setGridData?: (updater: any) => void) => [
  { headerName: "No" },
  { type: "numeric", headerName: "LBL_POD_ID", field: "POD_ID" },
  { type: "numeric", headerName: "LBL_REISSUE_CNT", field: "REISSUE_CNT" },
  {
    type: "text",
    headerName: "LBL_POD_OP_STS",
    field: "POD_OP_STS",
    codeKey: "podOpSts",
  },
  {
    type: "text",
    headerName: "LBL_POD_TCD",
    field: "POD_TCD",
    codeKey: "podTcd",
  },
  { type: "text", headerName: "LBL_POD_ISSUE_USR", field: "CRE_USR_ID" },
  { type: "text", headerName: "LBL_POD_ISSUED_DTTM", field: "CRE_DTTM" },
];

// 인수증 발행이력
export const RECEIPT_HISTORY_COLUMN_DEFS = (
  setGridData?: (updater: any) => void,
) => [
  { headerName: "No" },
  { type: "numeric", headerName: "LBL_POD_ID", field: "POD_ID" },
  {
    type: "text",
    headerName: "LBL_POD_TCD",
    field: "POD_TCD",
    codeKey: "podTcd",
  },
  {
    type: "text",
    headerName: "LBL_POD_LOG_EVNT_CD",
    field: "POD_LOG_EVNT_CD",
    codeKey: "podLogEvntCd",
  },
  ...standardAudit(setGridData, {
    delete: false,
    rowStatus: false,
    insertPerson: true,
    insertDate: true,
    updatePerson: false,
    updateTime: false,
  }),
];
