// 메인 그리드
export const MAIN_COLUMN_DEFS = () => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_LDNG_STAT", field: "SIGNAL", align: "center", width: 60 },
  { type: "date", headerName: "LBL_REQUESTED_DELIVERY_DATE", field: "DLVRY_DT", align: "center", width: 100 },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO", align: "center" },
  { type: "text", headerName: "LBL_PLAN_ID", field: "PLN_ID", align: "center", hide: true },
  { type: "text", headerName: "LBL_DISPATCH_OPERATIONAL_STATUS", field: "DSPCH_OP_STS", statusStyle: "DSPCH_OP_STS", codeKey: "dspchOpSts", align: "center", width: 150 },
  { type: "text", headerName: "LBL_CARRIER_NAME", field: "CARR_NM", width: 200 },
  { type: "text", headerName: "LBL_VEH_NO", field: "VEH_NO", align: "center" },
  { type: "text", headerName: "LBL_ORDER_TYPE", field: "SHPM_TP_NM", align: "center" },
  { type: "text", headerName: "LBL_VEHICLE_OPERATION_TYPE", field: "VEH_OP_TP", codeKey: "vehOpType", align: "center", width: 90 },
  { type: "text", headerName: "LBL_DSPCH_POD_OP_STS", field: "DSPCH_POD_OP_STS", codeKey: "dspchPodOpSts", align: "center", width: 150 },
  { type: "numeric", headerName: "LBL_ISSUED_POD_COUNT", field: "POD_CNT", align: "right", width: 120 },
  { type: "text", headerName: "LBL_POD_TCD", field: "POD_TCD", codeKey: "podTcd", align: "center", width: 150 },
  { type: "numeric", headerName: "LBL_STOP_CNT", field: "STOP_CNT", align: "right", width: 80 },
  { type: "text", headerName: "LBL_LANE", field: "LOC_LANE", width: 200 },
  { type: "text", headerName: "LBL_FIX_SEQ", field: "RTN_NO", align: "center", width: 60 },
  { type: "text", headerName: "LBL_CONFIRMED_QTY_UOM", field: "SHPM_CFM_UOM", width: 150 },
  { type: "text", headerName: "LBL_MEMO", field: "MEMO_DESC", width: 100 },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL", field: "PLN_NET_VOL", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL_RT", field: "PLN_NET_VOL_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_GRS_VOL", field: "PLN_GRS_VOL", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_GRS_VOL_RT", field: "PLN_GRS_VOL_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_NET_WGT", field: "PLN_NET_WGT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_NET_WGT_RT", field: "PLN_NET_WGT_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_GRS_WGT", field: "PLN_GRS_WGT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_GRS_WGT_RT", field: "PLN_GRS_WGT_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY_RT", field: "PLN_PLT_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY_RT", field: "PLN_RTNR_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY_RT", field: "PLN_BOX_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY_RT", field: "PLN_PBOX_RT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY1", field: "PLN_FLEX_QTY1", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_FLEX_QTY1_RT", field: "PLN_FLEX_QTY1_RT", align: "right", decimalPlaces: 1, width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY2", field: "PLN_FLEX_QTY2", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_FLEX_QTY2_RT", field: "PLN_FLEX_QTY2_RT", align: "right", decimalPlaces: 1, width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY3", field: "PLN_FLEX_QTY3", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_FLEX_QTY3_RT", field: "PLN_FLEX_QTY3_RT", align: "right", decimalPlaces: 1, width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY4", field: "PLN_FLEX_QTY4", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_FLEX_QTY4_RT", field: "PLN_FLEX_QTY4_RT", align: "right", decimalPlaces: 1, width: 120 },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY5", field: "PLN_FLEX_QTY5", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_PLN_FLEX_QTY5_RT", field: "PLN_FLEX_QTY5_RT", align: "right", decimalPlaces: 1, width: 120 },
  { type: "numeric", headerName: "LBL_CFM_NET_VOL", field: "CFM_NET_VOL", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CFM_GRS_VOL", field: "CFM_GRS_VOL", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CFM_NET_WGT", field: "CFM_NET_WGT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CFM_GRS_WGT", field: "CFM_GRS_WGT", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CFM_PLT_QTY", field: "CFM_PLT_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CFM_RTNR_QTY", field: "CFM_RTNR_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CFM_PBOX_QTY", field: "CFM_PBOX_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CFM_BOX_QTY", field: "CFM_BOX_QTY", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY1", field: "CFM_FLEX_QTY1", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY2", field: "CFM_FLEX_QTY2", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY3", field: "CFM_FLEX_QTY3", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY4", field: "CFM_FLEX_QTY4", align: "right", decimalPlaces: 1 },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY5", field: "CFM_FLEX_QTY5", align: "right", decimalPlaces: 1 },
  { type: "text", headerName: "LBL_DISPATCH_PLAN_TYPE", field: "DSPCH_TP", align: "center", hide: true },
  { type: "text", headerName: "LBL_DIVISION", field: "DIV_CD", align: "center" },
  { type: "text", headerName: "LBL_LOGISTICS_GROUP_CODE", field: "LGST_GRP_CD", align: "center" },
  { type: "text", headerName: "LBL_ASISTANT_NUM", field: "ASST_NM" },
  { type: "text", headerName: "LBL_VEHICLE_CODE", field: "VEH_ID", align: "center" },
  { type: "text", headerName: "LBL_VEHICLE_TYPE_NAME", field: "VEH_TP_NM" },
  { type: "text", headerName: "LBL_DRIVER_CODE", field: "DRVR_ID", align: "center" },
  { type: "text", headerName: "LBL_DRIVER_NAME", field: "DRVR_NM", align: "center" },
  { type: "text", headerName: "TNDR_REQ_ID", field: "TNDR_REQ_ID", noLang: true, align: "center", hide: true },
  { type: "text", headerName: "TNDR_REQ_USR_ID", field: "TNDR_REQ_USR_ID", noLang: true, align: "center", hide: true },
  { type: "text", headerName: "TNDR_REQ_DTTM", field: "TNDR_REQ_DTTM", noLang: true, align: "center", hide: true },
  { type: "text", headerName: "AP_FI_STS", field: "AP_FI_STS", noLang: true, align: "center", hide: true },
  { type: "text", headerName: "AP_PROC_TP", field: "AP_PROC_TP", noLang: true, align: "center", hide: true },
  { type: "text", headerName: "TRIP_ID", field: "TRIP_ID", noLang: true, align: "center", hide: true },
  { type: "text", headerName: "LBL_CARRIER_CODE", field: "CARR_CD", align: "center", hide: true },
  { type: "text", headerName: "LBL_VEHICLE_TYPE_CODE", field: "VEH_TP_CD", align: "center", hide: true },
];

// 주문정보 - 좌측
export const ORDER_COLUMN_DEFS = () => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_LDNG_STAT", field: "SIGNAL", align: "center", width: 80 },
  { type: "text", headerName: "LBL_DISPATCH_NO", field: "DSPCH_NO", hide: true },
  { type: "text", headerName: "LBL_PLAN_ID", field: "PLN_ID", hide: true },
  { type: "text", headerName: "LBL_INV_SYS_ID", field: "INV_SYS_ID", codeKey: "invSys", align: "center", width: 120 },
  { type: "text", headerName: "LBL_ORDER_NO", field: "ORD_NO", align: "center", width: 100 },
  { type: "text", headerName: "LBL_DEPARTURE_CODE", field: "FRM_LOC_CD", align: "center", width: 65 },
  { type: "text", headerName: "LBL_DEPARTURE_NAME", field: "FRM_LOC_NM", width: 121 },
  { type: "text", headerName: "LBL_DESTINATION_CD", field: "TO_LOC_CD", align: "center", width: 75 },
  { type: "text", headerName: "LBL_DESTINATION_NAME", field: "TO_LOC_NM", width: 200 },
  { type: "numeric", headerName: "LBL_PLANNED_QTY", field: "PLN_ORD_QTY_LIST", align: "right", width: 70, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_QTY", field: "CFM_ORD_QTY_LIST_QTY", align: "right", width: 70, summable: true },
  { type: "text", headerName: "LBL_CUSTOMER_CODE", field: "CUST_CD", align: "center", width: 80 },
  { type: "text", headerName: "LBL_CUSTOMER_NAME", field: "CUST_NM", width: 80 },
  { type: "text", headerName: "LBL_SOLD_TO_CD", field: "SOLD_TO_CD", align: "center", width: 70 },
  { type: "text", headerName: "LBL_SOLD_TO_NM", field: "SOLD_TO_NM", width: 100 },
  { type: "text", headerName: "LBL_SHIPMENT_OP_STATUS", field: "SHPM_OP_STS", statusStyle: "SHPM_OP_STS", codeKey: "shpmOpSts", align: "center", width: 130 },
  { type: "text", headerName: "LBL_SHIPMENT_NUMBER", field: "SHPM_NO", width: 150 },
  { type: "text", headerName: "LBL_TO_STATE_CD", field: "STT_CD", align: "center", width: 150 },
  { type: "text", headerName: "LBL_TO_STATE_NM", field: "STT_NM", width: 150 },
  { type: "text", headerName: "LBL_TO_DETAIL_ADDRESS_1", field: "DTL_ADDR1", width: 200 },
  { type: "text", headerName: "LBL_TO_DETAIL_ADDRESS_2", field: "DTL_ADDR2", width: 200 },
  { type: "text", headerName: "LBL_CUST_PICKUP_YN", field: "CUST_PICKUP_YN", align: "center", width: 80 },
];

// 주문정보 - 우측 (품목)
export const ORDER_ITEM_COLUMN_DEFS = () => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_ITEM_CODE", field: "CUST_ITEM_CD", align: "center" },
  { type: "text", headerName: "LBL_ITEM_NAME", field: "CUST_ITEM_NM" },
  { type: "numeric", headerName: "LBL_PLN_ORD_QTY", field: "PLN_ORD_QTY", align: "right", decimalPlaces: 2, summable: true },
  { type: "numeric", headerName: "LBL_CFM_ORD_QTY", field: "CFM_ORD_QTY", align: "right", decimalPlaces: 2, summable: true, validators: { min: 0 } },
  { type: "text", headerName: "LBL_PLN_ORD_QTY_UOM", field: "PLN_ORD_QTY_UOM", codeKey: "itmUom", align: "center" },
  { type: "numeric", headerName: "LBL_PLN_NET_VOL", field: "PLN_NET_VOL", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_NET_VOL", field: "CFM_NET_VOL", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLN_GRS_VOL", field: "PLN_GRS_VOL", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_GRS_VOL", field: "CFM_GRS_VOL", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLN_NET_WGT", field: "PLN_NET_WGT", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_NET_WGT", field: "CFM_NET_WGT", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLN_GRS_WGT", field: "PLN_GRS_WGT", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_GRS_WGT", field: "CFM_GRS_WGT", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLN_PLT_QTY", field: "PLN_PLT_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_PLT_QTY", field: "CFM_PLT_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLN_RTNR_QTY", field: "PLN_RTNR_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_RTNR_QTY", field: "CFM_RTNR_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLN_PBOX_QTY", field: "PLN_PBOX_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_PBOX_QTY", field: "CFM_PBOX_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLN_BOX_QTY", field: "PLN_BOX_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CFM_BOX_QTY", field: "CFM_BOX_QTY", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY1", field: "PLN_FLEX_QTY1", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY1", field: "CFM_FLEX_QTY1", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY2", field: "PLN_FLEX_QTY2", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY2", field: "CFM_FLEX_QTY2", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY3", field: "PLN_FLEX_QTY3", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY3", field: "CFM_FLEX_QTY3", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY4", field: "PLN_FLEX_QTY4", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY4", field: "CFM_FLEX_QTY4", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_PLANNED_FLEX_QTY5", field: "PLN_FLEX_QTY5", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "numeric", headerName: "LBL_CONFIRMED_FLEX_QTY5", field: "CFM_FLEX_QTY5", align: "right", width: 100, decimalPlaces: 4, summable: true },
  { type: "text", headerName: "LBL_SHIPMENT_ID", field: "SHPM_DTL_ID", hide: true },
  { type: "text", headerName: "LBL_LD_INSP_MDT", field: "REQUIRED_LD_RESULT_INTEGRATION_WITH_IMS", hide: true },
  { type: "text", headerName: "LBL_DISPATCH_OPERATIONAL_STATUS", field: "DSPCH_OP_STS", statusStyle: "DSPCH_OP_STS", codeKey: "dspchOpSts", align: "center", hide: true },
];

// 인수증
export const RECEIPT_COLUMN_DEFS = () => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_POD_ID", field: "POD_ID", align: "center", width: 100 },
  { type: "numeric", headerName: "LBL_REISSUE_CNT", field: "REISSUE_CNT", align: "right", width: 100 },
  { type: "text", headerName: "LBL_POD_OP_STS", field: "POD_OP_STS", codeKey: "podOpSts", align: "center", width: 100 },
  { type: "text", headerName: "LBL_POD_TCD", field: "POD_TCD", codeKey: "podTcd", align: "center", width: 150 },
  { type: "text", headerName: "LBL_POD_ISSUE_USR", field: "CRE_USR_ID", align: "center", width: 130 },
  { type: "text", headerName: "LBL_POD_ISSUED_DTTM", field: "CRE_DTTM", align: "center", width: 130 },
];

// 인수증 발행이력
export const RECEIPT_HISTORY_COLUMN_DEFS = () => [
  { headerName: "No" },
  { type: "text", headerName: "LBL_POD_ID", field: "POD_ID", align: "center", width: 100 },
  { type: "text", headerName: "LBL_POD_TCD", field: "POD_TCD", codeKey: "podTcd", align: "center", width: 150 },
  { type: "text", headerName: "LBL_POD_LOG_EVNT_CD", field: "POD_LOG_EVNT_CD", codeKey: "podLogEvntCd", align: "center", width: 250 },
];
